### DISCUSSION TITLE
Dynamic Theme works only changes primaryColor

### DISCUSSION THREAD

**Discussion by GeorgeFlorian** [ant-design/ant-design#36647] [Q&A]
I am following this guide: https://ant.design/docs/react/customize-theme-variable in order to change the theme colors inside a React app.

So far, only the `primaryColor` property changes something, the rest don't change anything no matter what color I write.

I have styled *all* of my components by importing the antd CSS file and different components from antd like this:
```
import 'antd/dist/antd.min.css';
import { Avatar, Col, Row, List, Skeleton, Button } from 'antd';
```

This is App.js:
```javascript
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import Login from './components/pages/Login';
import Dashboard from './components/pages/Dashboard';
import Register from './components/pages/Register';
import PrivateRoute from './components/pages/PrivateRoute';

import 'antd/dist/antd.variable.min.css';
import { ConfigProvider } from 'antd';

ConfigProvider.config({
  theme: {
    primaryColor: '#98212E', // primary color for all components
    componentBackground: '#98212E',
    linkColor: '#1890ff', // link color
    successColor: '#52c41a', // success state color
    warningColor: '#faad14', // warning state color
    errorColor: '#f5222d', // error state color
    fontSizeBase: '14px', // major text font size
    headingColor: 'rgba(0, 0, 0, 0.85)', // heading text color
    textColor: 'rgba(0, 0, 0, 0.65)', // major text color
    textColorSecondary: 'rgba(0, 0, 0, 0.45)', // secondary text color
    disabledColor: 'rgba(0, 0, 0, 0.25)', // disable state color
    borderRadiusBase: '2px', // major border radius
    borderColorBase: '#d9d9d9', // major border color
    boxShadowBase:
      '0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 6px 16px 0 rgba(0, 0, 0, 0.08) 0 9px 28px 8px rgba(0, 0, 0, 0.05)', // major shadow for layers
  },
});
function App() {
  // const isAuth = useSelector((state) => state.login.isAuthenticated);

  return (
    <>
      <ConfigProvider>
        <Router>
          <Routes>
            <Route element={<PrivateRoute />}>
              <Route path='/' element={<Dashboard />} />
            </Route>
            <Route path='/login' element={<Login />} />
            <Route path='/register' element={<Register />} />
          </Routes>
        </Router>
      </ConfigProvider>
    </>
  );
}

export default App;
```

I have also tried using 
```javascript
ConfigProvider.config({
  prefixCls: 'custom',
  theme: {
    primaryColor: '#25b864',
  },
});
```
with
```javascript
  <ConfigProvider prefixCls="custom">
    <MyApp />
  </ConfigProvider>
```

and `lessc --js --modify-var="ant-prefix=custom" antd/dist/antd.variable.less modified.css`

but this destroys all the styling as if there were no CSS applied to the app.

Any thoughts ?

**Comment by valcosmos** [comment]
Hello, I tried this, it does work.

Hope it can help u.

1. Compile to css file.

```sh
# complile default css file

npx lessc --js --modify-var="ant-prefix=custom-default" node_modules/antd/dist/antd.less custom-default.css

# compile dark theme css file

npx lessc --js --modify-var="ant-prefix=custom-dark" node_modules/antd/dist/antd.dark.less custom-dark.css

```

2. Modify the content of the css file.

in default css file

```css
// =======add .custom-default====
body .custom-default {
// =========================
  margin: 0;
  color: rgba(0, 0, 0, 0.85);
  font-size: 14px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  font-variant: tabular-nums;
  line-height: 1.5715;
  background-color: #fff;
  font-feature-settings: 'tnum';
}

```

in dark theme css file

```css
//  ======== add `.custom-dark`=====
body .custom-dark {
// =======================
  margin: 0;
  color: rgba(255, 255, 255, 0.85);
  font-size: 14px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  font-variant: tabular-nums;
  line-height: 1.5715;
  background-color: #000;
  font-feature-settings: 'tnum';
}
```

3. Use it in the component.

in `index.tsx`

```tsx

import React, { useState } from 'react'

import { Empty, Layout, Radio, RadioChangeEvent, Space } from 'antd'
import { ConfigProvider } from 'antd'

import '../custom-default.css' // import default css file
import '../custom-dark.css' // import dark theme css file

import './index.css'

export default function App() {
  const [prefix, setPrefix] = useState('custom-default')

  const handlePrefixChange = (e: RadioChangeEvent) => {
    setPrefix(e.target.value)
  }

  return (
    <ConfigProvider prefixCls={prefix}>
      <div className={`App ${prefix}`} style={{ height: '100%' }}>
        <Layout style={{ height: '100%' }}>
          <Layout.Content>
            <Space>
              Change Theme:
              <Radio.Group onChange={handlePrefixChange} value={prefix}>
                <Radio value="custom-default">default Style</Radio>
                <Radio value="custom-dark">dark Style</Radio>
              </Radio.Group>
            </Space>
            <br />

            <Empty />
          </Layout.Content>
        </Layout>
      </div>
    </ConfigProvider>
  )
}


```

<img width="477" alt="image" src="https://user-images.githubusercontent.com/53572196/180596627-4efe07fa-98ca-4f9c-a621-1fabdc27d378.png">

<img width="336" alt="image" src="https://user-images.githubusercontent.com/53572196/180596634-09c80453-13c3-489d-8029-6cd89097041a.png">
