### DISCUSSION TITLE
Is there a way to prevent the table columns from displaying on multiple lines?

### DISCUSSION THREAD

**Discussion by code3z** [ant-design/ant-design#36980] [Q&A]
I'd rather have the table stay expanded (and the user have to scroll) than have the column titles collapse into multiple lines: 
![image](https://user-images.githubusercontent.com/77302900/183762408-f71b412a-f9cc-47f0-ace4-5399f553b592.png)

**Comment by valcosmos** [comment]
Hello, u can set the `width` property on this column. 

```tsx
const columns: ColumnsType<DataType> = [
  {
    title: 'Name',
    dataIndex: 'name',
    sorter: true,
    render: name => `${name.first} ${name.last}`,
// ======just like this ==============
    width: '300px',
  }
]
```

Or use css to set a fixed width for this element.

```tsx
const columns: ColumnsType<DataType> = [
  {
    title: 'GenderGenderGender Gender Gender Gender',
    dataIndex: 'gender',
    filters: [
      { text: 'Male', value: 'male' },
      { text: 'Female', value: 'female' }
    ],
// set class name==========
    className: 'column-width'
  }
]
```

```css
.column-width .ant-table-column-title {
  width: 100px;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
```

Hope it can help u. :)
