### DISCUSSION TITLE
How to select deep nested classes when using React css modules ?

### DISCUSSION THREAD

**Discussion by GeorgeFlorian** [ant-design/ant-design#40173] [Q&A]
How can I reach `.ant-select-item-option-content` when using CSS modules
I've got a `<Select />` inside a React component:
```
import styles from "./NavMenu.module.css";

  return (
    <Row
      className={[styles.container, "mt-minus-100"].join(" ")}
      align="middle"
    >
      <Col span={24} className={styles.wrapper} id="wrapper">
        <Select
          className={[styles.menu, "menu-target"].join(" ")}
          options={items}
          defaultValue={currentvalue.label}
          bordered={false}
          onSelect={onSelect}
          value={currentvalue.value}
          size="large"
          dropdownAlign={{ offset: [0, 0] }}
          dropdownStyle={{
            backgroundColor: "var(--unccd-blue)",
            borderRadius: 0,
          }}
          popupClassName="_dropdown"
          getPopupContainer={() => document.getElementById("wrapper")}
        />
      </Col>
    </Row>
  );
```

I've set a class name to the actual dropdown using `popupClassName="_dropdown"`, but there are A LOT of child divs that ANTD creates and I can't seem to figure out how to reach `.ant-select-item-option-content`.

I have tried using the following but it does NOT work:
```css
._dropdown :global(.ant-select-item-option-content) {
  white-space: break-spaces !important;
  word-break: break-word !important;
}

._dropdown :global(.ant-select-item-option .ant-select-item-option-content) {
  white-space: break-spaces !important;
  word-break: break-word !important;
}
```
