### DISCUSSION TITLE
How to apply word-wrap to ANTD Select title and dropdown items ?

### DISCUSSION THREAD

**Discussion by GeorgeFlorian** [ant-design/ant-design#40174] [Q&A]
I am trying to apply break word to the TITLE of a Select component:
This is what I've managed until now: https://codesandbox.io/s/basic-usage-antd-4-24-7-forked-8jzp29?file=/demo.js

I have applied style:
```css
.ant-select-item-option-content {
  white-space: break-spaces;
  word-break: break-word;
}

.ant-select-show-search.ant-select:not(.ant-select-customize-input)
  .ant-select-selector {
  height: auto;
}
.ant-select-single.ant-select-show-arrow .ant-select-selection-item {
  white-space: normal;
  word-break: break-all;
}

```

But I can't manage to apply this to the selected/active/title item of the Select.

**Comment by Wxh16144** [comment]
It looks like you have an error in your css module file?

```css
.menu :global .ant-select-selection-item,
.menu :global .ant-select-item-option-content {
  color: red;
  white-space: break-spaces;
  word-break: break-word;
}
```
