### DISCUSSION TITLE
请问table如何可以 hover 行和列都高亮！

### DISCUSSION THREAD

**Discussion by eternallycyf** [ant-design/ant-design#40594] [Q&A]
<img width="1148" alt="截屏2023-02-07 16 01 02" src="https://user-images.githubusercontent.com/63464198/217186155-0621e3b0-ddc6-4e07-bc51-ab05471fd196.png">

## 目前只提供了hover行的API 
```ts 
 onRow={(record) => {
    return {
      onClick: (event) => {}, // 点击行
      onMouseEnter: (event) => {}, // 鼠标移入行
      onMouseLeave: (event) => {},
    };
  }}
```

## 目前只能实现 点击的单元格 横竖高亮
```less
 @hoverColor: #FFEFDB;
 @rowLength: 20;

 .tdHover1(@n, @i: 1) when (@i =< @n) {
   .ant-table-tbody tr:nth-child(@{i})>td:nth-child(1) {
     background-color: @hoverColor !important;
   }

   .ant-table-thead {
     tr:nth-child(1) {
       th:nth-child(1) {
         background-color: @hoverColor !important;
       }
     }
   }

   .tdHover1(@n, (@i + 1));
 }

....
```

```tsx 
      <div
        className={`
        ${styles.page}
        ${valClassNames[`hover${Number(hoverObj?.col) + 1}`]}
        ${valClassNames[`rowHover${Number(hoverObj?.row) + 2}`]}
        `}
        onMouseLeave={() => this.setState({ hoverObj: {} })}
      >
        <CommonTable {...tableParams} ref={this.tableRef} />
      </div>
```

**Comment by eternallycyf** [comment]
## 已解决 
### 1. 通过 column onCell 属性 为每个 cell 设置数据存储 当前是第几行 当前是第几列 当前的值
```tsx 
onCell: (record,rowIndex) => {
   data-row: rowIndex,
   data-col: index * 5 +1,
   data-val: record[prefix+value],
}
```
### 2. render 增加鼠标hover事件 存储当前hover单元格信息
```tsx
render: (text, record) => {
  return (
    <div
      onMouseEnter={() => {
        const rowIndex = dict.find((item) => record?.name == item.text).row;
        const currentHoverObj = {
          prefix,
          col: index * 5 + ind + 1,
          row: rowIndex,
          val: record[prefix + value],
        };
        self.setState({ currentHoverObj });
        self.foreUpdate();
      }}
    >
      {text ?? '--'}
    </div>
  );
}; 
```
### 3. 动态控制样式
```tsx 
const { currentHoverObj:hoverObj } = this.state
<div
        className={`
        ${styles.page}
        ${valClassNames[`hover${Number(hoverObj?.col) + 1}`]}
        ${valClassNames[`rowHover${Number(hoverObj?.row) + 2}`]}
        `}
        onMouseLeave={() => this.setState({ hoverObj: {} })}
      >
        <CommonTable {...tableParams} ref={this.tableRef} />
      </div>
```
### 4. less 
```less 
 @hoverColor: #FFEFDB;
 @rowLength: 20;

 .tdHover1(@n, @i: 1) when (@i =< @n) {
   .ant-table-tbody tr:nth-child(@{i})>td:nth-child(1) {
     background-color: @hoverColor !important;
   }

   .ant-table-thead {
     tr:nth-child(1) {
       th:nth-child(1) {
         background-color: @hoverColor !important;
       }
     }
   }

   .tdHover1(@n, (@i + 1));
 }

.... to tdHover21

.rowHover1{
  :global {
    .ant-table-tbody tr:nth-child(1)>td {
      background-color: @hoverColor !important;
    }
  }
}

.... to rowHover21

.hover1 {
  :global {
    .tdHover1(!rowLength)
  }
}
... to hover21
```
