### DISCUSSION TITLE
使用class覆盖后的antd的样式后，怎么做主题适配

### DISCUSSION THREAD

**Discussion by chaoyue1217** [ant-design/ant-design#40929] [General]
表格样式要隔行变色，通过
```less
.ant-table {
  .ant-table-tbody > tr {
      &:nth-child(even) {
        background-color:  #F0F8FF;
      }
  }
}
```
覆盖样式实现之后，怎么去适配不同的主题色呢，比如亮色模式是颜色A，暗色模式是颜色B？
或者是我的方式不对？
