### DISCUSSION TITLE
[FR] Table 长文本 能支持换行显示,而不是...?

### DISCUSSION THREAD

**Discussion by vaynevayne** [ant-design/ant-design#42830] [Q&A] [answered]
https://github.com/ant-design/ant-design/issues/5753#issuecomment-452668949
貌似: 目前antd 只实现了 ellipsis, 并没有支持 textWrap: 'word-break', 
我理解对吗? 能考虑支持word-break吗?

**Comment by afc163** [comment]
是的。

**Comment by afc163** [comment]
word-break 可以直接给对应的 column 加 className 就可以了。

**Reply by vaynevayne** [reply]
好的, 假如给所有的加, 会有问题吗? 
比如这样
```css
.ant-table-wrapper .ant-table-tbody > tr > td {
  word-break: break-all;
}
```
