### DISCUSSION TITLE
Tabs 中 页签的高度能够自适应父容器嘛

### DISCUSSION THREAD

**Discussion by WakerCN** [ant-design/ant-design#47774] [Q&A]
`antd: ^5.13.3`

需求想让tabs下的页签撑满父容器
![image](https://github.com/ant-design/ant-design/assets/50485199/dad4b797-beef-4aa1-b434-1896ff735828)

```ts
  const items: TabsProps['items'] = [
    {
      key: 'widget',
      label: (
        <>
          <AppstoreOutlined style={{ marginInlineEnd: 6 }} />
          <span>组件</span>
        </>
      ),
      style: { background: 'pink', height: '100%' },
      children: (
        <div>
          <WidgetLibPane />
        </div>
      )
    },
    {
      key: 'layout',
      label: (
        <>
          <BarsOutlined style={{ marginInlineEnd: 6 }} />
          <span>图层</span>
        </>
      ),
      children: <div>图层</div>
    }
  ];
```

可以看到设置的高度，但是由于页签所在的元素外面还有两层dom元素，无法设置高度
![image](https://github.com/ant-design/ant-design/assets/50485199/1b51ef49-3800-46f9-a48d-b0a893d6ef1d)

请问有没有什么方法能使页签高度撑满父容器？

**Comment by 1zilc** [comment]
```css
.aito-fit-tabs {
  display: flex;
  flex-direction: column;

  .ant-tabs-content-holder {
    flex: 1;
    height: 0;
    position: relative;

    .ant-tabs-content {
      height: 100%;
    }
  }
}

```
