### DISCUSSION TITLE
[RFC] Mix usage with other CSS lib (like tailwind, styled-component, emotion)

### DISCUSSION THREAD

**Discussion by zombieJ** [ant-design/ant-design#47892] [RFCs]
# 📋 RFC

## Summary

StyleProvider support `@layer` for ordering priority with other css lib.

## Basic example

```tsx
<StyleProvider layer>
  <MyApp />
</StyleProvider>
```

Will export the style as:

```css
@layer antd {
  .css-bAmBoO.ant-btn {/** */}
  .css-bAmBoO.ant-checkbox {/** */}
}

@layer pro-components {
  .css-bAmBoO.ant-pro-layout {/** */}
}
```

```tsx
// Control of layer priority with deps
useStyleRegister({
  layer: {
    name: 'pro-components',
    deps: ['antd'],
  },
})

// `@layer antd, pro-component`
```

## Motivation

Ant Design use `@ant-design/cssinjs` lib to dynamic create the style on `<header />` which will always move itself at beginning of `<header />`.

In most case, this helps the customize style as same css selector to override the antd style. But it some time it can help less on the patch update. e.g.

```less
// Previews
:where(.css-lITtlE).ant-btn-primary {
  color: #000;
}
```

```less
// After: with some reason to enhance the css priority
:where(.css-lITtlE).ant-btn.ant-btn-primary {
  color: #000;
}
```

This will break user style:

```less
// Customize `src/global.css` to override antd style
.ant-btn { // Break since priority fail the battle
  color: red;
}
```

To keep the antd component style well work with customize style (or other css lib). It should support developer to make antd style order-able.

## Detailed

A well ordered style. For example, user use tailwind.css & antd & emotion. The css order should be:

1. tailwind: base
2. antd
3. tailwind: components
4. tailwind: utilities
5. customize style(less, emotion, styled-component, etc.)

### For the configuration of the basic steps (next.js example)

It just need take 2 steps:

#### 1. Wrap antd StyleProvider

Make antd has the `@layer` of `antd`.

```tsx
<StyleProvider layer>
  <MyApp />
</StyleProvider>
```

#### 2. Config global.css

Wrap `@tailwind base` in layer to make it as low priority. And order `antd` after `tailwind: base`.

```css
@layer tailwind-base {
  @tailwind base;
}
@tailwind components;
@tailwind utilities;

@layer tailwind-base, antd;
```

## Drawbacks

Need developer to config the `@layer` order.

## Adoption strategy

- Feature for `@ant-design/cssinjs` lib to support `hashPriority="low"`.
- antd side to config the `@layer` for `useStyleRegister` to make all the component has `@layer` info.
