### DISCUSSION TITLE
如何修改Checkbox的强调色accent-color？

### DISCUSSION THREAD

**Discussion by frontend-is-magic** [ant-design/ant-design#50008] [Q&A]
无法直接通过css修改Checkbox内部的input元素的accent-color解决

**Comment by frontend-is-magic** [comment]
```css
// index.less
@green: #52c41a;

.green-checkbox .ant-checkbox-checked .ant-checkbox-inner {
    background-color: @green;
    border-color: @green;
}

.green-checkbox:hover .ant-checkbox .ant-checkbox-inner {
    border-color: @green;
}

.green-checkbox:hover .ant-checkbox-checked .ant-checkbox-inner {
    background-color: lighten(@green, 10%) !important;
}
```
通过给Checkbox添加名为green-checkbox的类重新设置样式解决
