### DISCUSSION TITLE
Persistent Scrollbar in Virtual Table

### DISCUSSION THREAD

**Discussion by ek2061** [ant-design/ant-design#50583] [Q&A]
i am currently using the Table component with the virtual scroll feature. i would like to know if there is a way to make the scrollbar always visible, instead of only appearing when hovering over the table.

我目前正在使用具有虚拟滚动功能的 Table 組件。我想知道是否有一种方法可以使卷轴始终可见，而不是仅在将滑鼠悬停在表格上时才出现。

**Comment by anreikas** [comment]
You can use it.

```css
.ant-table-tbody-virtual-scrollbar {
    visibility: visible !important;
  }

**Reply by ek2061** [reply]
thanks for your reply, but it doesn't work after i use.
in the end i used this

```css
.rc-virtual-list-scrollbar-thumb {
  visibility: visible !important;
}
```
