### DISCUSSION TITLE
Badge

### DISCUSSION THREAD

**Discussion by mamun360ict** [ant-design/ant-design#51139] [Ideas]
I'm working with the Badge component in Ant Design and would like to increase the size of the dot. Currently, there doesn't seem to be a straightforward way to accomplish this. I believe it would be beneficial if Ant Design introduced additional size options for badges, such as 'medium' and 'large', to provide more flexibility in customizing the dot size.

**Comment by petercat-assistant** [comment]
It seems like you're looking for a way to customize the size of the dot in the Badge component of Ant Design. Currently, Ant Design does not provide built-in size options like 'medium' or 'large' for the Badge component. However, you can achieve this by applying custom styles.

Here's a simple way to increase the size of the dot using CSS:

```css
.ant-badge-dot {
  width: 10px; /* Adjust the width */
  height: 10px; /* Adjust the height */
}
```

You can add this CSS to your stylesheet to increase the size of the dot. Adjust the `width` and `height` values to your desired size.

If you believe that having built-in size options would be beneficial, you might consider suggesting this feature to the Ant Design team through their GitHub repository or discussions.

For further assistance, please describe your question in the comments and @petercat-assistant to start a conversation with me.

**Reply by mamun360ict** [reply]
.ant-badge-dot {
  width: 10px; /* Adjust the width */
  height: 10px; /* Adjust the height */
}

this code not working and I believe built-in size options would be beneficial for use .

**Comment by emanuelvidall** [comment]
try css .ant-badge .ant-badge-count together

```css
.ant-badge .ant-badge-count {
width: 50px;
height: 50px;
border-radius: 100px;
}
```
should work

check [https://stackblitz.com/edit/react-lu6cq3?file=demo.tsx](url)
