### DISCUSSION TITLE
I would know how to change the color of one occurence of a Switch component on a specific page

### DISCUSSION THREAD

**Discussion by Benoit-ROBIN** [ant-design/ant-design#51500] [Q&A] [answered]
Hello, 
as written in this topic title, I would know how to change the color of one occurence of a Switch component on a specific page. 
All the Switchs components on my app are blue, but on one page I need it orange. 
I don't understand what you have done with token and css variables. 
I'm used to work with material design, but I don't understand how Antd token and variable works.

I have tried several options, but none of theme seems to works

```scss

.formElementContainer {
  @extend .formElementContainer;
  flex-direction: row;
  justify-content: space-between;

  :root {
    --ant-5-color-primary: var(--ant-5-orange);
  }

  & > .ant5-switch {
    --ant-5-color-primary: var(--ant-5-orange);
    background: var(--ant-5-orange);
  }

  .ant5-switch-checked {
    background: var(--ant-5-orange);
    --ant-5-color-primary: var(--ant-5-orange);
  }
}

```
