### DISCUSSION TITLE
DatePicker multiple选择了多个日期之后怎么改它显示的样式？

### DISCUSSION THREAD

**Discussion by hexiaochen666** [ant-design/ant-design#51677] [General]
### Reproduction link

[https://ant-design.antgroup.com/components/date-picker-cn](https://ant-design.antgroup.com/components/date-picker-cn)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/391e6b49-c24f-4ad0-922b-ace40c6f91f7)

### What is expected?

可以想类似饿了么ui这样吗？
![image](https://github.com/user-attachments/assets/90195871-dfe0-424a-88de-9fa65deed7a6)

### What is actually happening?

展示问题

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18 |
| System | win10 |
| Browser | 谷歌 |

**Comment by petercat-assistant** [comment]
要修改 Ant Design 的 `DatePicker` 组件在选择多个日期后的显示样式，你可以通过自定义样式来实现。以下是一些步骤和示例代码，帮助你实现类似于饿了么 UI 的样式：

1. **覆盖默认样式**：你可以通过 CSS 覆盖 Ant Design 的默认样式。找到 `DatePicker` 组件的类名，然后在你的样式文件中进行覆盖。

2. **使用 `className` 属性**：在 `DatePicker` 组件中使用 `className` 属性，添加自定义的类名，然后在 CSS 中定义该类名的样式。

3. **自定义渲染**：如果需要更复杂的样式，可以使用 `DatePicker` 的 `renderExtraFooter` 或其他自定义渲染方法来插入自定义的 HTML 和样式。

以下是一个简单的示例代码：

```jsx
import React from 'react';
import { DatePicker } from 'antd';
import 'antd/dist/antd.css';
import './customDatePicker.css'; // 引入自定义样式文件

const CustomDatePicker = () => {
  return (
    <DatePicker
      className="custom-date-picker"
      mode="multiple"
      onChange={(dates) => console.log(dates)}
    />
  );
};

export default CustomDatePicker;
```

在 `customDatePicker.css` 文件中：

```css
.custom-date-picker .ant-picker-cell-selected .ant-picker-cell-inner {
  background-color: #f0f0f0; /* 自定义背景色 */
  color: #ff4d4f; /* 自定义字体颜色 */
  border-radius: 4px; /* 自定义圆角 */
}

/* 添加更多自定义样式 */
```

通过这种方式，你可以根据自己的需求调整 `DatePicker` 的样式。如果需要更复杂的样式调整，可能需要深入了解 Ant Design 的样式结构，并根据需要进行调整。

如果你有更多问题或需要进一步的帮助，请在评论中描述你的问题，并 @petercat-assistant 来开始与我对话。

**Comment by petercat-assistant** [comment]
要在 Ant Design 的 `DatePicker` 组件中自定义多个日期选择后的显示样式，您可以通过自定义样式和覆盖默认的 CSS 类来实现。以下是一些步骤和示例代码，帮助您实现类似饿了么 UI 的效果：

1. **覆盖默认样式**：您可以通过 CSS 覆盖 Ant Design 的默认样式。首先，您需要找到 `DatePicker` 组件渲染的 DOM 结构，然后根据需要覆盖相应的类。

2. **使用 `className` 和 `style` 属性**：在 `DatePicker` 组件上使用 `className` 或 `style` 属性来应用自定义样式。

3. **自定义渲染函数**：如果需要更复杂的自定义，您可以使用 `DatePicker` 的 `renderExtraFooter` 或其他自定义渲染函数来插入额外的内容或样式。

下面是一个简单的示例代码，展示如何覆盖样式：

```jsx
import React from 'react';
import { DatePicker } from 'antd';
import 'antd/dist/antd.css'; // 引入 Ant Design 样式

const { RangePicker } = DatePicker;

const CustomDatePicker = () => {
  return (
    <RangePicker
      className="custom-date-picker"
      style={{ borderColor: 'red', borderWidth: 2 }} // 自定义样式
    />
  );
};

export default CustomDatePicker;
```

在 CSS 文件中，您可以添加自定义样式：

```css
.custom-date-picker .ant-picker-input {
  background-color: #f0f0f0; /* 自定义背景色 */
  border-radius: 8px; /* 自定义圆角 */
}

.custom-date-picker .ant-picker-cell-selected .ant-picker-cell-inner {
  background-color: #ff4d4f; /* 自定义选中日期的背景色 */
  color: white; /* 自定义选中日期的文字颜色 */
}
```

通过这些步骤，您可以根据需要调整 `DatePicker` 的样式以实现类似饿了么 UI 的效果。

如果您有更多问题或需要进一步的帮助，请在评论中描述您的问题并 @petercat-assistant 开始与我对话。
