### DISCUSSION TITLE
Add Navigation Mode to rc-menu

### DISCUSSION THREAD

**Discussion by Zyf665** [ant-design/ant-design#52679] [RFCs]
# Add Navigation Mode to rc-menu

## Summary

Add a new `navigation` mode to rc-menu to support modern website navigation patterns, providing a more content-rich and user-friendly navigation experience.

## Background

Current rc-menu supports three modes: horizontal, vertical, and inline. However, modern websites often require a more sophisticated navigation pattern that can display rich content in dropdown menus.

## Motivation

- Support modern website navigation patterns
- Provide better content organization in navigation menus

### API Changes

```typescript
// Add new mode type
type MenuMode = "vertical" | "horizontal" | "inline" | "navigation";
// Menu props remain unchanged
interface MenuProps {
  mode?: MenuMode;
  // ... existing props
}
```

#### Navigation Mode Specific Features:

- Single-level dropdown only (no nested submenus)
- Rich content support in dropdown
- Card-style popup design
- Grid layout for content organization

#### Example Usage:

```tsx
<Menu mode="navigation">
  <MenuItem>Home</MenuItem>
  <SubMenu title="Features">
    <div className="navigation-content">
      <MenuItem>
        <a href="/docs" className="menu-item-content">
          <h3>Getting Started</h3>
          <p>Quick start guide and learn the basics of our components.</p>
        </a>
      </MenuItem>
    </div>
  </SubMenu>
</Menu>
```

### **Event Handling in Navigation Mode**

In navigation mode, MenuItem needs to handle both link navigation and click events simultaneously.

```typescript
// Key implementation only
const handleClick = (e: React.MouseEvent) => {
  if (isAnchorElement && !isSpecialClick) {
    // Keep default link behavior
    return;
  }
  // Handle other click scenarios
};
```

### Style Changes

New styles will be added for navigation mode:

```less
.rc-menu-navigation {
  // Remove default borders
  border: none;
  // Popup styles
  .rc-menu-submenu-popup {
    padding: 16px;
    border-radius: 8px;
    box-shadow: 0 10px 38px -10px rgba(22, 23, 24, 0.35);
    min-width: 480px;
  }
  // Content styles
  .navigation-content {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 16px;
  }
  // MenuItem styles
  .rc-menu-item {
    padding: 0;
    a {
      display: block;
      padding: 16px;
      text-decoration: none;
      color: inherit;
      h3 {
        margin-bottom: 8px;
        font-size: 16px;
        font-weight: 500;
      }
      p {
        color: rgba(0, 0, 0, 0.45);
        font-size: 14px;
        line-height: 1.5;
      }
      &:hover {
        background: rgba(0, 0, 0, 0.03);
      }
    }
  }
}
```
