### DISCUSSION TITLE
如何取消Tabs创建时边框样式问题

### DISCUSSION THREAD

**Discussion by NP-1210** [ant-design/ant-design#53665] [General]
![image](https://github.com/user-attachments/assets/704c76fe-7f48-4c1a-a32d-443aae05fb91)

**Comment by petercat-assistant** [comment]
要取消 Ant Design Tabs 组件在创建时的边框样式，您可以通过自定义 CSS 来覆盖默认样式。以下是一个简单的示例，说明如何通过 CSS 来去除 Tabs 的边框：

```css
/* 覆盖 Ant Design Tabs 的边框样式 */
.ant-tabs {
  border: none; /* 去除 Tabs 容器的边框 */
}

.ant-tabs-tab {
  border: none; /* 去除每个 Tab 的边框 */
}
```

您可以将上述 CSS 添加到您的项目中，以覆盖默认的 Tabs 样式。如果您使用的是 CSS-in-JS 解决方案（如 styled-components 或 emotion），也可以使用相应的方法来应用这些样式。

请确保这些样式在 Ant Design 的默认样式之后加载，以确保覆盖生效。

如果您有更多问题或需要进一步的帮助，请随时告诉我！

<details>
<summary>🪧 Tips</summary>
For further assistance, please describe your question in the comments and @petercat-assistant to start a conversation with me.
</details>
