### ISSUE TITLE
body 撑满内容时候 message 不显示

### ISSUE THREAD

**Issue by SummerWish** [ant-design/ant-design#1053]
例如:

```css
body { width: 100%; height: 100%; display: flex; }
```

```html
<body>
<div style="flex: 1"></div>
</body>
```

则 message 的 div 会被挤掉最右边去。
需要为 `.ant-message` 加上 `left: 0`
