### ISSUE TITLE
关于treeSelect 父节点设置disabled的问题

### ISSUE THREAD

**Issue by ybning** [ant-design/ant-design#11013]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://codesandbox.io/s/53m7ll8p2k

#### 有这样一个需求场景：
选择车型，父节点是车品牌的首字母: A,B,C,D，子节点是车的品牌: 奥迪,奔驰,长安,大众，父节点这一层是不可选，只可展开。
![a](https://user-images.githubusercontent.com/3725612/41815834-a9302b78-77a8-11e8-976b-e52a75334f3a.png)
![b](https://user-images.githubusercontent.com/3725612/41815836-b3a7f680-77a8-11e8-98f5-9571b6c02315.png)
![c](https://user-images.githubusercontent.com/3725612/41815889-0bd2eb5c-77aa-11e8-9baa-0ea9aeb8d589.png)

为了实现这个需求，仅用到了disabled
但是，现在设置disabled后，鼠标移上去显示“禁止”的鼠标图标，第一感觉是不可操作的，实际点击前面的符号，是可以展开的。

### What does the proposed API look like?
希望是鼠标移上去显示鼠标原有“箭头”图标。

**Comment by ybning** [comment]
Cascader级联选择
> loadData 与 showSearch 无法一起使用。

@tsejx

**Comment by ybning** [comment]
我尝试用了Cascader，那么问题来了 #11037 
@tsejx

**Comment by yutingzhao1991** [comment]
需求看上去似乎是合理的，但是 disable 的情况下禁用选择也是对的。组件不太好直接修改这里的样式。你可以尝试覆盖掉默认样式： https://codesandbox.io/s/rl3v8wzr1o。

或者其实 TreeSelect 应该添加类似 `branchNode` 之类的属性来替代 `disable`。

**Comment by zombieJ** [comment]
tree-select 在重构，之后应该可以用 `selectable: false` 和 `onClick` 组合出来这个效果。

**Comment by ybning** [comment]
@zombieJ  It's great.

**Comment by iwestlin** [comment]
明天就是9月份了，不知道这功能官方实现了没有啊……

我翻了半天文档和issue没找到解决方案，最后只好强行用css扩大了左边箭头的点击范围，使得点击箭头右边的文字就相当于点在了箭头上……贴出代码来也许有人用得上。。
```css
.ant-select-tree-switcher {
  position: relative;
}
.ant-select-tree-switcher_open::before, .ant-select-tree-switcher_close::before {
  content: '';
  position: absolute;
  right: -190px;
  top: 0;
  left: 0;
  bottom: 0;
}
```

**Comment by zlab** [comment]
@iwestlin 
`treenode.selectable=false`

**Comment by iwestlin** [comment]
@zlab 你没get到楼主和我的点啊，目的不单是让父级节点不可选，而且要让它被点击的时候展开它的子级（也就是点击它左侧箭头的效果），目前我没找到css以外的解决方法……

**Comment by woo123123** [comment]
> @zlab 你没get到楼主和我的点啊，目的不单是让父级节点不可选，而且要让它被点击的时候展开它的子级（也就是点击它左侧箭头的效果），目前我没找到css以外的解决方法……

请问我使用ant design vue 有没有任何影响?我直接添加在文件内并没有产生任何效果. 应该如何添加?谢谢

**Comment by khanh19934** [comment]
> 明天就是9月份了，不知道这功能官方实现了没有啊……
> 
> 我翻了半天文档和issue没找到解决方案，最后只好强行用css扩大了左边箭头的点击范围，使得点击箭头右边的文字就相当于点在了箭头上……贴出代码来也许有人用得上。。
> 
> ```css
> .ant-select-tree-switcher {
>   position: relative;
> }
> .ant-select-tree-switcher_open::before, .ant-select-tree-switcher_close::before {
>   content: '';
>   position: absolute;
>   right: -190px;
>   top: 0;
>   left: 0;
>   bottom: 0;
> }
> ```

this is the worked solution . Any people have the right solution using js or from original document ?

**Comment by zlyyyy** [comment]
请问现在4.0是否有这个问题的配置 @zombieJ

**Comment by RicherDove** [comment]
可以在change，方法中调用方法，对当前选中进行回调判断，清除父类选中

**Comment by MaZhengA** [comment]
如果是父节点，直接设置selectable属性为false即可

**Comment by Gokakakan** [comment]
@iwestlin 感谢老哥的方案，给我们提供了很好的思路，我和同事做了一下改动，相对TreeNode做定位，可以适配任意宽度，点击选项任意位置都可以触发点击事件。
`.ant-select-tree-treenode{
    position: relative;
}
.ant-select-tree-switcher {
    position: static;
}
.ant-select-tree-switcher_open::before, .ant-select-tree-switcher_close::before {
    content: '';
    position: absolute;
    right: 0;
    top: 0;
    left: 0;
    bottom: 0;
    z-index: 9999;
}`

**Comment by Gokakakan** [comment]
> 明天就是9月份了，不知道这功能官方实现了没有啊……
> 
> 我翻了半天文档和issue没找到解决方案，最后只好强行用css扩大了左边箭头的点击范围，使得点击箭头右边的文字就相当于点在了箭头上……贴出代码来也许有人用得上。。
> 
> ```css
> .ant-select-tree-switcher {
>   position: relative;
> }
> .ant-select-tree-switcher_open::before, .ant-select-tree-switcher_close::before {
>   content: '';
>   position: absolute;
>   right: -190px;
>   top: 0;
>   left: 0;
>   bottom: 0;
> }
> ``` 
@iwestlin 感谢老哥的方案，给我们提供了很好的思路，我和同事做了一下改动，相对TreeNode做定位，可以适配任意宽度，点击选项任意位置都可以触发点击事件。
```css
.ant-select-tree-treenode{
    position: relative;
}
.ant-select-tree-switcher {
    position: static;
}
.ant-select-tree-switcher_open::before, .ant-select-tree-switcher_close::before {
    content: '';
    position: absolute;
    right: 0;
    top: 0;
    left: 0;
    bottom: 0;
    z-index: 9999;
}
```

**Comment by Gokakakan** [comment]
@iwestlin 感谢老哥的方案，给我们提供了很好的思路，我和同事做了一下改动，相对TreeNode做定位，可以适配任意宽度，点击选项任意位置都可以触发点击事件。

```css
.ant-select-tree-treenode{
    position: relative;
}
.ant-select-tree-switcher {
    position: static;
}
.ant-select-tree-switcher_open::before, .ant-select-tree-switcher_close::before {
    content: '';
    position: absolute;
    right: 0;
    top: 0;
    left: 0;
    bottom: 0;
    z-index: 9999;
}
```
