### ISSUE TITLE
notification这个组件智能修改top不能修改right吗 ,我看源代码里面都写死了

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#1166]

**Comment by afc163** [comment]
```css
.ant-notification {
  margin-right: 100px;
}
```

可通过样式覆盖。
