### ISSUE TITLE
Responsive columns for table component

### ISSUE THREAD

**Issue by marekgregor** [ant-design/ant-design#11817]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Antd table component does not support "responsive column hiding" out of the box. It means columns without space wrapping ("white-space: nowrap"), which have not enough space to render without horizonal scrollbar, should be automatically hidden in expandable row.
Similar functionality is already present in Datatables component (https://datatables.net/), which hides columns based on priority attribute in column definition.

I have implemented naive implementation of this functionality in https://codesandbox.io/s/k2qjo5j67v

### What does the proposed API look like?
API for Column definiton:
  - add property "responsivePriority" (number, default: undefined) - to notify that this column could be hidden when there is no space. Columns will be hidden in descendant order of this value (bigger number - first). User have to define CSS "white-space: nowrap" manually for cells of reponsive columns (either globally for table or for row/column/cell).

When at least one column has "responsivePriority" property set, default implementation expandedRowRender() function will show hidden columns in expandable part similar as in https://codesandbox.io/s/k2qjo5j67v . Developer could overridde expandedRowRender property with function which will receive list of currently hidden columns as one of its parameters (fifth?) of this function.

Probably whole functionality could be implemented as an extension (addon?) a not in the core API. (but I don't know how to do it correctly). It has to be decided ...

**Comment by afc163** [comment]
That was implemented already before: https://github.com/ant-design/ant-design/commit/bd9fba9f456e3be7a9e367f62a0e35abdc1bfe1f However it was reverted casue #8465

**Comment by devharf2310** [comment]
I'm wondering if there are other solution for responsive table, because I've seen https://github.com/ant-design/ant-design/commit/bd9fba9f456e3be7a9e367f62a0e35abdc1bfe1f, but I couldn't understand. Thanks

**Comment by afc163** [comment]
You can implement it by your own.

ref https://github.com/ant-design/ant-design/issues/12301

**Comment by bodfaj13** [comment]
.ant-table-thead > tr > th,
.ant-table-tbody > tr > td {
  /* padding: 16px 16px; */
  word-break: break-word;
  -ms-word-break: break-all;
}
@media (min-width: 768px) { 
  .ant-table-thead > tr > th,
  .ant-table-tbody > tr > td {
    padding: 16px 16px;
  }
}

**Comment by matirasa** [comment]
im using this trick
https://www.codeproject.com/Tips/820099/Responsive-HTML-Tables-using-CSS-LESS

it works for me

**Comment by matirasa** [comment]
i'm using this trick
https://www.codeproject.com/Tips/820099/Responsive-HTML-Tables-using-CSS-LESS

**Comment by nguyen-coding-c** [comment]
How to implement responsive for Antd Table?

**Comment by taniarascia** [comment]
For anyone who comes along this, you can implement something similar to https://github.com/ant-design/ant-design/commit/bd9fba9f456e3be7a9e367f62a0e35abdc1bfe1f to make the table acceptable on mobile. Here's some code that will work with LESS/SCSS.

```scss
.ant-table {
  display: block;

  @media screen and (max-width: 600px) {
    &-thead {
      display: none;
    }

    &-thead>tr,
    &-tbody>tr {

      th,
      td {
        &:first-of-type {
          padding-top: 1rem;
        }

        &:last-of-type {
          padding-bottom: 1rem;
        }
      }

      >th,
      >td {
        display: block;
        width: auto !important;
        border: none;
        padding: 0 1rem;
        font-size: 1.1rem;

        &:last-child {
          border-bottom: 1px solid #eee;
        }
      }
    }
  }
}
```

It would be nice to get the table headings in the `:before` of each cell, like Bootstrap.
