### ISSUE TITLE
how to change the margin between Menu and subMenu

### ISSUE THREAD

**Issue by oNexiaoyao** [ant-design/ant-design#11963]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to change the margin between Menu and subMenu

### What does the proposed API look like?
write style to change the margin

**Comment by oNexiaoyao** [comment]
![tim 20180830093841](https://user-images.githubusercontent.com/17607868/44824503-8e478d00-ac38-11e8-9f87-c1d47bfc78ff.png)

**Comment by hongxuWei** [comment]
antd 底下用的 rc-menu 实现的这个组件，目前我源码没看到有提供这个接口。
你可以这么试一下

```CSS
.ant-menu-submenu-popup {
    margin-top: -10px;
}
```

如果只想修改部分地方的你可以在 JSX 的 SubMenu 里面加上你自己定义的 className，然后这么用
```CSS
.your-class-name.ant-menu-submenu-popup {
    margin-top: -10px;
}
```
