### ISSUE TITLE
Since the 3.9s, Icon's customizability has become lower and lower

### ISSUE THREAD

**Issue by Hughen** [ant-design/ant-design#12236]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Before 3.9, I can directly modify the default icon style with my custom style without changing the framework code, but I can no longer use it after 3.9, for example:
```css
/* <= 3.8.x */
.my-custom-class .ant-select-selection__rendered > ul {
    padding-right: 10px;
}
.my-custom-class .ant-select-selection__rendered::before {
    display: inline-block;
    -webkit-animation: loadingCircle 1s infinite linear;
    animation: loadingCircle 1s infinite linear;
    content: "\E64D";
    color: #1890ff;
    position: absolute;
    pointer-events: none;
    width: 20px;
    height: 20px;
    text-align: center;
    font-size: 14px;
    font-family: anticon;
    visibility: visible;
    /* and xxx... */
}
```
The function that this style wants to achieve is to add a loading animation to the right of the Select component without destroying the original framework code, but after 3.9 I want to implement this function, there is no idea at all.
You might tell me to use `content: url(loading.svg)`, but the defect is that there is no custom svg color.

Throughout the industry's usage, such as `fontawesome`, they provide both font-family and svg forms.
**Obviously they have more practical experience.**

### What does the proposed API look like?
The Icon component either provides two ways of using (svg children and pseudo-element content font-family), or gives up using svg.
Just like this:
```javascript
// font-family
<Icon.Font type="loading" />

// svg
<Icon.Svg type="loading" />
```
For `ant-design` code, Icon.Font is used by default.
