### ISSUE TITLE
Form.Item组件下智能提示Select组件验证不通过时获取焦点样式显示错误

### ISSUE THREAD

**Issue by vicerwang** [ant-design/ant-design#1227]
## What you did

``` xml
<FormItem {...formItemLayout}
  label="关联PD"
  validateStatus={this.state.pdStatus}
  help={this.state.pdHelp}>
  <Select combobox
    style={{ width: '374px' }}
    filterOption={false}
    placeholder="请关联此需求相关同学"
    onChange={::this.handlePDInput}
    onSelect={::this.handlePDSelect}>
    {this.state.pds.map(pd => <Option key={pd.fullName}>{pd.fullName}</Option>)}
  </Select>
</FormItem>
```
表单项组件`FormItem`下包含可智能提示的下拉组件`Select`，如果验证不通过，即validateStatus值为error时，此时`Select`组件边框为红色，但是再次点击`Select`组件时，边框变为获取焦点时的@primary-color颜色，查看css发现，此时为`input.ant-select-search__field`添加了样式

``` css
.ant-select-combobox .ant-select-search__field:focus {
    box-shadow: 0 0 0 1px #597eee, 0 0 0 3px #d6dffb;
}
```

覆盖了显示红色的`span.has-error.ant-select-selection`的样式

``` css
.has-error .ant-select-selection {
    border-color: #f50;
    box-shadow: 0 0 0 2px #ffddcc;
}
```

其他`Input`以及`DatePicker`组件在`Form.Item`下验证都无此问题

目前使用下面代码hack

``` css
.ant-form-item-control.has-error .ant-select-combobox .ant-select-search__field:focus {
  box-shadow: none;
}
```

## What you would like to happen

边框依然显示红色

## What actually happened

边框依然显示蓝色

## Online demo

无，内部系统开发中。

## Environment Information

- The version of antd(e.g. 0.12.0): 0.12.10
- Your operating system and it's version(e.g. OSX 10.11.0): 10.10.4
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)): 49.0.2623.87 (64-bit)
