### ISSUE TITLE
[Table] Header overlap with sorter when long text

### ISSUE THREAD

**Issue by HsuanXyz** [ant-design/ant-design#12650]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
*

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nw63yxz3rl)

### Steps to reproduce
Open reproduction link

### What is expected?
Not overlap

### What is actually happening?
Overlap

---
hack

```css
.ant-table-column-has-filters.ant-table-column-has-sorters > .ant-table-column-sorters {
  margin-right: 30px
}
```
