### ISSUE TITLE
css3动画开关需求

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design#1277]
某些环境下css3动画会异常，会导致class=""内的样式空格丢失，界面异常显示。

所以能否增加一个指定元素css动画的开关，以解决此问题（目前我已经改源码实现）。

**Comment by benjycui** [comment]
增加一条 CSS 规则如何？大概如下：

```css
.disable-animation {
  transition: none;
}
```
