### ISSUE TITLE
Grid 栅格 为什么没有响应式工具类?

### ISSUE THREAD

**Issue by xujunzhou** [ant-design/ant-design#13043]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### 既然有响应式栅格(xs, sm, md, lg, xl, xxl), 为什么没有响应式工具类?   

Bootstrap工具类:  
* visible-<xs | sm | md | lg | xl | xxl>-<block | inline | inline-block> 在匹配的设备下可见  
* hidden-<xs | sm | md | lg | xl | xxl> 在匹配的设备下隐藏  

示例:
* ```<div class="visible-xs-block">仅在移动端显示</div>  ```
* ```<div class="hidden-lg">仅在PC端隐藏</div>  ```

### What does the proposed API look like?
# 这些功能很有用, 期待!

**Comment by xujunzhou** [comment]
如果想要在某种设备类型下显示或隐藏某一个元素, 那么在ant-design中如何实现?

**Comment by afc163** [comment]
@xujunzhou 可以参考 https://ant.design/components/grid-cn/#components-grid-demo-responsive 或使用 https://github.com/contra/react-responsive

**Comment by xujunzhou** [comment]
我用的是 Angular + ng.ant.design.
增加以下样式就可以愉快的玩耍了:
> SCSS
```scss
$breakpoints: (
  xs: (min: null, max: 575px),
  sm: (min: 576px, max: 767px),
  md: (min: 768px, max: 991px),
  lg: (min: 992px, max: 1199px),
  xl: (min: 1200px, max: 1799px),
  xxl: (min: 1600px, max: null),
);

$displays: block, inline, inline-block;

@mixin _content($breakpoint) {
  //在特定设备显示
  @each $displayType in $displays {
    .visible-#{$breakpoint}-#{$displayType} {
      display: $displayType;
    }
  }
  
  //在特定设备隐藏
  .hidden-#{$breakpoint} {
    display: none;
  }
}

@each $breakpoint, $breakpointMap in $breakpoints {
  @each $displayType in $displays {
    .visible-#{$breakpoint}-#{$displayType} {
      display: none;
    }
  }
  $min: map-get($breakpointMap, 'min');
  $max: map-get($breakpointMap, 'max');
  @if $min == null {
    @media (max-width: $max) {
      @include _content($breakpoint);
    }
  } @else if $max == null {
    @media (min-width: $min) {
      @include _content($breakpoint);
    }
  } @else {
    @media (min-width: $min) and (max-width: $max) {
      @include _content($breakpoint);
    }
  }
}
```

> 输出 CSS
```css
.visible-xs-block {
  display: none;
}

.visible-xs-inline {
  display: none;
}

.visible-xs-inline-block {
  display: none;
}

@media (max-width: 575px) {
  .visible-xs-block {
    display: block;
  }

  .visible-xs-inline {
    display: inline;
  }

  .visible-xs-inline-block {
    display: inline-block;
  }

  .hidden-xs {
    display: none;
  }
}
.visible-sm-block {
  display: none;
}

.visible-sm-inline {
  display: none;
}

.visible-sm-inline-block {
  display: none;
}

@media (min-width: 576px) and (max-width: 767px) {
  .visible-sm-block {
    display: block;
  }

  .visible-sm-inline {
    display: inline;
  }

  .visible-sm-inline-block {
    display: inline-block;
  }

  .hidden-sm {
    display: none;
  }
}
.visible-md-block {
  display: none;
}

.visible-md-inline {
  display: none;
}

.visible-md-inline-block {
  display: none;
}

@media (min-width: 768px) and (max-width: 991px) {
  .visible-md-block {
    display: block;
  }

  .visible-md-inline {
    display: inline;
  }

  .visible-md-inline-block {
    display: inline-block;
  }

  .hidden-md {
    display: none;
  }
}
.visible-lg-block {
  display: none;
}

.visible-lg-inline {
  display: none;
}

.visible-lg-inline-block {
  display: none;
}

@media (min-width: 992px) and (max-width: 1199px) {
  .visible-lg-block {
    display: block;
  }

  .visible-lg-inline {
    display: inline;
  }

  .visible-lg-inline-block {
    display: inline-block;
  }

  .hidden-lg {
    display: none;
  }
}
.visible-xl-block {
  display: none;
}

.visible-xl-inline {
  display: none;
}

.visible-xl-inline-block {
  display: none;
}

@media (min-width: 1200px) and (max-width: 1799px) {
  .visible-xl-block {
    display: block;
  }

  .visible-xl-inline {
    display: inline;
  }

  .visible-xl-inline-block {
    display: inline-block;
  }

  .hidden-xl {
    display: none;
  }
}
.visible-xxl-block {
  display: none;
}

.visible-xxl-inline {
  display: none;
}

.visible-xxl-inline-block {
  display: none;
}

@media (min-width: 1600px) {
  .visible-xxl-block {
    display: block;
  }

  .visible-xxl-inline {
    display: inline;
  }

  .visible-xxl-inline-block {
    display: inline-block;
  }

  .hidden-xxl {
    display: none;
  }
}
```
