### ISSUE TITLE
antd 设置了 * box-sizing: border-box;  之后，岂不是所有的原始都修改了这个属性？这样做的出发点是？

### ISSUE THREAD

**Issue by NicholasNC** [ant-design/ant-design#13169]
```css
*,
*::before,
*::after {
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
}
```

antd 有上述设置，但是这样做，一旦引用了 antd，那么整个应用都将 `box-sizing` 从默认的 `content-box` 改成 `border-box`，感觉这样不大好，想知道出发点如何？

如果说 UI 框架尽可能不影响调用的程序的话，这样做感觉不大合理

另外，翻查了一下，Ant Design Mobile 则没有这样的设计，感觉这样不统一更加大了对这个属性修改的疑惑
