### ISSUE TITLE
紧凑表格，样式有些问题

### ISSUE THREAD

**Issue by blade254353074** [ant-design/ant-design#1342]
![image](https://cloud.githubusercontent.com/assets/9346008/14315681/80b25328-fc31-11e5-949e-93b6466e7dd9.png)

```css
/* small table 表头圆角 */
.ant-table-small table {
  border-radius: 6px 6px 0 0;
}
```
