### ISSUE TITLE
Table 使用useFixedHeader后Table高度无法自定义

### ISSUE THREAD

**Issue by Sunzhuoyi** [ant-design/ant-design#1425]
**问题描述**
Table 使用useFixedHeader后Table高度无法自定义,自己重写样式.ant-table-body后项目内所有使用表格的地方，表格的高度都会发生改变

**发生环境**

- antd 版本：^0.12.10
- 操作系统及版本：mac pro
- 浏览器及版本：
- 在线演示地址：

**重现步骤**

1. ...
2. ...

**线上重现演示**

http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by afc163** [comment]
你给了一个没有重现的重现演示。

**Comment by afc163** [comment]
你外面加一个 className 。样式定义为

```css
.your-class-name .ant-table-body {
   height: 1000px;
}
```

或者用 `bodyStyle={{ height: 1000 }}`
