### ISSUE TITLE
Menu.Item与React router Link的兼容性问题

### ISSUE THREAD

**Issue by nie-xin** [ant-design/ant-design#1432]
**问题描述**

在Menu.Item中嵌入如下Link：

```javascript
        <Menu.Item key="mandate">
          <Link to="/dashboard/orders">
            Orders
          </Link>
        </Menu.Item>
```

当hover至该Item时，会触发一个warning：

Warning: ReactDOMComponent: Do not access .props of a DOM node; instead, recreate the props as `render` did originally or read the DOM properties/attributes directly from this node (e.g., this.refs.box.className). This DOM node was rendered by `Menu`.

**发生环境**

- antd 版本：0.12.13
- 操作系统及版本：Mac os
- 浏览器及版本：Chrome  49.0.2623.110 (64-bit)

**Comment by panzt** [comment]
我也遇到了，我的解决办法是判断key，然后直接location

**Comment by benjycui** [comment]
antd 官网中这样用没问题，麻烦提供可重现 demo http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by EdenLiang** [comment]
<Menu mode="inline" theme="dark">
      <Menu.Item><Link to="/">主页</Link></Menu.Item>
</Menu>
这样是没问题，可以渲染，然而Link生成的a没有占据memu生成的li整行

**Comment by benjycui** [comment]
> 然而Link生成的a没有占据memu生成的li整行

这个设置 `a` `display: block` 就可以了。

**Comment by EdenLiang** [comment]
不行，menu生成的li上有padding-left:48px;
所以加一个block，然并卵

**Comment by afc163** [comment]
```css
.ant-menu-item > a:before {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: transparent;
  content: '';
}
```

目前只能用这种奇技淫巧..
