### ISSUE TITLE
Can not Custom Tree showLine Icon(在 Tree 组件中使用 showLine 属性，无法自定义图标)

### ISSUE THREAD

**Issue by nbhaohao** [ant-design/ant-design#14562]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

## Duplicate issues
I searched [#3854](https://github.com/ant-design/ant-design/issues/3854), and read the Demo [Pull#5261](https://github.com/ant-design/ant-design/pull/5261), but the demo is not use SVG Icon, So I think this demo can't solve this problem in the newest ant-design.

我搜索了 [#3854](https://github.com/ant-design/ant-design/issues/3854), 阅读了其中提到的解决 Demo [Pull#5261](https://github.com/ant-design/ant-design/pull/5261), 但是那个例子中，ant-design 的 Icon 还没有使用 SVG, 所以我觉得那个例子在新的 ant-design 版本中，不能解决这个问题

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8k86qm4n20)

### Steps to reproduce
use <Tree> Component, and use `showLine: true`, 

在 <Tree /> 组件中使用 `showLine` 属性

``` js
<Tree
  showLine
   ....
>
```

### What is expected?
provide API to custom the line icon 

提供可以自定义图标的 API

![screenshot](https://i.loli.net/2019/01/26/5c4bca00ac8fe.png)

### What is actually happening?
can't modify the default icon.

无法修改默认的图标

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.0 |
| System | macOS Mojave 10.14.1 |
| Browser | Google Chrome(71.0.3578.98) |

---
由于生成的图标是 svg 格式的，尝试过使用类似这种 CSS 代码进行样式覆盖，只能在 Chrome 生效，因为其他浏览器并不支持。

The generated icon is SVG, I try to use style overrides like this CSS code, But is only valid in Chrome ,because it is not supported by other browsers.
``` css
.anticon-file {
  svg path {
    d: path('M858.5 763.6a374 374 0 0 0-80.6-119.5 375.63 375.63 0 0 0-119.5-80.6c-.4-.2-.8-.3-1.2-.5C719.5 518 760 444.7 760 362c0-137-111-248-248-248S264 225 264 362c0 82.7 40.5 156 102.8 201.1-.4.2-.8.3-1.2.5-44.8 18.9-85 46-119.5 80.6a375.63 375.63 0 0 0-80.6 119.5A371.7 371.7 0 0 0 136 901.8a8 8 0 0 0 8 8.2h60c4.4 0 7.9-3.5 8-7.8 2-77.2 33-149.5 87.8-204.3 56.7-56.7 132-87.9 212.2-87.9s155.5 31.2 212.2 87.9C779 752.7 810 825 812 902.2c.1 4.4 3.6 7.8 8 7.8h60a8 8 0 0 0 8-8.2c-1-47.8-10.9-94.3-29.5-138.2zM512 534c-45.9 0-89.1-17.9-121.6-50.4S340 407.9 340 362c0-45.9 17.9-89.1 50.4-121.6S466.1 190 512 190s89.1 17.9 121.6 50.4S684 316.1 684 362c0 45.9-17.9 89.1-50.4 121.6S557.9 534 512 534z') !important;
  }
}
```
