### ISSUE TITLE
带样式的 RadioGroup 在 IE8 下点击无效

### ISSUE THREAD

**Issue by wxt2005** [ant-design/ant-design#1459]
官网 Radio demo 页面可重现 : http://ant.design/components/radio/
看了下样式文件，应该是 `ant-radio-button` 这个 `span` 设置了 `display: none` 造成的，我尝试了一下修改为以下样式可以修正问题：
```css
label.ant-radio-button > span.ant-radio-button {
    margin-left: 0;
    width: 0;
    height: 0;
    display: block;
}
```
