### ISSUE TITLE
Table 表格头有排序以及 Resizable 时，拖拽缩放时 mouseup 将会触发 cell 的 sort 

### ISSUE THREAD

**Issue by KentonYu** [ant-design/ant-design#14647]
- [✔️] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qzvr57q81j )

### Steps to reproduce
拖拽表格头的大小，在表格头上释放鼠标，会触发 sort

### What is expected?
拖拽释放鼠标 不会触发 sort

### What is actually happening?
 触发了 sort

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.x |
| System | mac |
| Browser | chrome latest |

**Comment by zombieJ** [comment]
用 `stopPropagation`: https://codesandbox.io/s/1qnmpry8qj

**Comment by AlwaysBeOk** [comment]
it is not work..

**Comment by zombieJ** [comment]
@AlwaysBeOk, thanks for notice. Update the demo. Pls check.

**Comment by AlwaysBeOk** [comment]
What is the principle？

**Comment by zombieJ** [comment]
> What is the principle？

table use `onClick` to trigger sorter. The resize block is also a child node of th. So mark it when resizing and not trigger onClick.

**Comment by xiaoiver** [comment]
上面的例子中需要修改下这里：
``` tsx
if (!width) {
  // return <th {...restProps} />;
  return <th {...restProps} onClick={onClick} />;
}
```

否则会出现未设置 `width` 即不支持拖拽的列无法排序的现象（点击最后一列的排序）：
https://codesandbox.io/s/resizeabletable-de23n

**Comment by piyushk96** [comment]
> ~Use `stopPropagation`: https://codesandbox.io/s/1qnmpry8qj~
> 
> Update the demo: https://codesandbox.io/s/zrj8xvyzxx

@zombieJ can you please update the docs as many users are facing this issue

**Comment by zombieJ** [comment]
done

**Comment by vaynevayne** [comment]
多谢, z-index  是多余的
```css
.react-resizable-handle {
  position: absolute;
  top: 0px;
  bottom: 0px;
  height: 100%;
  width: 4px;
  border-right: 1px dashed rgb(44, 46, 51);
  cursor: col-resize;
}
.react-resizable-handle:hover {
  background-color: rgb(44, 46, 51);
}
```
