### ISSUE TITLE
Support to set this diameter of Badge

### ISSUE THREAD

**Issue by shinnqy** [ant-design/ant-design#14881]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Make easier to customize the size of Badge by setting diameter instead of rewrite several css properties.

Say if I want a Badge with diameter = 24px
```less
.ant-badge-count {
    height: 24px;
    line-height: 24px;
    min-width: 24px;
    width: 24px;
    padding: 0 7.2px;
    font-size: 14.4px;
}
```

### What does the proposed API look like?
```js
const yourDiameter = 24;
<Badge diameter={yourDiameter} />
```
