### ISSUE TITLE
inputnumber  is not css align setting..

### ISSUE THREAD

**Issue by wishu101** [ant-design/ant-design#14943]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
i want setting inputnumber align right
{textalign:'right'}
not accept web browser 

### What does the proposed API look like?
number align

**Comment by afc163** [comment]
It is hard to align number in current design, I will pass it.

**Comment by The-io-dev** [comment]
Could this issue be reconsidered ?

My team would like to be able to align text inside an inputNumber to the right, unfortunately the value find itself hidden under the arrows of the field.
Having this ability would allow users to easily compare multiple values more easly (like in a bill), but also allow the display of the value when editing it next to the arrows (an behavior appreciated by some people).

There could be options like :
- nzAlign: **left** | center | right (positionning the value of the input according to the size of the input minus the arrows and spacing)
- nzArrows: **true** | false (that would disable arrows if set to false and could also be usefull if the input is very small)

**Comment by engmsilva** [comment]
`input.ant-input {
  text-align: right;
}`

**Comment by yoyo837** [comment]
Do you need RTL?

**Comment by DRYmag** [comment]
It's not for doing some  RTL, as my colleague @ The-io-dev said, it is very common in French applications to have inputs with a number aligned to the right (as in spreadsheet like MS Excel).

In our app, we need this too, because ours users need to writing a lot of numbers (price, remise, bill, ...). These numbers inputs will be within forms but also in tables where comparing numbers is importante and it's a lot more easier (for ours users) when number are right aligned.

Even if tweaking with css is maybe possible, but it's not future proof like a new option `nzAlign` on the input.

**Comment by MauritsvanderZee** [comment]
+1

**Comment by devuxer** [comment]
It's a pretty general rule of UI design that text should be aligned left, and number should be aligned right.

I'd really like to see support for this in `InputNumber`.

As a workaround, you could put something like this in CSS (for Antd 5):

```css
/* right align text for InputNumber */

.ant-input-number-input-wrap {
    padding-right: 18px;
}

.ant-input-number-input-wrap > input.ant-input-number-input {
    text-align: right;
}
```

- The padding is needed so the number doesn't get covered up by the +/- buttons
- `.ant-input-number-input-wrap >` is needed so the selector has enough specificity to override the default

**Comment by ingrid-source** [comment]
Please allow for right alignment for InputNumber. Given that there is an entire section in your specs stating that numbers should be right-aligned, we should be able to do just that.

**Comment by acoBOYZ** [comment]
If anyone still looking for the solution, below solution solved the problem for current version of antd:

```tsx
// solution: style={{ textAlignLast: 'right' }}

// usage:
<InputNumber decimalSeparator=',' controls={false} min={0} step={0.01} style={{ textAlignLast: 'right' }}  />

**Comment by BilalSajid173** [comment]
> If anyone still looking for the solution, below solution solved the problem for current version of antd:
> 
> ```tsx
> // solution: style={{ textAlignLast: 'right' }}
> 
> // usage:
> <InputNumber decimalSeparator=',' controls={false} min={0} step={0.01} style={{ textAlignLast: 'right' }}  />
> ```

This works but the cursor on focus is still left aligned.

**Comment by namanthanki** [comment]
> > If anyone still looking for the solution, below solution solved the problem for current version of antd:
> > ```tsx
> > // solution: style={{ textAlignLast: 'right' }}
> > 
> > // usage:
> > <InputNumber decimalSeparator=',' controls={false} min={0} step={0.01} style={{ textAlignLast: 'right' }}  />
> > ```
> 
> This works but the cursor on focus is still left aligned.

```css
/* Right-align text for InputNumber */
.ant-input-number-input-wrap {
    padding-right: 18px;
}

.ant-input-number-input-wrap > input.ant-input-number-input {
    text-align: right;
}

/* Right-align text and cursor for InputNumber */
.ant-input-number-input {
    text-align: right;
    caret-color: transparent; /* Hides the blinking cursor */
}

.ant-input-number-input::placeholder {
    text-align: left; /* Explicitly Left-aligns the placeholder text */
}

.ant-input-number-input:focus {
    caret-color: auto; /* Shows the cursor when focused */
}
```

Try this, so far this is the best I could come up with
