### ISSUE TITLE
Form验证不通过时，布局跳动

### ISSUE THREAD

**Issue by jimmyabc** [ant-design/ant-design#1557]
垂直排列布局的Form，发起提交时，整个布局会跟着跳动。

原因是显示错误信息的<div class="ant-form-explain">有个3px的marginTop。

之前的版本，这个div在没有错误时有渲染的，可以自己加样式让它没内容可显示的时候也有3px的marginTop。

最新版本，这个div在没错误时没有渲染。

如果还想保留3px的marginTop，有比较好的解决办法吗？

[例子](http://ant.design/components/form/#demo-validate-basic) 

操作方式：来回点击“确定”和“重置”按钮

**Comment by afc163** [comment]
感谢反馈，可先执行覆盖样式修复。

```css
.ant-form-item.ant-form-item-with-help {
  margin-bottom: 3px;
}
```
