### ISSUE TITLE
DatePicker has not correct style

### ISSUE THREAD

**Issue by metauro** [ant-design/ant-design#15787]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mok095q40p?fontsize=14)

### Steps to reproduce
click date picker and open a panel

### What is expected?
has correct style 

### What is actually happening?
not correct style

| Environment | Info |
|---|---|
| antd | 3.16.0 |
| React | 16.8.3 |
| System | macos10.14.4 Beta |
| Browser | google chrome  73.0.3683.86 |

---
the panel and date picker will overlapping when I use the following styles
```css
* {
  position: relative;
}
```

the following styles can fix this problem
```css
.ant-calendar-year-panel,
.ant-calendar-month-panel {
    top: 1px !important;
}

.ant-calendar-year-panel-body,
.ant-calendar-month-panel-body {
    background: white !important;
}
```

it is a bug?
