### ISSUE TITLE
Flash of unstyled content for first load

### ISSUE THREAD

**Issue by sheerun** [ant-design/ant-design#16037]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-reproduce.sheerun.now.sh/](https://ant-reproduce.sheerun.now.sh/)

### Steps to reproduce
Disable cache in browser and reload page many times. You can also see Flash Of Unstyled Content in slow motion when you use Performance tab in Developer Tools and enable screenshot recording.

### What is expected?
Page should render and no FOUC or animations should be visible

### What is actually happening?
Flash of Unstyled Content: https://v.usetapes.com/pX8SB0q5K0

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16 |
| System | MacOS |
| Browser | Google Chrome 74 |

---
I suspect this is because ::before and ::after in CSS which are applied to html only after CSS is loaded. I think the only way to avoid it is to not use ::before in CSS and rather render final html in React.

**Comment by afc163** [comment]
I believe it is a next.js problem than antd's.

**Comment by sheerun** [comment]
I've sent you example with just html and css. It's pure html page, no next.js there.

The effect is also the same when I deploy it on platform other than now.sh.

**Comment by sheerun** [comment]
I did an experiment where I removed all `::before` and `::after` from CSS and problem persists. It means the problem is something different than these. Still, it's antd issue, not next.js.

**Comment by sheerun** [comment]
I seems that problem is connection to "transition:" css rules, as when I remove all of them from CSS the problem stops or at least is too short to notice: https://ant-reproduce-2.sheerun.now.sh/

I guess the solution could be to enable all animations only after antd is loaded

**Comment by sheerun** [comment]
Here's very minimal reproduction that still has this issue:

antd.css:

```css
.ant-btn {
  line-height: 1.499;
  position: relative;
  display: inline-block;
  font-weight: 400;
  white-space: nowrap;
  text-align: center;
  background-image: none;
  border: 1px solid transparent;
  -webkit-box-shadow: 0 2px 0 rgba(0, 0, 0, 0.015);
          box-shadow: 0 2px 0 rgba(0, 0, 0, 0.015);
  cursor: pointer;
  -webkit-transition: all 0.3s cubic-bezier(0.645, 0.045, 0.355, 1);
  transition: all 0.3s cubic-bezier(0.645, 0.045, 0.355, 1);
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
  -ms-touch-action: manipulation;
      touch-action: manipulation;
  height: 32px;
  padding: 0 15px;
  font-size: 14px;
  border-radius: 4px;
  color: rgba(0, 0, 0, 0.65);
  background-color: #fff;
  border-color: #d9d9d9;
}
```

index.html:

```
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="./antd.css"/>
  </head>
  <body>
    <button type="button" class="ant-btn">
      <span>Cancel</span>
    </button>
  </body>
</html>
```

Interestingly the problem is gone when I use `<style>...</style>` instead of link, but it's not viable solution as <link> is required for any real-world application so styles are cached
