### ISSUE TITLE
能否为自定义Input+button组合增加一些样式支持，以便与datepicker、timepicker的风格保持一致

### ISSUE THREAD

**Issue by xuzhy** [ant-design/ant-design#1626]
你好
我尝试使用Input组件的addonBefore和addonAfter属性，但发现风格与antd自带的datepicker等Input+button组件不太一致，而且也不好为按钮绑定事件。
我也尝试了.ant-input-group-wrap样式，但似乎该样式不适用于按钮。

我现在是这样做的：
jsx
```jsx
 <FormItem label="用户昵称：" { ...formItemLayout }>
    <Input type="text" { ...userNickNameProps } style={{ paddingRight: 19 }} />
    <span className="ant-input-icon">
        <Icon { ...userNickNameLockProps } />
    </span>
</FormItem>
```
css
```css
.ant-input-icon {
    position: absolute;
    user-select: none;
    transition: all 0.3s cubic-bezier(0.645, 0.045, 0.355, 1);
    width: 12px;
    height: 12px;
    line-height: 12px;
    right: 8px;
    color: #999;
    top: 50%;
    margin-top: -6px;
}
```
效果
![fm l4siwuwv pds 8ufhe](https://cloud.githubusercontent.com/assets/8393696/15148196/c82a942e-16f6-11e6-890d-8e312c2b0f1b.png)
![jwwib w362 4ck 8_3 6f](https://cloud.githubusercontent.com/assets/8393696/15148204/ca504302-16f6-11e6-82eb-26cda91e3d73.png)

不过这样做可能会对FormItem的hasFeedback属性产生影响 : (

## 环境信息

- antd版本(0.12.17):
- 操作系统(Windows 7):
- 浏览器(Chrome 50.0.2661.94 m(64-bit)):
