### ISSUE TITLE
antd table 当设置 size=samll 且添加勾选列时，勾选列遮挡了表格第一列

### ISSUE THREAD

**Issue by yunxifd** [ant-design/ant-design#16645]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-johnson-esr40)

### Steps to reproduce
1. 缩小浏览器，使表格出现横向滚动条
1. 查看表格第一列显示

### What is expected?
勾选列遮挡了 表格第一列

### What is actually happening?
勾选列不遮挡表格第一列

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.9.0 |
| System | win10  |
| Browser | chrome 74 |

---
手动在浏览器上添加
```css
.ant-table-selection-column {
    width: 62px;
    min-width: 62px;
    text-align: center;
}
```

样式时，显示正常
