### ISSUE TITLE
如何修改波纹动效的颜色

### ISSUE THREAD

**Issue by AAAgeekWeb** [ant-design/ant-design#16938]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以设置波纹动效的颜色是非主色的其他颜色，现在直接用css覆盖是不生效的

### What does the proposed API look like?
可以通过css样式覆盖来达到修改颜色的目的。
```css
[ant-click-animating-without-extra-node='true']::after
.ant-click-animating-node { 
  box-shadow: 0 0 0 $primary ;
  border-color: $primary !important;
  background-color:$primary !important;
}
```

**Comment by afc163** [comment]
什么样的效果？为啥会和主色不一样？

**Comment by AAAgeekWeb** [comment]
@afc163  我的项目主色是读取配置的，不同配置颜色不一样。我现在的主色是通过css变量实现，如果直接将@primary-color设置成css变量，less是编译不通过的。因此我通过样式覆盖来替换主色，但是波纹颜色通过css覆盖不生效。

**Comment by zombieJ** [comment]
可以覆盖 `--antd-wave-shadow-color` css 变量：https://codesandbox.io/s/sad-carson-idpe8

**Comment by AAAgeekWeb** [comment]
@zombieJ  我antd的版本号为3.7.3 react和react-dom版本号都是16.2.0。在你给的示例中，是没有波纹效果的，有两个疑问：
1. 我本地对应版本号是有波纹效果的，而且试了你的方法 也是颜色并不生效
2. 如果实在改不了，那我如何全局关闭波纹效果

**Comment by afc163** [comment]
Try 3.19.2

**Comment by AAAgeekWeb** [comment]
@afc163 由于项目自身原因，我们的版本号是写死的 暂时改不了版本号

**Comment by afc163** [comment]
那可能我们也没啥好办法了，你需要自行探索了。

**Comment by AAAgeekWeb** [comment]
@afc163 我关闭这个功能吗

**Comment by AAAgeekWeb** [comment]
> 可以覆盖 `--antd-wave-shadow-color` css 变量：https://codesandbox.io/s/sad-carson-idpe8

这种方法对Radio组件不生效，https://codesandbox.io/s/elastic-swartz-i5muf 请问对Radio应该如何替换颜色

**Comment by zombieJ** [comment]
https://codesandbox.io/s/misty-rgb-k1mh6

**Comment by vanishcode** [comment]
button自定义wave颜色不生效的应该再单独指定：
```css
[ant-click-animating-without-extra-node="true"]::after {
  border-color: red !important;
  --antd-wave-shadow-color: red !important;   // 此行
}
```
