### ISSUE TITLE
Can ant design pro's table customize the extension subcolumn?

### ISSUE THREAD

**Issue by anran758** [ant-design/ant-design#17571]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In some business scenarios, it may be necessary to trigger an extended subrow in the specified column.

### What does the proposed API look like?
We want the table to expose Boolean parameters that hide the default extension icon.
 then provide a way for external components to control whether or not to expand the content?

**Comment by dengfuping** [comment]
@anran758 Temporary workaround like this [demo](https://codesandbox.io/s/funny-lehmann-9fjng):
```css
.ant-table-expand-icon-th,
.ant-table-row-expand-icon-cell {
  display: none;
}

tr.ant-table-expanded-row > td:first-child {
  display: none;
}
```
