### ISSUE TITLE
Component - rate

### ISSUE THREAD

**Issue by 4val0v** [ant-design/ant-design#17754]
Also remove the `margin` for the last element.
![last star margin](https://user-images.githubusercontent.com/11297476/61415416-37eb4780-a8f9-11e9-84a4-8d76af7801c0.png)
**_Solution:_**
```CSS
li:not(:last-child) {
    margin-right: 8px;
}
```
_Now I use:_
```CSS
::ng-deep .ant-rate {
  li {
    margin: 0 4px 0 4px
  }
}
```
![NG-ZORRO ANT Component Rate (Half star)](https://user-images.githubusercontent.com/11297476/61474180-b515cb80-a990-11e9-88f7-b7447a8d0c28.png)

| Environment | Info |
|---|---|
| NG-ZORRO | LAST |
| Angular | 8 |
| Browser | Chrome |
