### ISSUE TITLE
 rotate trigger of the right Sider when collapsedWidth is 0

### ISSUE THREAD

**Issue by kagawagao** [ant-design/ant-design#18026]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://github.com/ant-design/ant-design/blob/60e66dbafedeaf5dbfdf1331d071e8680ebb7059/components/layout/style/index.less#L115-L117

current trigger is just stay in the left, but not be inverse

### What does the proposed API look like?
use `transform` or make `border-radius` inverted, but  change `border-radius` will not make icon inverted

```less
&-right {
   transform: rotate3d(0, 0, 1, 180deg);
   // or
  border-radius: @border-radius-base 0 0 @border-radius-base;
}
```
