### ISSUE TITLE
Steps组件当背景色不为白色时, title部分会有白色背景遮挡，并且无法通过传入style进行设置

### ISSUE THREAD

**Issue by sojohn** [ant-design/ant-design#1841]
演示: http://codepen.io/sojohn/pen/zBOvNr?editors=0100
需要提供一个入口设置step的title及icon的背景色

**Comment by afc163** [comment]
```css
.ant-steps .ant-steps-head, 
.ant-steps .ant-steps-title {
  background: xxx;
}
```

先这么覆盖一下，这里现在是一个 css trick ，目前没找到完美的 css 方案。
