### ISSUE TITLE
如何设置Carousel的dots位置 

### ISSUE THREAD

**Issue by bethinner** [ant-design/ant-design#1857]
我希望Carousel的指示点不是在轮播图的下面而是在图片占据的空间里面展示

**Comment by foriacus** [comment]
覆盖  .ant-carousel .slick-dots {} 和 .ant-carousel .slick-dots  {}这两处的样式就行了。

**Comment by afc163** [comment]
@foriacus is right.

**Comment by pimkle** [comment]
利用 dotsClass ？

**Comment by theprimone** [comment]
说说我的问题吧，看了[官方文档](https://ant.design/components/carousel-cn/)说：

> 更多参数可参考：https://github.com/akiran/react-slick

我就去学习这个文档了，然后用这个 dotsClass 去自定义 dots，编译之后未生效_(:3J∠)_覆盖 slick-dots 之后 ok 了

**Comment by DaiZhaoedu** [comment]
> 覆盖 .ant-carousel .slick-slider {} 和 .ant-carousel .slick-dots {}这两处的样式就行了。
刚接触react不久。请问如何覆盖样式呢？
这样写，没有起作用
```less
.ant-carousel .slick-slider{
    :global{.ant-carousel .slick-dots{
                height: 50px;
    }
    }
}
```
