### ISSUE TITLE
.ant-checkbox-input z-index: 9999  这个值太高了吧

### ISSUE THREAD

**Issue by hanai** [ant-design/ant-design#186]
``` css
.ant-checkbox-input {
    position: absolute;
    left: 0;
    z-index: 9999;
    cursor: pointer;
    opacity: 0;
    top: 0;
    bottom: 0;
    right: 0;
}
```
