### ISSUE TITLE
menu margin bfc

### ISSUE THREAD

**Issue by tangjinzhou** [ant-design/ant-design#19477]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/menu-cn/](https://ant-design.gitee.io/components/menu-cn/)

### Steps to reproduce
菜单选项的margin重叠
![image](https://user-images.githubusercontent.com/6937879/67745771-08072080-fa60-11e9-87a9-dfd81d63a186.png)

注意到有一个
```css
.ant-menu-inline .ant-menu-submenu {
    padding-bottom: .01px;
}
```
用来bfc？  但是并没有生效

如果没有重叠问题，inline 模式展开动画也会更加流畅

### What is expected?
无 margin 重叠，展开动画更加流畅
增加如下css可解决
```css
.ant-menu-inline .ant-menu-submenu {
    overflow: hidden;
}
```

### What is actually happening?
略有卡顿

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | all |
| System | all |
| Browser | chrome |
