### ISSUE TITLE
关于 Affix 的 宽 高（之前没按格式写抱歉）

### ISSUE THREAD

**Issue by xutou12** [ant-design/ant-design#1987]
## 你做了什么？

body 下面
```jsx
<Row className="toolbar-wrap" style="padding: 0 4%">
  <Affix offsetTop={offsetTop}>
    <Row className="toolbar">
      <Col style={{ float: 'left' }}>
        <Button  {...buttonProps}>
            刷新
        </Button>
      </Col>
      <Col style={{ float: 'right' }}>
        <Pagination {...paginationProps} />
      </Col>
    </Row>
  </Affix>
</Row>
```

```less
.toolbar-wrap {
  .ant-affix {
    width: 100%;
    padding-right: 8%;
  }
}
```

## 你期待的结果是：

在窗口resize时 .toolbar-wrap 宽度变化自适应，.toolbar 宽度跟随父节点变化
左侧跟父节点对齐，固定元素下面的内容正常展示

## 实际上的结果和抱怨：

左侧没有跟父节点对齐，宽度也没有跟随变化，固定元素下面的内容瞬间被固定元素挡住
出现了固定元素在状态变化瞬间下面的内容上下跳动的情况

## 可重现的在线演示

无

## 本地环境信息

- antd 版本:1.3.2
- 操作系统及其版本：mac os x 10.11.5
- 浏览器及其版本:safari 9.1.1
