### ISSUE TITLE
IE9中 Checkbox 的对钩缺少旋转

### ISSUE THREAD

**Issue by abbish** [ant-design/ant-design#2062]
![screen shot 2016-06-16 at 11 43 12](https://cloud.githubusercontent.com/assets/138192/16104907/e4c10504-33b7-11e6-8d17-32c357a6c4fd.png)
如上图

**Comment by abbish** [comment]
增加下面样式解决
-ms-transform: rotate(10deg);

**Comment by afc163** [comment]
我测试了最新版是没有问题的，你是如何引入样式的？

我们的样式中有对 IE9 的兼容处理：https://npmcdn.com/antd@1.4.1/dist/antd.css

```css
.ant-checkbox-inner:after {
  -webkit-transform: rotate(45deg) scale(0);
      -ms-transform: rotate(45deg) scale(0);
          transform: rotate(45deg) scale(0);
  position: absolute;
  left: 4px;
  top: 1px;
  display: table;
  width: 5px;
  height: 8px;
  border: 2px solid #fff;
  border-top: 0;
  border-left: 0;
  content: ' ';
  -webkit-transition: all 0.1s cubic-bezier(0.71, -0.46, 0.88, 0.6);
  transition: all 0.1s cubic-bezier(0.71, -0.46, 0.88, 0.6);
}
```
