### ISSUE TITLE
Disable multiple errors in Form Item

### ISSUE THREAD

**Issue by rohit-gohri** [ant-design/ant-design#21145]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently if multiple rules are present for a Form.Item, all of them are displayed individually.

Input a simple space (" ") in the first form item here:
https://codesandbox.io/s/antd-reproduction-template-810fl

There should be an option to only display the first error from the rules.

### What does the proposed API look like?
Something like the option already present in async-validator: `{first: true}`
Could be passed through Config Provider

**Comment by dmwin72015** [comment]
+1

**Comment by Pacheco95** [comment]
You can replace the styles to hide all other errors but first:

```css
form div.ant-form-item-explain .ant-form-item-explain-error:not(:first-child) {
  display: none;
}
```
