### ISSUE TITLE
<Table /> 组件里固定列和不固定列的单元格高度不一致

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#2132]
比如下图，`备注`列为非固定列，`批准状态`为固定列，由于备足内容为两行，所以出现高度不一致现象，这种要怎么解决呢？

![53972d06-947d-4cdb-8eb3-3cdd34fb7b4f](https://cloud.githubusercontent.com/assets/2840462/16255572/9d629afe-387d-11e6-81ab-59e2227a8934.png)

在 `antd.css` 里有看到强制 `<td> ` 不换行，不知道是不是为了避免这种现象
```css
.ant-table-fixed-left th, .ant-table-fixed-right th, .ant-table-scroll th, .ant-table-fixed-left td, .ant-table-fixed-right td, .ant-table-scroll td {
    white-space: nowrap;
}

``` 

但是在实际场景中，应该会有很多场景都会显示多行的吧
