### ISSUE TITLE
Badge - Disable animation prop

### ISSUE THREAD

**Issue by rvitorgomes** [ant-design/ant-design#21345]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Prevent the initial rendering animation of the Badge

Example
https://codesandbox.io/s/antd-reproduction-template-ehdz8
Version: 3.26.8

### What does the proposed API look like?
A prop to the Badge component that disables the initial animation

**Comment by afc163** [comment]
You can try

```css
.ant-badge-zoom-appear {
  animation: none;
}
```

https://codesandbox.io/s/antd-reproduction-template-dgzgq

**Comment by jeggy** [comment]
Just leaving a comment here for others, solution by @afc163 does not work in version ant version 4.

This can be used instead:
```less
.ant-scroll-number-only {
  transform: none !important;
}
```
