### ISSUE TITLE
antd V4 Modal 希望增加 children 的 Footer 

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#21388]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在 `Modal` `Children` 中也可以自定义渲染 `Header` `Footer`，样式继承 `Modal` 的样式。

### What does the proposed API look like?
```jsx
      <Modal visible={visible}>
        {({ header, footer }) => {
          return (
            <div>
              {header(<p>demo header</p>)}
              content。。。
              {footer(
                <>
                  <Button>自定义按钮</Button>
                  <Button onClick={() => setVisible(false)}>取消</Button>
                </>,
              )}
            </div>
          );
        }}
      </Modal>
```

**Comment by crazyair** [comment]
这样对于弹框表单，就好写多了。

**Comment by yoyo837** [comment]
和直接传footer区别是什么？

**Comment by crazyair** [comment]
> 和直接传footer区别是什么？

一个在内一个在外，不一样。

**Comment by yoyo837** [comment]
小弟没看出啥大的区别，内外与否也没啥影响。

**Comment by crazyair** [comment]
> 小弟没看出啥大的区别，内外与否也没啥影响。

就说 
![image](https://user-images.githubusercontent.com/7971419/74585570-be474380-5018-11ea-95be-115c398e083c.png)

```jsx
      <Form.Item {...tailLayout}>
        <Button type="primary" htmlType="submit">
          Submit
        </Button>
      </Form.Item>
```
这个 `submit` 能写到 `footer` 上吗。写道 `footer` 上就是在 `form` 外面了，回车后能提交表单吗？

**Comment by yoyo837** [comment]
但是 父元素里放children, children是来自父元素的作用域的，并不能从内部得来哒，所以我觉得这个例子并无关系。

**Comment by afc163** [comment]
可以在 children 里自定义结构和样式就好了。

**Comment by crazyair** [comment]
> 但是 父元素里放children, children是来自父元素的作用域的，并不能从内部得来哒，所以我觉得这个例子并无关系。

你还是没理解。


> 可以在 children 里自定义结构和样式就好了。

只能这样了。

**Comment by crazyair** [comment]
> 可以在 children 里自定义结构和样式就好了。

怎么引用这个 `ConfigConsumer` 我要用 `getPrefixCls`。

**Comment by crazyair** [comment]
less

```less
@import '~antd/dist/antd.less';

@dialog-prefix-cls: ~'@{ant-prefix}-modal';
@table-prefix-cls: ~'@{ant-prefix}-table';
@dialog-wrap-rtl-cls: ~'@{dialog-prefix-cls}-wrap-rtl';

.demo .@{dialog-prefix-cls} {
  &-body {
    padding: 0;
  }
  &-body-children {
    padding: @modal-body-padding;
  }
}
```

```jsx
<Modal visible={visible} footer={null} title="demo" wrapClassName="demo">
  <div className="ant-modal-body-children">
    <p>2</p>
    <p>2</p>
  </div>
  <div className="ant-modal-footer">
    <div>
      <Button>ok</Button>
      <Button>cancel</Button>
    </div>
  </div>
</Modal>
```

这样吗？ `ant` 这个能不写死吗？
