### ISSUE TITLE
ant.design 官网 form 组件 高级搜索demo 样式错误

### ISSUE THREAD

**Issue by maxmeng93** [ant-design/ant-design#21403]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/ant-design-bug.vu8co5801hp.gif)

### What is expected?
高级搜索demo 样式正确

### What is actually happening?
高级搜索demo 样式错误

| Environment | Info |
|---|---|
| antd | 3.26.10 |
| React | 16.12.0 |
| System | windows 10 |
| Browser | chrome |

**Comment by maxmeng93** [comment]
``` css
.ant-row::before, .ant-row::after {
    display: table;
    /* width: 100%; */
    content: '';
}
```
把css中的 `width:100%;` 去掉就正常了。
