### ISSUE TITLE
咨询一下为什么块级元素的 margin 和 padding 设为 0？

### ISSUE THREAD

**Issue by Alex1990** [ant-design/ant-design#2158]
即下面代码：

```css
// unify the setting of elements's margin and padding for browsers
body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,textarea,p,blockquote,th,td,hr,button,article,aside,details,figcaption,figure,footer,header,hgroup,menu,nav,section {
  margin: 0;
  padding: 0;
}
```

而不是像 Bootstrap 那样提供 Typography 样式，这样就不需要再单独为 `h1`，`p`, `form` 之类设置 `margin`了。

总之，想请教您两点问题：

- 选择目前方案的权衡考虑。
- 在目前方案基础上，开发时如何**方便快速**设定元素（组件）之间的间距的（不使用原子类）？
