### ISSUE TITLE
Menu.Item not show <a> tag inline text with Icon

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#21649]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/currying-dream-n8xo1)

### Steps to reproduce
a tag text not show

### What is expected?
display text

### What is actually happening?
a tag text not show

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.6 |
| React | 16.9 |
| System | windows 10 |
| Browser | chrome 75.0.3770.100  |

**Comment by shaodahong** [comment]
we can remove `display`  style to resolve it

```less
.ant-menu-item > a {
    display: block;
}
```

**Comment by MuYunyun** [comment]
This is an intentional design. We usually use the tag `a` to jump to some url. If the tag a is not block element, the area will be very difficult to click for jumping.

And if use the tag a, the icon should be written in the tag, for example:

```js
<Menu.Item>
  <a><Icon />demo</a>
</Menu.Item>
```

Write in this way, the icon can be click for jumping too. Hope to help you.

**Comment by shaodahong** [comment]
yep, I know block element user-friendly to click, so there are pseudo-elements already

```less
.ant-menu-item > a::before {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background-color: transparent;
    content: '';
}
```
