### ISSUE TITLE
[v4] Wrong styles when generating with less variables

### ISSUE THREAD

**Issue by Arttse** [ant-design/ant-design#21909]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-v4-with-less-variables-reproduction-template-0mozw)

### Steps to reproduce
I use less css variables:
```lesscss
@font-size-base: 16px;
@border-radius-base: 4px;
```

Then I import components:
```
<Select mode="tags" />
```
```
<Button type="primary" size="small" icon={<PlusCircleOutlined />}>
  Some text
</Button>
```

### What is expected?
Normal Button with right padding, normal Select with right padding and margin (between tags) like with default less css build.

### What is actually happening?
Button component has wrong padding:
```css
.ant-btn-sm {
  padding: -1.6px 7px;
}
```

Select component has wrong padding:
```css
.ant-select-multiple .ant-select-selector {
  padding: -0.6px 2.4px
}
```
And space between tags (margin) is too small:
```css
.ant-select-multiple .ant-select-selection-item {
  margin-right: 2.4px;
}
```

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13.0 |
| System | Linux |
| Browser | Google Chrome 80 |

---
There are also problems with negative padding in other places in the final CSS.

A prefix `ant-` is missing, for example:
```css
.ant-picker-input > input-sm {
  padding: -1.6px 7px;
}
```
