### ISSUE TITLE
Multiple select search input doesn't show normally on Safari

### ISSUE THREAD

**Issue by iicdii** [ant-design/ant-design#21950]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dreamy-agnesi-g500u)

### Steps to reproduce
1. type Orlando
2. select first item
3. type Brown

### What is expected?
The select input must show what you type.

### What is actually happening?
The letters you type on input doesn't show full text. Especially the first letter completely doesn't show.

![KakaoTalk_Photo_2020-03-06-20-10-52](https://user-images.githubusercontent.com/4951716/76078774-b01c8f80-5fe6-11ea-9eaa-fc02e7ba49e7.jpeg)
![KakaoTalk_Photo_2020-03-06-20-10-23](https://user-images.githubusercontent.com/4951716/76078766-ad219f00-5fe6-11ea-86b2-c23d072d8c6e.jpeg)

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | 16.12.0 |
| System | iOS 13.3.1 |
| Browser | Safari 13 |

---
I tested it on antd v4.0.1, it's same.

**Comment by iicdii** [comment]
I found why. It's because different padding applied to input between Safari and Chrome. 
```css
/* user agent style sheet in Safari */
textarea, input[type="range"], input, input:matches([type="password"], [type="search"]) {
  ...
  padding-top: 0.2em;
  padding-right: 0.5em;
  padding-bottom: 0.3em;
  padding-left: 0.5em;
}

/* user agent style sheet in Chrome */
textarea, input[type="range"], input, input:matches([type="password"], [type="search"]) {
  ...
  padding-top: 1px;
  padding-right: 1px;
  padding-bottom: 1px;
  padding-left: 1px;
}
```
I think we need to fix padding to the input in multiple selection.
