### ISSUE TITLE
Toggle dark with @media (prefers-color-scheme: dark)

### ISSUE THREAD

**Issue by Innei** [ant-design/ant-design#23370]
# What problem does this feature solve?
The theme color changes according to the system theme

主题色根据系统主题变换

# What does the proposed API look like?
```
import 'antd/dist/antd.dark.css'
```
加载这个样式后，并不是直接应用到全局，而是可以通过一个类名，比如 <body class="dark">来切换主题。

再或者是把 less 颜色变量暴露到 css var
```css
:root {
    --red: #ff6347;
    --yellow: #ffc107;
    --blue: #6495ed;
}
@media screen and (prefers-color-scheme: dark)
:root {
    color: #ddd;
    --red: #ad1a00;
    --blue: #1346a4;
}
```

#16661
