### ISSUE TITLE
Menu样式修改建议

### ISSUE THREAD

**Issue by ansonchen** [ant-design/ant-design#2364]
Menu里面的index.less部分代码如下
``` css
&-vertical, &-inline {
    padding: 12px 0;
    & > .@{menu-prefix-cls}-item, & > .@{menu-prefix-cls}-submenu > .@{menu-prefix-cls}-submenu-title {
      padding: 0 24px;
      font-size: 12px;
      line-height: 42px;
      height: 42px;
    }
  }
```
建议改成：
``` css
     { 
      font-size: @font-size-base;
      line-height: 3.5em;
      height: 3.5em;
 }
```` 
的方式，方便统一修改样式
