### ISSUE TITLE
v4 input 在 ie11 下显示错位

### ISSUE THREAD

**Issue by xiaosongxiaosong** [ant-design/ant-design#23955]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://goblin-laboratory.github.io/cra-lerna-template/login/?from=https%3A%2F%2Fgoblin-laboratory.github.io%2Fcra-lerna-template%2F%23%2F#/](https://goblin-laboratory.github.io/cra-lerna-template/login/?from=https%3A%2F%2Fgoblin-laboratory.github.io%2Fcra-lerna-template%2F%23%2F#/)

### Steps to reproduce
使用 ie11 打开页面

### What is expected?
input 显示正常

### What is actually happening?
input 显示错位

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | win10 |
| Browser | ie11 |

![image](https://user-images.githubusercontent.com/2703455/81373390-42e4c200-912f-11ea-816f-84f4c2e71c59.png)

**Comment by xrkffgg** [comment]
尴尬，没有 IE11 环境，也看不了啥问题 😂

**Comment by xiaosongxiaosong** [comment]
@xrkffgg 我看了下，由于 IE11 下的 flex item 的 box-sizing: border-box 属性不生效导致的

将下面的样式
```css
.ant-input-affix-wrapper > input.ant-input {
    padding-right: 0;
    padding-left: 0;
    border: none;
    outline: none;
}
```

改成

```css
.ant-input-affix-wrapper > input.ant-input {
    padding: 0;
    border: none;
    outline: none;
}
```
可以修复

参考资料：
https://github.com/philipwalton/flexbugs#flexbug-7 

PS: 网络条件太差，clone 了一上午都没成功😭
