### ISSUE TITLE
There are hardcoded values on less files

### ISSUE THREAD

**Issue by mzamoras** [ant-design/ant-design#2424]
Sorry maybe I didn't follow the guidelines, but this issue has nothing to do with my system configuration and I'm sure no example is needed. 

Using antd version 1.6.5. 

Following the guide: [https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme](url) to modify the theme style and color,  some values are not reflected because the less files have hardcoded values instead of the variables it should be referenced to.

**Little example:**
In the style for radio: ( ant-design/components/radio/style/index.less )  

```less
.@{radio-prefix-cls}-button-wrapper {
  margin: 0;
  height: 28px;
  line-height: 26px;
  color: #666;  //  <== should be @text-color  or @btn-default-color
  display: inline-block;
  transition: all 0.3s ease;
  cursor: pointer;
  border: 1px solid @border-color-base;
  border-left: 0;
  background: #fff;  // <== should be @btn-default-bg or @body-background
  padding: 0 16px;

  a {
    color: #666; //  <== should be @text-color  or @btn-default-color
  }
}
````

I've found many of this hardcoded values, making very difficult to actually modify the style.
