### ISSUE TITLE
Missing peerDependencies for yarn@2 compatibility

### ISSUE THREAD

**Issue by irudoy** [ant-design/ant-design#24419]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
```
yarn set version berry
yarn add antd
```

### What is expected?
No warnings

### What is actually happening?
Warnings like that:
```
➤ YN0002: │ rc-animate@npm:2.10.3 doesn't provide react@^15.0.0 || ^16.0.0 requested by rc-util@npm:4.20.1
```

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | any |
| System | any |
| Browser | any |

---
Similar issue for one particular package: https://github.com/react-component/animate/issues/99
And another: https://github.com/react-component/input-number/issues/241

The problem: https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency
Detailed explanation: https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0

The list of `packageExtensions` that resolves all warnings in my case, might be helpful
```yaml
packageExtensions:
  antd@*:
    peerDependencies:
      dayjs: "^1.8.18"
    peerDependenciesMeta:
      dayjs:
        optional: true
  "@ant-design/icons@*":
    peerDependencies:
      react-dom: "15.0.0 || ^16.0.0"
  rc-animate@*:
    peerDependencies:
      react: "15.0.0 || ^16.0.0"
      react-dom: "15.0.0 || ^16.0.0"
  rc-collapse@*:
    peerDependencies:
      react: "15.0.0 || ^16.0.0"
      react-dom: "15.0.0 || ^16.0.0"
  rc-dialog@*:
    peerDependencies:
      react: "15.0.0 || ^16.0.0"
      react-dom: "15.0.0 || ^16.0.0"
  rc-input-number@*:
    peerDependencies:
      react: "15.0.0 || ^16.0.0"
      react-dom: "15.0.0 || ^16.0.0"
  rc-slider@*:
    peerDependencies:
      react: "15.0.0 || ^16.0.0"
      react-dom: "15.0.0 || ^16.0.0"
  rc-tabs@*:
    peerDependencies:
      react: "15.0.0 || ^16.0.0"
  rc-drawer@*:
    peerDependencies:
      react-dom: "15.0.0 || ^16.0.0"
  rc-field-form@*:
    peerDependencies:
      react-dom: "15.0.0 || ^16.0.0"
  rc-mentions@*:
    peerDependencies:
      react-dom: "15.0.0 || ^16.0.0"
```
