### ISSUE TITLE
Divider 标签内含有文字能不能做到居左或居右置顶 

### ISSUE THREAD

**Issue by Nathanielna** [ant-design/ant-design#24859]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如何像官方文档一样居左

### What does the proposed API look like?
能够居左到顶
![image](https://user-images.githubusercontent.com/47273938/84105216-39aa8600-aa4a-11ea-9006-9a7dfde4cefe.png)

**Comment by xrkffgg** [comment]
临时性的话，可以改样式。

``` css
.ant-divider-horizontal.ant-divider-with-text-left::before {
    top: 50%;
    width: 5%;  // 距离左侧距离
}

.ant-divider-inner-text { 
    padding: 0 1em;   // 文字padding
}
```
