### ISSUE TITLE
支持关闭Table的Checkbox动画

### ISSUE THREAD

**Issue by 1123612483** [ant-design/ant-design#25698]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
_**有效解决全选时掉帧造成卡顿的问题。**_
CodeSandbox: https://codesandbox.io/s/condescending-bhaskara-sznns?file=/src/App.js

1. 全选所有记录，由于原生checkbox没有动画，所以没有卡顿的问题。
2. 选中Show antd table。
3. 全选所有记录，由于Antd的Checkbox使用了动画效果，并且渲染的节点很多，造成掉帧卡顿问题。(这是React的渲染机制问题，即使使用了Table的shouldCellUpdate，memo了单元格也无济于事)。

### What does the proposed API look like?
``` javascript
  <Table 
    rowSelection={{
      animation: false
    }}
  />
```
或者，这样Checkbox组件也可以加上这个属性
``` javascript
  <Table 
    rowSelection={{
      getCheckboxProps: {
        animation: false
      }
    }}
  />
```
如果可以，ConfigProvider组件也加这个属性，我不想一个一个去改项目所有的Table。
``` javascript
  <ConfigProvider
    table={{
       rowSelection: {
         animation: false
       }
    }}
  />
```
``` javascript
  <ConfigProvider
    table={{
       rowSelection: {
         getCheckboxProps: {
            animation: false
         }
       }
    }}
  />
```

**Comment by beMySun** [comment]
顶上来

**Comment by xrkffgg** [comment]
可以在需要的地方覆盖样式，外层加个 ID 限制

```css
.ant-checkbox-checked .ant-checkbox-inner::after {
    transition: none;
}

.ant-checkbox-checked::after { 
    animation: none;
}
```

**Comment by 1123612483** [comment]
> 可以在需要的地方覆盖样式，外层套个 id 或 class 限制
> 
> ```css
> .ant-checkbox-checked .ant-checkbox-inner::after {
>     transition: none;
> }
> 
> .ant-checkbox-checked::after { 
>     animation: none;
> }
> ```

感谢解答，再加上table的class以及important，卡顿现象好了许多。

**Comment by 1123612483** [comment]
``` css
.ant-table-cell .ant-checkbox-checked .ant-checkbox-inner::after {
  transition: none !important;
}

.ant-table-cell .ant-checkbox-checked::after {
  animation: none !important;
}
```
