### ISSUE TITLE
Popover doesn't work well with prop "color"

### ISSUE THREAD

**Issue by zmen** [ant-design/ant-design#26419]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focused-satoshi-he06c)

### Steps to reproduce
Just set any color to the component: `<Popover color="#ff0000" ...>...</Popover>`

### What is expected?
The background color of Popover should be the same with the color we set, including the arrow part.

### What is actually happening?
The background of arrow is still white, which looks wired.
![image](https://user-images.githubusercontent.com/11732386/91290159-dff26600-e7c5-11ea-8e8e-7ec01a49b123.png)

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.12.0 |
| System | macOS Catalina 10.15.6 |
| Browser | Chrome 84.0.4147.125 |

---
Seems `Popover` is based on `Tooltip`, `Tooltip` applies the color to `.ant-tooltip-arrow-content` while `Popover` applies to `.ant-popover-arrow-content`. But there is no style for `.ant-popover-arrow-content`, so its width and height  are both 0, which cause this issue.

Besides, I suggest to add props for the color of title and its border,  because they may not fit well with user-defined color.

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/blob/852fad9e3b9c6d8738062a12dc03b248fb6d5807/components/style/themes/default.less#L480-L498

You can use Less-variables

https://ant.design/docs/react/customize-theme#Ant-Design-Less-variables

**Comment by zmen** [comment]
@xrkffgg Thanks for reply. It works but what if I want to change it dynamically？For example, a theme switcher in an app.

**Comment by xrkffgg** [comment]
You can use `overlayClassName`.

Example:
```
<Popover overlayClassName={customerCSS} content={content} title="Title">
    {xxx}
</Popover>
```

```css
.customerCSS1 { 
   .ant-popover-inner {
      background-color: xxx;
   }
   .ant-popover-title {
      color: xxx;
   }
}

.customerCSS2 { 
   .ant-popover-inner {
      background-color: xxx;
   }
   .ant-popover-title {
      color: xxx;
   }
}
```

Then you change `customerCSS` to get different styles.
