### ISSUE TITLE
DatePicker/RangePicker on mobile browsers

### ISSUE THREAD

**Issue by khrizt** [ant-design/ant-design#26758]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-uyqw0)

### Steps to reproduce
Open codesandbox link and resize browser window to simulate mobile page width and open rangepicker. RangePicker goes outside the browser window, but there isn't a parameter to show only 1 month or something similar.

### What is expected?
Adapt to the browser width

### What is actually happening?
RangePicker goes outside browser screen

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.9 |
| System | Android |
| Browser | Chrome |

**Comment by nit5343** [comment]
I am also facing similar issue. There should be a way to reder calender one by one

**Comment by sowka1995** [comment]
I tried to wrap two panels on mobile devices but absolute positioning behave strange. 
Does anyone know how to adapt RangePicker for mobile device?

**Comment by yuenzp** [comment]
Any solutions?

**Comment by Valar103769** [comment]
> Any solutions?

Any solutions?@afc163

**Comment by deadit** [comment]
any solutions?=/

**Comment by IonelLupu** [comment]
@afc163 What does the "Inactive" label mean? It means this won't be implemented ever?

**Comment by paschalidi** [comment]
How would someone go about this?

**Comment by IonelLupu** [comment]
@afc163 I want to help add this feature. What are some tips that you can give me about this regarding the code and the functionality, what helpers to use for mobile (if any), etc. ?

**Comment by vladasko-g** [comment]
hacky workaround - do a DateTimePicker (e.g. with showTime) and hide the time selection (.ant-picker-time-panel)  this should be an optional design choice in the lib imo

**Comment by muh-hizbe** [comment]
try my solution to overwrite css these classes by adding below css code:

```css
.ant-picker-dropdown {
  @media (max-width: 768px) {
    inset: 51.9333px auto auto 0px !important;
  }
}
.ant-picker-dropdown .ant-picker-panel-container {
  @media (max-width: 768px) {
    max-width: 100vw !important;
    overflow: auto !important;
  }
}
```

**Comment by skchawala** [comment]
try this solution:

```
.ant-picker-panel-container {
    .ant-picker-presets {
        min-height: 25rem !important;
    }
    @media (max-width: 800px) {
        overflow: scroll !important;
        height: 400px;
        .ant-picker-panel-layout {
            flex-direction: column !important;

            .ant-picker-presets {
                max-width: 100% !important;
                min-height: 10rem !important;
            }

            .ant-picker-panels,
            .ant-picker-datetime-panel {
                flex-direction: column !important;
            }
        }
    }
}
```

<img width="240" alt="Screenshot 2024-01-19 at 6 22 43 PM" src="https://github.com/ant-design/ant-design/assets/11574135/51d62e2f-f624-4ad3-a662-60ddaa8a77b6">
<img width="223" alt="Screenshot 2024-01-19 at 6 22 54 PM" src="https://github.com/ant-design/ant-design/assets/11574135/56b24b90-a5c7-4171-af5e-db4c290b8b5a">
<img width="345" alt="Screenshot 2024-01-19 at 6 23 38 PM" src="https://github.com/ant-design/ant-design/assets/11574135/f8b7351c-8e37-4670-bc88-51a21e0316bc">

**Comment by just2102** [comment]
MUI has this functionality out of the box.
Is there any reason anyone would try these solutions instead of just switching to another UI library, especially considering that this issue has been opened since 2020?

**Comment by Useems** [comment]
```css
@media (max-width: 992px) {
  .ant-picker-panel:last-child .ant-picker-date-panel {
    display: none !important;
  }

  .ant-picker-panel:first-child
    .ant-picker-date-panel
    .ant-picker-header-next-btn,
  .ant-picker-panel:first-child
    .ant-picker-date-panel
    .ant-picker-header-super-next-btn {
    visibility: initial !important;
  }

  .ant-picker-panel.ant-picker-range-wrapper {
    min-width: 288px !important;
  }

  .ant-picker-presets {
    display: none !important;
  }
}
```

# Desktop
![image](https://github.com/ant-design/ant-design/assets/34917473/22c7d974-abc6-425e-a7f2-59dc8e8194c3)

# Mobile
![image](https://github.com/ant-design/ant-design/assets/34917473/204b54ec-2257-4a80-8993-49cbb89cb6e2)
![image](https://github.com/ant-design/ant-design/assets/34917473/717344ac-b0a9-4d2e-ae59-754258d8bc47)

**Comment by xsjcTony** [comment]
@afc163 Wondering whether we have any updates? I'm a bit worried since
- The issue has been open for 3 years+
- The issue is being marked as `Inactive`
And this is definitely the feature I need 🤣 Rather than the hacky CSS overwriting way, I would like to see whether a new design will be introduced for this by official team.

**Comment by RodeoAdrian** [comment]
Hey! any update on this? @canisminor1990 @afc163 
Web mobile adaptation is pretty important, is this on your plans?

**Comment by ImMaxence** [comment]
up

**Comment by mrKorg** [comment]
Oh, my gods
when you go to 2024 to see why it looks so bad on a mobile device....

**Comment by annbeemsterboer** [comment]
this is really a big issue. how is a a library of this size and popularity not supporting basic mobile responsiveness for its components?

**Comment by AsuraKev** [comment]
Its almost mid 2024, and this datepicker is unusable in mobile. Is everyone not browsing a site in mobile app nowadays or what :P

**Comment by Muriel-Gasparini** [comment]
> ```css
> @media (max-width: 992px) {
>   .ant-picker-panel:last-child .ant-picker-date-panel {
>     display: none !important;
>   }
> 
>   .ant-picker-panel:first-child
>     .ant-picker-date-panel
>     .ant-picker-header-next-btn,
>   .ant-picker-panel:first-child
>     .ant-picker-date-panel
>     .ant-picker-header-super-next-btn {
>     visibility: initial !important;
>   }
> 
>   .ant-picker-panel.ant-picker-range-wrapper {
>     min-width: 288px !important;
>   }
> 
>   .ant-picker-presets {
>     display: none !important;
>   }
> }
> ```

This approach work's weel, but all my calendars components are hidden when hit's the breakpoint.

**Comment by sky21kr** [comment]
```
.ant-picker-panels {
  flex-direction: column !important;
}
```

before
<img width="373" alt="image" src="https://github.com/user-attachments/assets/e24ec5d4-1108-47c0-bbb4-62242c374afd">


after
<img width="337" alt="image" src="https://github.com/user-attachments/assets/b9e0d3a5-c53f-46c2-822a-0c8f8ffd477c">

**Comment by acher249** [comment]
> try my workaround.
> 
> 1. create file styles.css in root project
>    `.ant-picker-dropdown .ant-picker-panel-container .ant-picker-panels {   display: inline-flex;   animation: none;   flex-wrap: nowrap;   direction: ltr;   @media (max-width: 768px) { display: inline-grid;   } }`
> 2. import file styles.css in App.tsx:
>    `import '.styles.css';`

this one worked nicely for me, thank you!

**Comment by tabrownies** [comment]
Similarly to @acher249 I used the following code in a css file
```css
@media (max-width: 768px) {
    .ant-picker-panels {
        display: flex;
        flex-wrap: wrap !important;
        width: 300px !important;
    }

    .ant-picker-panel:first-child .ant-picker-date-panel .ant-picker-header-super-next-btn,
    .ant-picker-panel:first-child .ant-picker-date-panel .ant-picker-header-next-btn {
        visibility: visible !important;
    }

    .ant-picker-panel:nth-child(2) .ant-picker-date-panel .ant-picker-header-super-next-btn,
    .ant-picker-panel:nth-child(2) .ant-picker-date-panel .ant-picker-header-next-btn {
        visibility: hidden !important;
    }
}

```
