### ISSUE TITLE
Improve UX of TimePicker

### ISSUE THREAD

**Issue by yutimo** [ant-design/ant-design#27480]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In our app users use date / range / time pickers frequently

But they complain about the UX as they have to do too many actions to just change values of the fields

They especially don't like having to scroll through the hours list, like that: https://prnt.sc/va4g61

So i tried to put hours in several columns with regular .css, like that:

```css
.ant-picker-time-panel .ant-picker-content {
    width: 90px;
}

.ant-picker-time-panel-column {
    width: 90px;
    display: flex;
    flex-wrap: wrap;
}

.ant-picker-time-panel-column > li {
    width: 25%;
}
```

The problem is in autoscroll on every value change: https://prnt.sc/va4k77

As i can see in sources, it is not configurable now https://github.com/react-component/time-picker/blob/d708d84bde663d7740c4943c52624beeeda1d2c7/src/Select.jsx#L40

### What does the proposed API look like?
It would be useful to add property autoscrollOnChange: boolean, default true to timepicker
Or (maybe this is more preferable) support columns: 1 | 2 | 3 | 4 default 1
