### ISSUE TITLE
使用ant-ui编写了一个页面，准备将页面使用到react native下，求大神指点

### ISSUE THREAD

**Issue by catcxj** [ant-design/ant-design#2823]
使用ant-ui编写了一个页面，准备将页面使用到react native下，求大神指点。

代码里面使用了栅格布局。

页面代码如下：

```javascript
import React from 'react';
import 'antd/dist/antd.css';
import styles from './styles.css';
import { Row, Col } from 'antd';

class WordPage1 extends React.Component {
	render() {
		return (
			<div>
				<div className={styles.html}>
					<h3>质量评定表</h3>

					<div className={styles.word}>
						<Row>
							<Col span={15} className={styles.left}>承包人：施工总承包项目部</Col>
							<Col span={5} className={styles.left}>合同编号：201506</Col>
							<Col span={4} className={styles.left}>№ </Col>
						</Row>
					</div>
				</div>
			</div>
		);
	}
}
export default WordPage1;
```

styles.css

```css
.left{
	text-align: left;
}
.word-to-html{
	text-align: center;
	color: #000;
}

.html h3{
	margin-bottom: 20px;
	font-size: 20px;
}
```
