### ISSUE TITLE
Carousel走马灯组件的默认dots样式能不能改改？

### ISSUE THREAD

**Issue by ilaipi** [ant-design/ant-design#28384]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在的dots默认只有3px的高度，鼠标只有3px的高度可以点击，太难了。

希望能把这个高度增加点 - - 或者暴露个稍微方便的字段来控制一下可点击的高度

### What does the proposed API look like?
```
dotsHeight: 15px;
```

设置后，dots横线可以在上下15px的高度居中，这样的话在dots的附近区域都可以点击...

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/jiben-antd494-forked-j345i?file=/index.js

**Comment by afc163** [comment]
来个 PR？

**Comment by ilaipi** [comment]
> https://codesandbox.io/s/jiben-antd494-forked-j345i?file=/index.js

我觉得保持原来的视觉效果，只是增加点击区域。就是不要看起来横线都变很粗了。

**Comment by xrkffgg** [comment]
我只是举个🌰 看个人喜好 随意改

**Comment by ilaipi** [comment]
我实现的方式是:
```less
    .slick-dots {
      li {
        & > div {
          padding-top: 10px;
          padding-bottom: 20px;
          cursor: pointer;
        }
        & > div > button {
          height: 3px;
          background: rgba(0, 0, 0, .65);
        }
        &.slick-active > div > button {
          background: #108ee9;
        }
      }
    }
```

```jsx
<Carousel
  customPaging={i => (<div><button>i</button></div>)}
>
</Carousel>
```

感觉不太好pr，我关掉吧
