### ISSUE TITLE
怎样关闭 Tree 的展开/收缩动画效果？

### ISSUE THREAD

**Issue by lnstock** [ant-design/ant-design#28535]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
搜索并定位到相关Node后，由于父节点之前是收缩状态，需要在展开后调用 scrollTo 滚动到该节点，结果由于动画效果的延迟，导致无法正常定位。

### What does the proposed API look like?
麻烦贴一下相关css代码，谢谢

**Comment by xrkffgg** [comment]
```css
.ant-tree .ant-tree-node-content-wrapper {
    transition: none;
}
```

试试
