### ISSUE TITLE
Responsive Col don't support 'flex' prop in ColSize

### ISSUE THREAD

**Issue by RplusSoundOn** [ant-design/ant-design#28961]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/rplussoundon/pen/ExgJZVb?editors=0010](https://codepen.io/rplussoundon/pen/ExgJZVb?editors=0010)

### Steps to reproduce
To resize between `md` and `lg`, the `flex` prop doesn't apply.

### What is expected?
`flex` value should inject to the element inlin style when window size is larger than `md`.

### What is actually happening?
`flex` value does't apply.

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.13.1 |
| System | Mac |
| Browser | Chrome 87.0.4280.141 |

**Comment by RplusSoundOn** [comment]
ColSize should contain `flex` prop
![image](https://user-images.githubusercontent.com/63219476/105316479-dbf33480-5bfb-11eb-8de3-25c4cdcf7689.png)

**Comment by bendrick92** [comment]
Bumping as I'm having the same issue. Setting the `flex` prop via a breakpoint param is not affecting the columns as expected.

```
<Col xs={12} md={{ flex: 'auto' }}>
...
```

I have confirmed other properties are behaving as expected:
```
<Col xs={12} md={{ push: 12 }}>
...
```

**Comment by AlexeySemigradsky** [comment]
Same issue. Not working as expected.

```JavaScript
<Col xs={{ flex: "0 0 100%" }} sm={{ flex: "0 0 auto" }}></Col>
```

**Comment by bendrick92** [comment]
Bumping - any update on a fix?

**Comment by bendrick92** [comment]
Another bump...

**Comment by curly210102** [comment]
@afc163 有实现计划么？或许可以用 [responsiveObserve](https://github.com/ant-design/ant-design/blob/master/components/_util/responsiveObserve.ts) 做动态设置？

**Comment by afc163** [comment]
@curly210102 有，可行。

**Comment by curly210102** [comment]
@afc163 那我上手改咯

**Comment by Tideus** [comment]
Hello! When will it be released? => [33656](https://github.com/ant-design/ant-design/pull/33656)

**Comment by Juroviol** [comment]
+1

**Comment by shieldAgentJZ** [comment]
Having the same issue, has it been solved? Or is there any alternative way to implement responsive flex with the current version?

**Comment by naimeshbarot** [comment]
I am also facing the same issue. I am not able to apply flex for responsive.

**Comment by Daneng66** [comment]
Bump

**Comment by beltjun26** [comment]
Bump LOL

**Comment by DjVreditel** [comment]
Em... Bump ?

**Comment by Clazherx** [comment]
today i discovered this issue, some news about a fix on this?

**Comment by protetore** [comment]
Bump

**Comment by songyot11** [comment]
same

**Comment by aalvarezwindey** [comment]
Same issue

**Comment by aalvarezwindey** [comment]
Is maybe missing here https://github.com/ant-design/ant-design/blob/master/components/grid/col.tsx#L82 something like that?

```jsx
    sizeClassObj = {
      ...sizeClassObj,
      [`${prefixCls}-${size}-${sizeProps.span}`]: sizeProps.span !== undefined,
      [`${prefixCls}-${size}-order-${sizeProps.order}`]: sizeProps.order || sizeProps.order === 0,
      [`${prefixCls}-${size}-offset-${sizeProps.offset}`]:
        sizeProps.offset || sizeProps.offset === 0,
      [`${prefixCls}-${size}-push-${sizeProps.push}`]: sizeProps.push || sizeProps.push === 0,
      [`${prefixCls}-${size}-pull-${sizeProps.pull}`]: sizeProps.pull || sizeProps.pull === 0,
      [`${prefixCls}-rtl`]: direction === 'rtl',

      // next line is missing
      [`${prefixCls}-${size}-flex-${sizeProps.flex}`]: sizeProps.flex || sizeProps.flex === '', // 
    };
```

**Comment by AlexisSniffer** [comment]
Is there a fix that was merged about this problem but in later versions this error still appears? Any solution or example of how this works? xs={{ flex: 'auto' }}

**Comment by extremecode0xFF** [comment]
fix doesn't work

**Comment by DjVreditel** [comment]
BUMP

**Comment by chungnq253** [comment]
BUMP!!!

**Comment by Tantalon** [comment]
@AlexisSniffer @afc163 the pull request https://github.com/ant-design/ant-design/pull/41962 added a flex prop to ColSize. However, there's no CSS for it in [genLoopGridColumnsStyle](https://github.com/ant-design/ant-design/blob/5b75f3f817f74564da407ba40d7aaf5f980a4884/components/grid/style/index.ts#L90), so the prop doesn't do anything when set.

Please can this be reopened?

This is a workaround to enable the flex keywords:
```css
.ant-col-xs-flex-initial { flex: initial; }
.ant-col-xs-flex-auto { flex: auto; }
.ant-col-xs-flex-none { flex: none; }
@media (min-width: 576px) {
  .ant-col-sm-flex-initial { flex: initial; }
  .ant-col-sm-flex-auto { flex: auto; }
  .ant-col-sm-flex-none { flex: none; }
}
@media (min-width: 768px) {
  .ant-col-md-flex-initial { flex: initial; }
  .ant-col-md-flex-auto { flex: auto; }
  .ant-col-md-flex-none { flex: none; }
}
@media (min-width: 992px) {
  .ant-col-lg-flex-initial { flex: initial; }
  .ant-col-lg-flex-auto { flex: auto; }
  .ant-col-lg-flex-none { flex: none; }
}
@media (min-width: 1200px) {
  .ant-col-xl-flex-initial { flex: initial; }
  .ant-col-xl-flex-auto { flex: auto; }
  .ant-col-xl-flex-none { flex: none; }
}
@media (min-width: 1600px) {
  .ant-col-xxl-flex-initial { flex: initial; }
  .ant-col-xxl-flex-auto { flex: auto; }
  .ant-col-xxl-flex-none { flex: none; }
}
```
