### ISSUE TITLE
Table row expanded icon disappears when expanded on Firefox and looks like a checkbox

### ISSUE THREAD

**Issue by yasikovsky** [ant-design/ant-design#29303]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-uh9o8?file=/index.js)

### Steps to reproduce
Click on the "expand" icon.

### What is expected?
Icon becomes horizontal

### What is actually happening?
Icon animates and disappears afterwards.

| Environment | Info |
|---|---|
| antd | 4.12.2 |
| React | 17 |
| System | Windows 10 |
| Browser | Firefox 86 |

This is most likely due to scaling issues (::after width being 1px and displaying as 0 on certain scales), because after zooming the page in it works.

Workaround for now:

```scss
.ant-table-row-expand-icon::after {
 bottom: 2px;
}

.ant-table-row-expand-icon::before {
  height: 2px;
}

```
