### ISSUE TITLE
[Feature Request] 移除颜色计算相关的 less 函数，以支持 css variables

### ISSUE THREAD

**Issue by dancerphil** [ant-design/ant-design#32807]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

## 背景

一直以来我们都使用 antd 来构建我们的组件库，并且我们一直在使用 css variables。看到 antd 通过动态主题来支持 css variables，我们非常兴奋，并且尝试使用，但是与我们预期的还有一些距离。

我们开启此 issue，希望可以讨论一下以怎样的方式支持 css variables，以满足更通用的需求，以及更方便用户的升级。

## 我们的做法

我们的业务场景，只需要支持现代浏览器，所以我们的内部组件库一直是使用 css variables 作为基础设施的。

在我们的 theme 里，我们使用类似以下的方式来定义 less 变量，并支持 dark mode：

```less
@primary-color: var(--ant-primary-color);

:root {
    --ant-primary-color: #1890ff;
}

@media (prefers-color-scheme: dark) {
    --ant-primary-color: #1890ff;
}
```

但我们会遇到一个最大的阻碍，即当遇到 less function 如 `fade` 的时候，就会产生编译问题。

目前我们通过重载 less function 解决了这个问题，但这样肯定不如官方支持，这样颜色更精准，也省去了我们的工作。

## 我们的建议

使用 less 变量来自定义样式的方式已经非常成熟了，我们希望继续这种模式，并在此基础上支持 css variables。

从 less 的角度来说，除了 `fade` 这几个函数以外，没有什么其他的阻碍。

在动态主题的开发中，我看到已经有很多 less function 被移除了，如果可以移除所有的 less function，我们可以很自然的使用原来的方式支持 css variables。

如果 antd 同意把所有的 less function 移除（与颜色计算相关的部分），我们可以提供 PR。

相关成员： @otakustay, @yuxuan

### What does the proposed API look like?
```less
@primary-color: var(--ant-primary-color);

:root {
    --ant-primary-color: #1890ff;
}

@media (prefers-color-scheme: dark) {
    --ant-primary-color: #1890ff;
}
```
