### ISSUE TITLE
global.less file svg style is cutting of elements inside svg element

### ISSUE THREAD

**Issue by cliffordfajardo** [ant-design/ant-design#33573]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/strange-tree-2c8i4?file=/src/index.css)

### Steps to reproduce
1. Visit index.css file in the [codesanbox](https://codesandbox.io/s/strange-tree-2c8i4?file=/src/index.css), which contains the CSS rule that ant design is using, which causes svg canvas element to be cut off
2. Drag the canvas

https://user-images.githubusercontent.com/6743796/148293028-6464140b-5d4d-442d-acc8-c501780678e0.mp4

### What is expected?
As a user using antd library, I expect antd not to apply global styles to html elements in order to reduce the possibility of antd clashing with other libraries.

Instead, css override rule should be more specific in order to avoid chances of antd clashing with other libraries

For example:
- https://github.com/ant-design/ant-design/blame/b6bd4c18b4f00efa7d8e133618ee008fcf5a2911/components/style/core/global.less#L284

```css
//global.css

❌
svg:not(:root) {
  overflow: hidden; // Hide the overflow in IE
}

✅
.anticon svg:not(:root) {
  overflow: hidden; // Hide the overflow in IE
}
```

### What is actually happening?
The global.css rule targeting svg elements is to borad, css selector should be more specific

| Environment | Info |
|---|---|
| antd | 4.17.4 |
| React | 17.02 |
| System | MacOS |
| Browser | Chrome latest version |
