### ISSUE TITLE
Upload上传文件夹图片时，图片过多，下方图片list显示过长？

### ISSUE THREAD

**Issue by strongyc** [ant-design/ant-design#33628]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Upload上传文件夹图片时，图片过多，下方图片list显示过长，该怎么优化显示list的长度，或者使用滑动能显示上传成功的list

### What does the proposed API look like?
上传文件夹图片过多时，支持滚动查看上传成功的list，防止文件过多显示较长。

**Comment by afc163** [comment]
```css
.ant-upload-list {
  overflow: auto;
  max-height: 300px;
}
```
