### ISSUE TITLE
Snapshot test failing due to ant-click-animating-without-extra-node

### ISSUE THREAD

**Issue by Pacheco95** [ant-design/ant-design#34139]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jiox7p)

### Steps to reproduce
1. Clone https://codesandbox.io/s/antd-reproduction-template-forked-jiox7p
2. Run test (it works)
3. Run it in CI and it will fail:
```
// ...
    -           ant-click-animating-without-extra-node="false"
                ant-click-animating-without-extra-node="true"
// ...
```

### What is expected?
the test works in localhost and CI

### What is actually happening?
It's not working in CI

```
FAIL src/components/InstallApp/InstallApp.spec.tsx
  ● InstallApp › should ask user to install app

    expect(received).toMatchSnapshot()

    Snapshot name: `InstallApp should ask user to install app 1`

    - Snapshot  - 1
      Received    1

    @@ -13,11  13,11 @@
            >
              <p>
                Install App
              </p>
              <button
    -           ant-click-animating-without-extra-node="false"
                ant-click-animating-without-extra-node="true"
                class="ant-btn installButton"
                type="button"
              >
                <span
                  aria-label="download"

      49 |
      50 |     expect(promptSpy).toBeCalled();
    > 51 |     expect(container).toMatchSnapshot();
         |                       ^
      52 |   });
      53 |
      54 |   it('should display installation success notification', () => {

      at Object.<anonymous> (src/components/InstallApp/InstallApp.spec.tsx:51:23)

 › 1 snapshot failed.
```

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | Ubuntu 20.04.3 LTS |
| Browser | N/A |

**Comment by MadCcc** [comment]
Since it works in localhost, I think you should check your CI environment...

**Comment by Pacheco95** [comment]
The CI is only installing the dependencies and running the tests. Github actions:

```yaml
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run tests with coverage report
        run: npm run test:coverage
```
