### ISSUE TITLE
同时使用使用 Datepicker Select 时没有对齐

### ISSUE THREAD

**Issue by daysv** [ant-design/ant-design#3481]
#### 发生问题的环境是：

- antd 版本: 2.1.0
- 操作系统及其版本: win7 x64
- 浏览器及其版本: chrome 53.0.2785.143 m

#### 您做了什么？

同时使用 Datepicker Select

#### 您期待的结果是：

两个组件对齐

#### 实际上的结果是：

两个控件没有对齐， 需要在DatePicker 中增加 `verticalAlign: 'middle'`样式进行修复

#### 可重现的在线演示

[http://codepen.io/daysv/pen/BLqbxw](http://codepen.io/daysv/pen/BLqbxw)

**Comment by benjycui** [comment]
`Select` 是有 `vertical-align: middle` 的，DatePicker 应该是忘了加。

**Comment by afc163** [comment]
这个我来改，应该是 Select 不应该 `vertical-align: middle`。

**Comment by afc163** [comment]
1. Select 去掉 `vertical-align: middle`，保持和 Input、DatePicker 等一致的默认 `vertical-align: baseline`。
2. `vertical-align: baseline` 是按照 Select 内部自然排版的文本进行对齐，由于 Select 内部的 placeholder 和搜索框都是绝对定位（无法对齐），这里使用了一个小技巧，通过给内部补充一个始终存在的文本来对齐。

   ```css
   .ant-select-selection--single .ant-select-selection__rendered::after {
      content: '.';
      visibility: hidden;
      pointer-events: none;
    }
   ```

3. `.ant-select-selection__rendered` 的 `overflow: hidden` 会影响文本对齐，去掉。
4. 去掉后会破坏原来的文本溢出省略号效果，一一予以修正。
