### ISSUE TITLE
提供一个隐藏 IE 下 table header scrollbar 的办法

### ISSUE THREAD

**Issue by zation** [ant-design/ant-design#3511]
比较 tricky，但是我试了下是 work 的

```css
  .ant-table-scroll {
    position: relative;

    &:before {
      content: '';
      display: block;
      position: absolute;
      width: 18px;
      background: #F7F7F7;
      right: 0;
      top: 0;
      bottom: 0;
      pointer-events: none;
    }
  }
```

http://codepen.io/zation/pen/BLGOAP?editors=001
上面这个 demo 在 IE 下打开，table header scrollbar 就没有显示了
