### ISSUE TITLE
Select多选 maxTagCount="responsive"，选择的第一项超长，会显示成 +1

### ISSUE THREAD

**Issue by Necroogre** [ant-design/ant-design#35727]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-1yn17i?file=/index.js)

### Steps to reproduce

选择第1项

### What is expected?

下拉项内容超长的情况，选择的第一项能以...展示而不是 +1

### What is actually happening?

显示 1

| Environment | Info |
| --- | --- |
| antd | 4.20.6 |
| React | 17 |
| System | windows 10 |
| Browser | Chrome 101.0.4951.67 |

**Comment by Necroogre** [comment]
发现一个不太完美的解决方案
``` css
.ant-select-selection-overflow-item:first-child {
    max-width: calc(100% - 60px);
}
```
1.仅显示1项时，尾部有空白
2.select宽度<100px，显示不了任何信息
