### ISSUE TITLE
React 18 下 Modal 组件动画不正常 且关闭可能出现闪烁

### ISSUE THREAD

**Issue by izhouteng** [ant-design/ant-design#36911]
### Reproduction link

[https://stackblitz.com/edit/react-yng9pn?file=index.js](https://stackblitz.com/edit/react-yng9pn?file=index.js)

### Steps to reproduce

1. 打开 [https://react-yng9pn.stackblitz.io](https://react-yng9pn.stackblitz.io)
2. 打开 Chrome DevTools -> 性能 -> CPU -> 设为四倍降速。（为了 100% 复现）
3. 打开 Modal，然后关闭，会出现闪烁；再次打开关闭，会发现动画变得不正常。

### What is expected?

动画正常、关闭不出现闪烁。

## 关闭闪烁
![关闭闪烁](https://s2.loli.net/2022/08/05/F92gNn7OK4MUtQY.gif)

## 动画不正常
![动画不正常](https://s2.loli.net/2022/08/05/8B3qrwbCs1Q2MAY.gif)

ps: 打开过一次之后，动画不再是从按钮方向出现的，而是从屏幕中央，关闭时也是（只有首次动画正常）。

| Environment | Info |
| --- | --- |
| antd | 4.22.3 |
| React | ^18.0.0 |
| System | Windows 10 |
| Browser | Chrome 101.0.4951.67 |

---
这俩问题只在 React 18 才会复现。

其实从 React 18 以来，就一直存在。但无法 100% 复现（有时候随便点一下就出现闪烁，有时候点十几下都不出现），就没提出来。

直到近日又看到有人提 issue 反馈这个问题。恰巧我找到了一种100%复现的方法，就提了出来。

**Comment by afc163** [comment]
感谢给了这么细致的重现步骤。

**Comment by izhouteng** [comment]
闪烁原因似乎是因为 React 18 的 `Automatic Batching` 特性，导致 `rc-dialog` 中的 [setAnimatedVisible(false)](https://github.com/react-component/dialog/blob/2644f198c316680a9c32f7cf5101fbe6ff59fcff/src/DialogWrap.tsx#L49) 没有及时渲染。

然后 `display` 没有及时变成 `none`
```tsx
<div
  tabIndex={-1}
  onKeyDown={onWrapperKeyDown}
  className={classNames(`${prefixCls}-wrap`, wrapClassName)}
  ref={wrapperRef}
  onClick={onWrapperClick}
  style={{ zIndex, ...wrapStyle, display: !animatedVisible ? 'none' : null }}
  {...wrapProps}
>
```

原本过渡动画完成后，是可以靠 CSS 来隐藏的：
```css
.rc-dialog-zoom-leave.rc-dialog-zoom-leave-active {
    animation-name: rcDialogZoomOut;
    animation-play-state: running;
}
```
```css
@keyframes rcDialogZoomOut {
  0% {
    transform: scale(1, 1);
  }
  100% {
    opacity: 0;
    transform: scale(0, 0);
  }
}
```

但 `rc-motion`  过渡完成后，会将 `className` 覆盖成 `leavedClassName`。

```tsx
if (mergedVisible) {
  motionChildren = children({ ...mergedProps }, setNodeRef);
} else if (!removeOnLeave && renderedRef.current) {
  motionChildren = children(
    { ...mergedProps, className: leavedClassName },
    setNodeRef,
  );
} else if (forceRender) {
  motionChildren = children(
    { ...mergedProps, style: { display: 'none' } },
    setNodeRef,
  );
} else {
  motionChildren = null;
}
```

这就导致 `rcDialogZoomOut` 的 `opacity: 0` 与 `transform: scale(0, 0)` 失效了。

此时 `.rc-dialog-wrap` 的 `display` 还没变成 `none`，`Modal` 自然就又显示出来了。

然后 `display` 变成 `none` ，就造成了闪烁。

我感觉可以也加一句 `style: { display: 'none' }` 来解决闪烁。
