### ISSUE TITLE
不是问题，一个建议。

### ISSUE THREAD

**Issue by monsterooo** [ant-design/ant-design#3707]
不太懂为什么要加上normalize.css。可以参考jqury ui的做法嘛。这样肯定每个人使用的时候都会被你这样的东西搞得头疼
```css
a {
  color: #2db7f5;
  background: transparent;
  text-decoration: none;
  outline: none;
  cursor: pointer;
  -webkit-transition: color .3s ease;
  transition: color .3s ease;
}
a:hover {
  color: #57c5f7;
}
a:active {
  color: #2baee9;
}
```
