### ISSUE TITLE
Spin style中定义position: relative; 产生的问题

### ISSUE THREAD

**Issue by artisanship** [ant-design/ant-design#37164]
### Reproduction link

[https://stackblitz.com/edit/react-94slix?file=demo.js,index.css](https://stackblitz.com/edit/react-94slix?file=demo.js,index.css)

### Steps to reproduce

1、在Spin组件上层加入一个容器div.example

2、Spin容器里加入div.example-footer

3、style.css
```css
.example {
   position: relative; 
   padding-bottom: 20px;
   height: 100px;
}
.example-footer {
   position: absolute; 
   bottom: 0;
}
```
此时的div.example-footer是按Spin中的position来进行定位的
```html
<div className="example">
      <Spin spinning={loading}>
        <div>
          <h1>Hello Antd!</h1>
          <p>Start editing to see some magic happen :)</p>
        </div>
        <div className="example-footer">Footer</div>
      </Spin>
</div>
```

### What is expected?

div.example应该定位在div.example-footer的底部填充(20px)上。

### What is actually happening?

div.example定位在了Spin的底部

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17.0.2 |
| System | macOS 12.4 |
| Browser | Chrome 103.0.5060.53 |
