### ISSUE TITLE
segmented 白色文字，深色背景，切换有延迟

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#37192]
### Steps to reproduce

https://user-images.githubusercontent.com/7971419/186079718-55d1058e-9004-42f8-8bb5-2b7829971e1b.mp4

### What is actually happening?

| Environment | Info |
| --- | --- |
| antd | 4.22.7 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by crazyair** [comment]
@vagusX

**Comment by crazyair** [comment]
> @crazyair 你这边修改了哪些颜色值？可以发一下我复现下


        'segmented-bg': 'white',
        'segmented-hover-bg': 'white',
        'segmented-selected-bg': '#5254CC',
        'segmented-label-color': '#595959',
        'segmented-label-hover-color': '#595959',

**Comment by crazyair** [comment]
> 看起来需要增加一个 `@segmented-selected-color` 的变量支持一下前景色定制
> 
> 我来搞一下

怎么样了，还有上面我使用，还有 less部分
```less
.@{ant-prefix}-segmented {
    border: 1px solid #d9d9d9;
    .@{ant-prefix}-segmented-item-selected {
        color: white;
        transition: none;
    }
}
```

**Comment by XueMeijing** [comment]
切换的时候会在.ant-segmented-group insertBefore一个div，所以我目前使用这种方法解决的，点击的时候给父元素增加一个exec-segmented-selected${index}的class，index是倒序索引，然后用倒序设置对应子元素的color

```js
<Segmented
  className={`exec-segmented exec-segmented-selected${
    execTypes.findIndex((item) => item.value === execType) - execTypes.length
  }`}
  onChange={(value) => setExecType(value)}
  options={execTypes}
  value={execType}
/>
```

```css
.exec-segmented-selected-1 {
  .ant-segmented-group {
    label:nth-last-child(1) {
      color: #fff;
    }
  }
}
.exec-segmented-selected-2 {
  .ant-segmented-group {
    label:nth-last-child(2) {
      color: #fff;
    }
  }
}
...
```


https://user-images.githubusercontent.com/35559153/212888971-8042d3b6-9525-4c7f-9021-c8ce768dc0a6.mp4

**Comment by ClearLuvMoki** [comment]
![image](https://user-images.githubusercontent.com/61321768/225646994-5dc97730-c59f-4e4b-9473-4e5826d7fbf5.png)

**Comment by afc163** [comment]
5.x 里还有这个问题不

**Comment by MadCcc** [comment]
动画结束后才会更新选中项，这个问题似乎不太简单。
5.x 目前还有类似问题：https://codesandbox.io/s/ji-ben-antd-5-9-0-forked-8gsjjn

**Comment by afc163** [comment]
点击后就应该直接更新。

**Comment by dingshaohua-com** [comment]
> 切换的时候会在.ant-segmented-group insertBefore一个div，所以我目前使用这种方法解决的，点击的时候给父元素增加一个exec-segmented-selected${index}的class，index是倒序索引，然后用倒序设置对应子元素的color
> 
> ```js
> <Segmented
>   className={`exec-segmented exec-segmented-selected${
>     execTypes.findIndex((item) => item.value === execType) - execTypes.length
>   }`}
>   onChange={(value) => setExecType(value)}
>   options={execTypes}
>   value={execType}
> />
> ```
> 
> ```css
> .exec-segmented-selected-1 {
>   .ant-segmented-group {
>     label:nth-last-child(1) {
>       color: #fff;
>     }
>   }
> }
> .exec-segmented-selected-2 {
>   .ant-segmented-group {
>     label:nth-last-child(2) {
>       color: #fff;
>     }
>   }
> }
> ...
> ```
> 
>  QQ20230117-193342-HD.mp4

very good，resolve my question！
but i use less，
```less
.setSelected(@n, @i: 1) when (@i =< @n) {
    .exec-segmented-selected-@{i} {
        .ant-segmented-group {
            label:nth-last-child(@{i}) {
                color: rgba(0, 0, 0, 0.8);
            }
        }
    }
    .setSelected(@n, (@i + 1));
}
.setSelected(4);
```
