### ISSUE TITLE
Table组件能怎么能支持高度固定？

### ISSUE THREAD

**Issue by wangchao18654941093** [ant-design/ant-design#37359]
### What problem does this feature solve?

首先吐槽下： 我搜了下之前的issue记录，明明有很多这种需求，为什么就不提供这个解决方案 #12088  #37069 等等

需求： 一个页面， 想让Table 不论Table 有没有内容，内容的多少 占一个计算出来的固定高度，pagination在底部
![1662094067778](https://user-images.githubusercontent.com/107595890/188061389-1a1dd910-9f20-4f60-84ad-2f323f085a20.jpg)

### What does the proposed API look like?

scroll:{ height: height}

**Comment by wangchao18654941093** [comment]
之前有个隐藏的api，bodyStyle 在里面可以设置高度，但是现在版本更新已经把这个入口给关闭了，api移除了， 现在 没发解决问题了

**Comment by wangchao18654941093** [comment]
难道不觉得  存在分页时，当你点击最后一页（最后一页的数据很少时），分页忽然跑到了上面，布局一下就变了，不觉得很怪异吗？你们内部都不自己使用这个组件吗？用户体验极差。

**Comment by jounzhang** [comment]
同样的需求，分页在页面上乱跳，看着很舒服？

**Comment by afc163** [comment]
原来的 bodyStyle 如何支持这个需求，能给一下方式么？在哪个版本这个方式不支持了？

**Comment by wangchao18654941093** [comment]
> 原来的 bodyStyle 如何支持这个需求，能给一下方式么？在哪个版本这个方式不支持了？

bodyStyle就是设置table 内容区域样式的，直接设置就可以类似bodyStyle:{height:400}，你可以看看最新的源码他上面有注释，说移除这个了

**Comment by wangchao18654941093** [comment]
> 原来的 bodyStyle 如何支持这个需求，能给一下方式么？在哪个版本这个方式不支持了？

bodyStyle就是设置table 内容区域样式的，直接设置就可以类似bodyStyle:{height:400}，你可以看看最新的源码他上面有注释，说移除这个了

> 原来的 bodyStyle 如何支持这个需求，能给一下方式么？在哪个版本这个方式不支持了？

目前已经找到这个解决方案了，就是动态的修改Table内容高度，解决的当时不是很优雅。

**Comment by alienzhangyw** [comment]
这个我是自己对Table做了一层封装，使用resizeObserver获取高度变化，使表格能自适应填充所在区域。
``` typescript
// ...

const target = useRef<HTMLDivElement>(null);
const size = useSize(target); // resizeObserver获取target的contentRect大小
const [tableHeight, setTableHeight] = useState(433); // 表格高度，默认值大约显示10行

useEffect(() => {
  if (size?.height) {
    const headerHeight = target.current?.firstElementChild?.getElementsByClassName('ant-table-header')[0]?.clientHeight || 39;
    const pagiHeight = target.current?.firstElementChild?.getElementsByClassName('ant-table-pagination')[0]?.clientHeight || 0;
    const newHeight = size.height - headerHeight - ((pagiHeight || -12) + 12);
    setTableHeight(Math.round(newHeight));
  }
}, [size?.height, tableProps.loading]);

// ...

return (
  <div ref={target} style={{ heigt: '100%', width: '100%' }} >
    <Table
      {...tableProps}
      className={classNames(className, styles.table)}
      scroll={{ x: '100%', y: tableHeight }}
     // ...
    />
  </div>
)

```
``` less
.table {
  height: 100%;
  width: 100%;

  :global .ant-spin-nested-loading {
    height: 100%;
  }

  :global .ant-spin-container {
    height: 100%;
    display: flex;
    flex-direction: column;

    >.ant-table {
      flex: 1;

      >.ant-table-container {
        height: 100%;
        display: flex;
        flex-direction: column;

        >.ant-table-body {
          flex: 1;
        }
      }
    }

    >.ant-pagination {
      margin: 12px 0 0;
    }
  }
}
```
