### ISSUE TITLE
2.3.1版的table组件在ie11及ie10中默认显示为半透明

### ISSUE THREAD

**Issue by joe-sky** [ant-design/ant-design#3755]
#### 发生问题的环境是：

- antd 版本: 2.3.1
- 操作系统及其版本: win7
- 浏览器及其版本: ie11的edge及ie10模式

#### 您做了什么？请提供尽可能详细的重现步骤。

使用table组件

#### 您期待的结果是:

table显示透明度正常

#### 实际上的结果是:

table默认显示为半透明，应是有个遮罩层的opacity小于1导致。

在源码`antd/lib/spin/style/index.css`中155行发现为ie10+设置了透明度：
```css
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
  /* IE10+ */
  .ant-spin-nested-loading > .ant-spin-container {
    background: #fff;
    opacity: 0.5;
  }
}
```
貌似是这里设置的`opacity: 0.5`导致的，IE9下就没有这个问题...

#### 可重现的在线演示

用IE11及IE10访问[官方文档的table例子](https://ant.design/components/table/)即可重现。
