### ISSUE TITLE
DatePicker日期选择框希望能新增选择器类型-半年

### ISSUE THREAD

**Issue by qianfengg** [ant-design/ant-design#37639]
### What problem does this feature solve?

DatePicker日期选择框可以选择上半年，下半年

### What does the proposed API look like?

picker参数目前有，date | week | month | quarter | year
希望新增类型 half-year

**Comment by afc163** [comment]
半年感觉用 Select 配合来做更好。。

**Comment by YunPeng75** [comment]
> 半年感觉用 Select 配合来做更好。。

可不可以增加个多选功能，可以分开选择

**Comment by liucys** [comment]
尝试实现了一下：区分上半年与下半年以1和2为区别。具体时间判断看个人需求了。
```js
import { DownOutlined } from '@ant-design/icons';
import { DatePicker } from 'antd';
import { useEffect, useState } from 'react';
import moment from 'moment';
import styles from './index.less';

interface Props {
  value?: any; // Form组件传递的值
  onChange?: (value: any) => void; // Form组件中使用时必须方法
  onValueCB?: (value: any) => void; // 额外的时间变化选择回调
}

const yearHalf: any[] = [
  {
    label: '上半年',
    value: 1,
  },
  {
    label: '下半年',
    value: 2,
  },
];

const dateFormat = (time: any, half: number) => {
  if (half === 0) {
    return ``;
  }
  return `${moment(time).format('YYYY')} / ${half === 1 ? '上半年' : '下半年'}`;
};

const YearDateHalf = ({ value, onChange, onValueCB }: Props) => {
  // 日期选择框状态
  const [hasDate, setHasDate] = useState<boolean>(false);
  // 选择的日期
  const [dateVal, setDateVal] = useState<any>(undefined);
  // 上半年还是下半年
  const [half, setHalf] = useState<number>(0);

  //   年度日期选择
  const handlerDateChange = (date: any) => {
    if (date) {
      setHalf(0);
      setDateVal(date);
      setHasDate(true);
    } else {
      setHalf(0);
      setHasDate(false);
      setDateVal(undefined);
      if (onChange) {
        onChange(null);
      }
      if (onValueCB) {
        onValueCB(null);
      }
    }
  };

  // 上半年/下半年选择
  const handleClickHalf = (val: any) => {
    const year = moment(dateVal).format('YYYY');
    const newDate = moment(`${year}-0${val}-01`);
    setHalf(val);
    setHasDate(false);
    if (onChange) {
      onChange(newDate);
    }
    if (onValueCB) {
      onValueCB(newDate);
    }
  };

  useEffect(() => {
    if (value) {
      const halfVal = moment(value).format('M');
      setDateVal(moment(value));
      setHalf(Number(halfVal));
    }
  }, [value]);

  return (
    <div className={styles.yearHalf}>
      <DatePicker
        picker="year"
        style={{ width: '100%' }}
        value={dateVal}
        className="formRadius"
        placeholder="填报期数"
        format={(val: any) => dateFormat(val, half)}
        suffixIcon={<DownOutlined />}
        onChange={handlerDateChange}
      />
      {hasDate && (
        <div className={styles.halfSelectCon}>
          {yearHalf.map((item: any) => {
            return (
              <div key={item.label} onClick={() => handleClickHalf(item.value)}>
                {item.label}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
export default YearDateHalf;

```
样式设置：
```less
.yearHalf {
    position: relative;

    .halfSelectCon {
        left: 0;
        right: 0;
        position: absolute;
        box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;
        border: solid 1px #f5f5f5;
        background: #fff;
        padding: 4px 0;

        >div {
            padding: 4px 11px;
            cursor: pointer;
        }

        >div:hover {
            background: #f5f5f5;
        }
    }
}
```

**Comment by xingorg1** [comment]
想知道为什么不支持呢？像我们这边的业务需求其实还是挺多的，我只好改了源码来支持😭

**Comment by afc163** [comment]
> 想知道为什么不支持呢？像我们这边的业务需求其实还是挺多的，我只好改了源码来支持😭

@xingorg1 半年我们感觉用 Select + DatePicker 实现更合适。

**Comment by toddywang** [comment]
<img width="401" alt="image" src="https://github.com/ant-design/ant-design/assets/3415622/d4a97ffe-f15f-4e21-8feb-650246a84ee5">
我也觉得应该支持，这个场景还是业务经常需要的。

**Comment by afc163** [comment]
这个交互比较复杂，感觉不如 Select 来的直观。

**Comment by yoyo837** [comment]
选个半年为啥还整这么麻烦的组件，我个人的项目对比较复杂的组件是能避免就避免。

**Comment by toddywang** [comment]
我也想问，为什么，设计师就是这样搞的。。。。

**Comment by aspirantzhang** [comment]
我也遇到这个场景。业务中，在这块既然按年、按月、按季度都支持 DatePicker，那半年选择突然变为 Select 是一件很怪的事情。
我目前妥协采取的一种方法：
禁用除1和7月的所有月份，通过 renderExtraFooter 给用户一个提示。
这样辗转实现了上半年与下半年选择的问题，也统一了用户界面。

![period](https://github.com/ant-design/ant-design/assets/24559988/da618fc5-ecdb-45d8-a224-29cbdf0d393c)

pro-component json schema：
```
    {
      colProps: {
        lg: 24,
        xl: 12,
      },
      title: __('field.performance_period'),
      dataIndex: 'performance_period',
      valueType: 'date',
      dependencies: ['period_type'],
      fieldProps: (form) => {
        const periodType = form.getFieldValue('period_type');
        if (periodType === 'year') {
          return {
            format: 'YYYY',
            picker: 'year',
          };
        } else if (periodType === 'quarter') {
          return {
            format: 'YYYY-Q',
            picker: 'quarter',
          };
        } else if (periodType === 'half a year') {
          return {
            disabledDate: (current) => {
              return current && current.month() !== 0 && current.month() !== 6;
            },
            format: 'YYYY-MM',
            picker: 'month',
            renderExtraFooter: () => (
              <>Please select January for the first half of the year, and July for the second half.</>
            ),
          };
        } else if (periodType === 'month') {
          return {
            format: 'YYYY-MM',
            picker: 'month',
          };
        }
        return {};
      },
    },
```

**Comment by focant** [comment]
基于antd Datepicker扩展一下就行啦，官方不愿意支持，就自己上呗
![image](https://github.com/ant-design/ant-design/assets/40012919/280e6716-3cf0-4d15-933c-3f49e820d215)

**Comment by vajsp** [comment]
> 基于antd Datepicker的picker类型扩展一下就行啦，官方不愿意支持，就自己上呗 ![image](https://private-user-images.githubusercontent.com/40012919/336407233-280e6716-3cf0-4d15-933c-3f49e820d215.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzIxMjQsIm5iZiI6MTcyMTgzMTgyNCwicGF0aCI6Ii80MDAxMjkxOS8zMzY0MDcyMzMtMjgwZTY3MTYtM2NmMC00ZDE1LTkzM2MtM2Y0OWU4MjBkMjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE0MzcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5Zjg0M2MwNTVjMGQ4MmFjMmM0ZmY1N2YwOWJlODBlOTQ0ZWViZWM4NjFiMjc2ZWFkMmYyOGM5MjRjOTdkOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aLkufB8OHGHaBvc4NvI3RA8oCFEcDvQG8hbmWD5PXyY)

具体怎么实现的，可以说说么

**Comment by znn0105** [comment]
> 具体怎么实现的，可以说说么

```typescript
// 判断moment对象位于哪个半年
function isFirstHalfYear(date) {
  const month = moment(date).month() + 1; // 获取月份，需要转换为1-12的范围
  return month <= 6; // 月份小于等于6则为上半年
}

        <DatePicker
          {...props}
          placeholder="请选择半年度"
          picker="quarter"
          format={(value) => {
            return `${moment(value).year()}年${isFirstHalfYear(value) ? '上半年' : '下半年'}`;
          }}
          className={styles.halfYearPickerBox}
          dropdownClassName={styles.halfYearPicker}
        />
```

样式：
```less
.halfYearPicker {
  :global {
    .ant-picker-year-panel,
    .ant-picker-quarter-panel {
      width: 230px;
    }
    .ant-picker-quarter-panel {
      .ant-picker-content {
        tr {
          display: flex;
          flex-wrap: wrap;
        }
        td {
          display: flex;
          align-items: center;
          justify-content: center;
          width: 50%;
          height: 50px;
          padding: 20px;
        }
      }
      .ant-picker-cell-selected {
        &::before {
          color: #fff;
          background: #5788ff;
        }
      }
      .ant-picker-cell {
        &::before {
          right: auto;
          left: auto;
          display: flex;
          align-items: center;
          justify-content: center;
          width: 60%;
        }
      }
      .ant-picker-cell-inner {
        display: none;
      }
      .ant-picker-cell[title$='-Q1'] {
        &::before {
          content: '上半年';
        }
      }
      .ant-picker-cell[title$='-Q3'] {
        &::before {
          content: '下半年';
        }
      }
      .ant-picker-cell[title$='-Q2'], .ant-picker-cell[title$='-Q4'] {
        display: none;
      }
    }
  }
}
```

最后传值需要处理一下，因为实际值还是Q1和Q3
