### ISSUE TITLE
When I use TextArea with  allowClear. TextArea didn't get styles

### ISSUE THREAD

**Issue by mrshukhratbek** [ant-design/ant-design#38068]
### What is expected?
I want when I wrote styles need to work

### What is actually happening?
I tred give styles to TextArea with allowClear atribute, but didn't get styles on atribute styles. If I used without allowCllear styles atribute. it is working

| Environment | Info |
| --- | --- |
| antd | 4.23.4 |
| React | 18.1.0 |
| System | Windows |
| Browser | Chrome |

---

**Comment by mrshukhratbek** [comment]
Hi @afc163.

This is online reproduction link: https://codesandbox.io/s/antd-reproduction-template-forked-crztv8?file=/index.js

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/31391 cc @zombieJ @MadCcc

**Comment by wangmeijian** [comment]
被这块样式把border干没了
```less
.@{ant-prefix}-input-affix-wrapper-textarea-with-clear-btn {
  padding: 0 !important;
  border: 0 !important;
}
```
