### ISSUE TITLE
怎么在项目的css里面引入静态图片资源

### ISSUE THREAD

**Issue by Nero0** [ant-design/ant-design#387]
layout.css
```css
.logo{
	position: absolute;
	width: 149px;
	height: 52px;
	left:0;
	top:0;
	background: url('../common/static/images/logo.png');
}
```

header.jsx
```js
import React from 'react';
import '../component/layout.css';

var Header = React.createClass({
	render() {
		return  <header className="header">
					<a className="logo" href="..">
				    </a>
				    <div className="user">
				    	<button className="ant-btn ant-btn-primary">登录</button>
				    </div>	
				</header>
	}
})

export default Header;
```

layout.jsx
```js
import React from 'react';
import Header from '../component/header';

var Layout = React.createClass({
	render() {
		return <Header />
	}
});

export default Layout;
```
这样引入图片 webpack打包会报错  Cannot find module "../component/layout.css"
新手求解
