### ISSUE TITLE
Inline menu has border-right that can't be overwritten

### ISSUE THREAD

**Issue by GeorgeFlorian** [ant-design/ant-design#38826]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-inline-menu-has-right-border-when-focuse-visible-z0p5e9)

### Steps to reproduce

Create inline menu in a 100% container
Give it a width smaller than the container

### What is expected?

To display menu without border

### What is actually happening?

The menu has a border-right which creates a white space in the design

| Environment | Info |
| --- | --- |
| antd | 4.23.3 |
| React | 	18.1.0 |
| System | Ubuntu 20.04.5 LTS |
| Browser | Version 107.0.5304.110 (Official Build) (64-bit) |

---
Aside from the border being there for no apparent reason, I can't overwrite the css style for it.
I have tried the following and nothing works:
```css
.container.wrapper.ant-menu-inline {
  border-right: 0;
}
.wrapper.ant-menu-inline {
  border-right: 0;
}
.ant-menu-inline {
  border-right: 0;
}

.wrapper:global(.ant-menu-inline) {
  border-right: 0;
}
```

Also, in my project I have modified all the antd.less variables that had something to do with margin or outline but to no avail:
```less
@menu-item-active-border-width: 0;
@menu-item-boundary-margin: 0;
@menu-icon-margin-right: 0;
@outline-width: 0;
```
