### ISSUE TITLE
tabs组件在设置tab为flex:1时会有概率“抽搐”

### ISSUE THREAD

**Issue by FriedRiceNoodles** [ant-design/ant-design#39079]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/ji-ben-antd-5-0-1-forked-0wyog9?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

```css
body {
  width: 399px;
}

.ant-tabs-nav-list {
  width: 100%;
}

.ant-tabs-tab {
  flex: 1;
}
```

### What is expected?

正常显示

### What is actually happening?

抽搐

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | 16.0.0 |
| System | macos monterey |
| Browser | chrome |
