### ISSUE TITLE
v5 Table Drag sorting 无上提示线

### ISSUE THREAD

**Issue by meseme** [ant-design/ant-design#39218]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/drag-sorting-antd-5-0-3-forked-qg2vuz)

### Steps to reproduce

向下拖动正常，向上拖动无上提示线，v4 无此问题

### What is expected?

正常

### What is actually happening?

不正常

| Environment | Info |
| --- | --- |
| antd | 5.0.3 |
| React | 18.0.0 |
| System | Windows 10 Pro N 19043.1348 |
| Browser | Microsoft Edge Version 96.0.1054.41 |

**Comment by Dunqing** [comment]
![image](https://user-images.githubusercontent.com/29533304/205476192-b06885f4-c5c8-4f82-8aba-bfb54ee44916.png)

官网的demo是正常的，点击codesandbox生成出来的demo样式权重低了所以没展示出来

```css
tr.drop-over-downward td {
  border-bottom: 2px dashed #1890ff;
}

tr.drop-over-upward td {
  border-top: 2px dashed #1890ff;
}
```

可以在前面加上 .ant-table 就能生效了

```css
.ant-table tr.drop-over-downward td {
  border-bottom: 2px dashed #1890ff;
}

.ant-table tr.drop-over-upward td {
  border-top: 2px dashed #1890ff;
}

```
