### ISSUE TITLE
是否有考虑更换一下 Select 的 Arrow Down Icon?

### ISSUE THREAD

**Issue by huacnlee** [ant-design/ant-design#39529]
### What problem does this feature solve?

> 🐼 不知道之前这个话题是否有其他人提起过，我搜索 Issue 没找到类似的。

目前 Select 和 Dropdown 组件的 suffixIcon 用的是 Ant Design Icons 里面自带的 <DownOutlined />，这个图标在 Select 组件默认的尺寸下，显得线条太细，且尺寸偏大，有改进的空间。

![](https://user-images.githubusercontent.com/5518/207281110-142250b5-2e1e-4788-8ac2-92c19b9595e1.png)

比如这种

![](https://user-images.githubusercontent.com/5518/207282645-55474eef-ca40-48a2-be36-72612b950fe0.png)

![](https://user-images.githubusercontent.com/5518/207283044-884c8a3b-581b-48e3-9738-1cd4c6e815b3.png)

因为这个，很多设计在给的时候往往会提需求要求更换它。然而 Ant Design 组件里面有没有全局替换的实现，于是每个项目都写了一个 CSS 来覆盖那个图标。

```css
.ant-select-suffix {
  background: url('data:image/svg xml;base64,PHN2ZyB3aWR0aD0iMTA2cHgiIGhlaWdodD0iNjlweCIgdmlld0JveD0iMCAwIDEwNiA2OSIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIj4KICAgIDxnIHN0cm9rZT0ibm9uZSIgc3Ryb2tlLXdpZHRoPSIxIiBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIG9wYWNpdHk9IjAuNSI CiAgICAgICAgPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTAuMDMzMzMzLCA0LjUxNjY2NykiIGZpbGw9IiMwMDAwMDAiIGZpbGwtcnVsZT0ibm9uemVybyI CiAgICAgICAgICAgIDxwb2x5Z29uIHBvaW50cz0iNTMuMDMzMzMzNCA0MS4yNSA5NC4yODMzMzM0IDAgMTA2LjA2NjY2NyAxMS43ODMzMzM0IDUzLjAzMzMzMzQgNjQuODE2NjY2OCAwIDExLjc4MzMzMzQgMTEuNzgzMzMzNCAxLjExMDIyMzAyZS0xNCI PC9wb2x5Z29uPgogICAgICAgIDwvZz4KICAgIDwvZz4KPC9zdmc ');
  background-size: 9px;
  width: 9px;
  height: 9px;
  background-repeat: no-repeat;
  background-position: center right;
  svg {
    display: none !important;
  }
}
```

同样的问题还有 Modal 的关闭图标，如图，这个图标不是一个精确的正方形比例。

![SCR-20221213-o9i](https://user-images.githubusercontent.com/5518/207280013-b436bb45-8e66-444e-b9ca-7ad5844c9bc3.png)

这个图标我记得从 Ant Design 很早的版本就开始使用了，建议评估一下。

### What does the proposed API look like?

- 从 Ant Design Icons 里面替换 DownOutlined 的图像。
- 或者开放 API，可以全局更换。
