### ISSUE TITLE
Dropdown custom render not working as expected

### ISSUE THREAD

**Issue by thomastvedt** [ant-design/ant-design#39542]
### Reproduction link

[https://ant.design/~demos/components-dropdown-demo-custom-dropdown](https://ant.design/~demos/components-dropdown-demo-custom-dropdown)

### Steps to reproduce

See documentation for Dropdown component and the "dropdownRender" function (https://ant.design/components/dropdown/#components-dropdown-demo-custom-dropdown). In the documentation page it looks ok, but if you open it in full screen: https://ant.design/~demos/components-dropdown-demo-custom-dropdown
you can see that the styling is off.

### What is expected?

I expected the Popover to include everything returned in the "dropdownRender" function. I expected there to be a white background out of the box.

### What is actually happening?

The "Click me" button in the example appears "outside" the popover.

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | 18.2.0 |
| System | OSX |
| Browser | Chrome |

**Comment by thomastvedt** [comment]
Just noticed that the Stackblitz version works as expected, and has some additional CSS:
https://stackblitz.com/run?file=demo.tsx

```css
.dropdown-content {
  background: #fff;
  box-shadow: 0 3px 6px -4px rgb(0 0 0 / 12%), 0 6px 16px 0 rgb(0 0 0 / 8%),
    0 9px 28px 8px rgb(0 0 0 / 5%);
}
.dropdown-content .ant-dropdown-menu {
  box-shadow: none;
}
```

I guess I missed the fact that there was some custom CSS in play here. It would be nice if this could be added to the documentation. Feel free to close this issue as resolved.
