### ISSUE TITLE
多行 checkbox 样式不对齐

### ISSUE THREAD

**Issue by flashback313** [ant-design/ant-design#3971]
antd 版本 2.4.2
![image](https://cloud.githubusercontent.com/assets/7339470/20550913/c26c817c-b175-11e6-8118-677149cfbeb5.png)
由以下样式造成
```css
.ant-checkbox-wrapper + .ant-checkbox-wrapper {
    margin-left: 8px;
}
```
建议改为
```css
.ant-checkbox-wrapper  {
    margin-right: 8px;
}
```

**Comment by benjycui** [comment]
这样好点：

```css
.ant-checkbox-wrapper:not(:last-child)  {
    margin-right: 8px;
}
```

来个 PR 如何？记得测试下。
