### ISSUE TITLE
browser rendering in v5 is slower than v4

### ISSUE THREAD

**Issue by rinick** [ant-design/ant-design#39746]
### Reproduction link

I tried a sample code with about 20 tables:
v5 https://deepmess.com/antd5performance/5.1/build/
v4https://deepmess.com/antd5performance/4.24/build/

### Steps to reproduce
use the performance tab in chrome's develop tool to reload these 2 pages 

"Recalculate Style" takes about 200 ~350ms with v5 while the same example in v4 takes about 100ms.
![](https://azure-rnd.iot-dsa.org/file/proj/rick/assets/screenshot.png)

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18 |
| System | windows 11 |
| Browser | Chrome 108 |

**Comment by rinick** [comment]
Is it possible to pre-generate a css file with all the components being used. 
so cssinjs doesn't need to inject those styles at runtime?

**Comment by rinick** [comment]
I updated the links to make it easier to benchmark with chrome

**Comment by rinick** [comment]
I tried pre define all the css in the v5 html head, so they won't be injected at runtime:
https://deepmess.com/antd5performance/5.1/build/predefine_css.html

however, the performance is almost the same. still much slower than v4

**Comment by rinick** [comment]
It seems, v5's style is defined in a more complicated way than v4 in general
selectors are much longer so they take more time for the browser to render

as an example, in v5, a td element's border-box is affected by these rules
```css
:where(.css-9ntgx0)[class^="ant-table"] [class^="ant-table"]::before, :where(.css-9ntgx0)[class*=" ant-table"] [class^="ant-table"]::before, :where(.css-9ntgx0)[class^="ant-table"] [class*=" ant-table"]::before, :where(.css-9ntgx0)[class*=" ant-table"] [class*=" ant-table"]::before, :where(.css-9ntgx0)[class^="ant-table"] [class^="ant-table"]::after, :where(.css-9ntgx0)[class*=" ant-table"] [class^="ant-table"]::after, :where(.css-9ntgx0)[class^="ant-table"] [class*=" ant-table"]::after, :where(.css-9ntgx0)[class*=" ant-table"] [class*=" ant-table"]::after {
    box-sizing: border-box;
}

```
