### ISSUE TITLE
Typography.Title无法使用className修改文字颜色

### ISSUE THREAD

**Issue by zingxy** [ant-design/ant-design#40093]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-cgk04v?file=/index.css)

### Steps to reproduce

Typograph.Title

### What is expected?

使用className修改Title颜色

### What is actually happening?

无法使用className修改

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18 |
| System | windows |
| Browser | chrome |

---
应该是CSS选择器优先级问题， 
```css
h1:where(.css-dev-only-do-not-override-k83k30).ant-typography, div:where(.css-dev-only-do-not-override-k83k30).ant-typography-h1, div:where(.css-dev-only-do-not-override-k83k30).ant-typography-h1>textarea, :where(.css-dev-only-do-not-override-k83k30).ant-typography h1 {
    margin-bottom: 0.5em;
    color: rgba(0, 0, 0, 0.88);
    font-weight: 600;
    font-size: 38px;
    line-height: 1.2105263157894737;
}
```
上面时devtool显示的一段css, 覆盖了class中定义的color, 但是background-color可以生效

![image](https://user-images.githubusercontent.com/28285708/211202633-2113ed41-82e8-4511-9e3f-35b89203c134.png)
