### ISSUE TITLE
Button with loading property not working when custom iconPrefixCls on ConfigProvider

### ISSUE THREAD

**Issue by doiya46** [ant-design/ant-design#40282]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/error-loading-button-when-change-iconprefixcls-zrhqos?file=/demo.tsx)

### Steps to reproduce

<ConfigProvider    
      iconPrefixCls="myicon"      
    >
      <Button loading>Demo loading</Button>
    </ConfigProvider>

### What is expected?

Loading circle icon worked

### What is actually happening?

Loading circle not working

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | ^18.0.26 |
| System | Ubuntu |
| Browser | All |

**Comment by liwenkang** [comment]
@doiya46 
```css
// antd default config
.anticon-spin::before, .anticon-spin {
  display: inline-block;
  -webkit-animation: loadingCircle 1s infinite linear;
  animation: loadingCircle 1s infinite linear;
}

// if change iconPrefixCls property from "anticon" to "myicon", try add them in index.css
.myicon-spin::before, .myicon-spin {
  display: inline-block;
  -webkit-animation: loadingCircle 1s infinite linear;
  animation: loadingCircle 1s infinite linear;
}
```
