### ISSUE TITLE
360安全浏览器，在使用StyleProvider兼容样式下，message弹出不会消失，dom节点一直存在，但是onClose回调执行了

### ISSUE THREAD

**Issue by 303394539** [ant-design/ant-design#40525]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/winter-cherry-9o4scm?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

1、使用StyleProvider兼容样式
``` typescript
<StyleProvider
  hashPriority="high"
  transformers={[legacyLogicalPropertiesTransformer]}
>
  {children}
</StyleProvider>
```
2、使用测试;
``` typescript
message.error('错误', 1, () => console.log('触发关闭'))
```

### What is expected?

message关闭正常，dom节点删除正常

### What is actually happening?

在360安全浏览器触发了message的onClose回调，但是提示没有消失

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 17.x |
| System | window10 |
| Browser | 360安全浏览器 13.x |

**Comment by zombieJ** [comment]
手头没有 360，截图看一下 DOM 结构是什么样子的？推测和动画有关。

**Comment by 303394539** [comment]
@zombieJ 
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/1750965/216511326-2b1de5c8-5a16-49de-9daf-28ff8ac8e3dc.png">
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/1750965/216511396-07d198af-9280-4241-92b1-94e641e91c62.png">

**Comment by 303394539** [comment]
看起来是因为move-up和move-up-leave-action的样式没有匹配上。
看起来像ant和ant-message这里有问题
我在全局加上
```css
.ant-message-notice.ant-message-move-up-leave.ant-message-move-up-leave-active {
  animation-name: MessageMoveOut;
  animation-duration: 0.3s;
}
@keyframes MessageMoveOut {
  0% {
    max-height: 150px;
    padding: 8px;
    opacity: 1;
  }

  100% {
    max-height: 0;
    padding: 0;
    opacity: 0;
  }
}
```
就正常了，目前只有这么快捷本地修复。你们看下是不是有bug
