### ISSUE TITLE
Plan of Menu refactor

### ISSUE THREAD

**Issue by MadCcc** [ant-design/ant-design#41249]
## 优化点

- [ ] `rc-trigger` 升级为 `@rc-component/trigger`
- [ ] JSX 语法糖移除，数据驱动以获得更高性能
- [ ] 优化渲染逻辑，减少 `active` 等属性带来的不必要渲染 https://github.com/ant-design/ant-design/issues/32681

## 需要解决的问题

- [ ] https://github.com/ant-design/ant-design/issues/41223
- [ ] a 标签问题 https://github.com/ant-design/ant-design/issues/40565
- [ ] overflow 子菜单的 offset 问题 https://github.com/ant-design/ant-design/issues/39007

## 待定

- [ ] https://github.com/ant-design/ant-design/issues/33776
- [ ] https://github.com/ant-design/ant-design/issues/36338

**Comment by afc163** [comment]
- [ ] https://github.com/ant-design/ant-design/issues/41791
- [ ] https://github.com/ant-design/ant-design/issues/41505
- [ ] https://github.com/ant-design/ant-design/issues/29366

**Comment by afc163** [comment]
- [ ] https://github.com/ant-design/ant-design/issues/39306

**Comment by afc163** [comment]
- [ ] https://github.com/ant-design/ant-design/issues/40337

**Comment by monolithed** [comment]
It would be great to have a lightweight menu without a second level and predefined formatting such as a bottom border.


<img width="615" alt="Screenshot 2023-07-14 at 18 21 25" src="https://github.com/ant-design/ant-design/assets/803674/8447d6d2-d187-4dc0-9055-330c9e60f892">

Currently, we have to resort to such hacks for customizing styles. Not only does everything break with any update because these are internal styles, but the component itself is also very heavy for such a simple task.

```css
.ant-menu-title-content:hover {
    color: var(--theme-primary);
    cursor: pointer;
}

.ant-menu-item {
    cursor: default !important;
}

.ant-menu-item::after {
    border: 0 !important;
}
```
