### ISSUE TITLE
给antd4，pagination的margin定义less变量

### ISSUE THREAD

**Issue by BigFatStar** [ant-design/ant-design#41924]
### What problem does this feature solve?

我可以通过修改这个less变量的值自定义我的主题样式

### What does the proposed API look like?

我希望可以定义分页器的边距，我打算配置一个自定义主题，然而我观察到，在node_modules/antd/lib/table/style/index.css文件中下面这段代码，没有给margin定义less变量，导致我不能实现我的需求，希望可以给它加上less变量
```css
.ant-table-pagination.ant-pagination {
  margin: 16px 0;
}
```
