### ISSUE TITLE
特定情况下，Table组件的TR元素，鼠标hover样式的bug

### ISSUE THREAD

**Issue by Liang-Henry** [ant-design/ant-design#4197]
### 发生问题的环境

- antd 版本: 2.5.1
- 操作系统及其版本: macOS Sierra 10.12.1
- 浏览器及其版本: Chrome 54.0.2840.98 (64-bit)

### 问题描述

在使用 antd Table 组件的时候, 发生tr:hover样式bug, 第4*n行tr无法在鼠标移动到tr上时显示完整的背景色，仅仅显示靠近tr上边界的很窄一条横向背景色

由于是内部系统，不方便截图，只能使用文字描述，抱歉

### 解决方案及疑问

经排查，怀疑是一下两种样式结构引起的bug：
1. 祖先元素的overflow:auto样式
2. 页面上存在position:fixed定位的按钮

移除以上两种样式和页面结构以后，表格tr:hover样式表现正常

**还有一种解决方案**，将
```css
tr:hover {
  background: color;
}
```
修改为
```css
tr:hover td {
  background: color;
}
```
样式表现恢复正常，且不需要改动其他页面结构和样式
是否可以使用这种方式来实现tr:hover的背景色显示，不采用这种方案的原因是什么？
