### ISSUE TITLE
带边框的Table底部缺失圆角

### ISSUE THREAD

**Issue by ZZZCNY** [ant-design/ant-design#42026]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5rzr5k?file=/index.js)

### Steps to reproduce

无

### What is expected?

底部同样有圆角

### What is actually happening?

底部是直角

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 18.2.0 |
| System | macOS 13.3.1 |
| Browser | Edge 112.0.1722.58 |

---
我知道为什么会是直角，就是希望在有边框的时候，底部能是圆角。

**Comment by afc163** [comment]
设计如此，否则下面这种情况下底部圆角不好看。

<img width="379" alt="图片" src="https://user-images.githubusercontent.com/507615/236593659-8a93875e-24c0-4d73-a2ea-8df3effbe7cc.png">

**Comment by ZZZCNY** [comment]
就是做成区分有边框和没有边框两种，有边框是圆角，没有边框是直角

**Comment by afc163** [comment]
这样实现起来会复杂很多很多。

**Comment by slc3a2** [comment]
如果你想要四角都是圆角，可以覆盖`css`，先去掉`<Table />`上的`borded`属性，在添加下面的`css`
```css
:global {
  .ant-table table {
    border-radius: 6px;
    border-collapse: separate;
    border-spacing: 0px;
    overflow: hidden;
    border: 1px solid #f0f0f0;
    .ant-table-thead > tr > th:before {
      width: 0px !important;  // 去掉表头每项的右border
    }
    .ant-table-tbody > tr > td:not(:last-child) {
      border-right: 0 !important;
    }
    .ant-table-tbody > tr:last-child > td {
      border-bottom: 0 !important;
    }
  }
```
