### ISSUE TITLE
Global CSS included with component CSS import

### ISSUE THREAD

**Issue by benthehenten** [ant-design/ant-design#4331]
Thanks for this great library!

I tried to use `babel-plugin-import` to do modular CSS imports, but along with the css for an individual component, there is a lot of global css being imported that interferes with my existing styles. Is it possible to import the CSS for an individual component without global CSS being included?

Thanks!

**Comment by benjycui** [comment]
Do you mean CSS rules like this?

```css
html,
body {
  ...
}
```

**Comment by benthehenten** [comment]
Yes.

**Comment by benjycui** [comment]
It's impossible not to import those CSS rules now.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1966#issuecomment-247946641

You have to override these global styles now.

---

Or you drop the `style` option of `babel-plugin-import`, import the less files indenpently.

```
@import "~antd/lib/style/themes/default.less";
@import "~antd/lib/button/style/index.less";
```

**Comment by Forestdev** [comment]
That's terrible design though.

**Comment by peitalin** [comment]
This issue makes this library very difficult to work with. Especially having global properties on body etc. I think this issue should be made much more clear unless you have plans to change this.

**Comment by benjycui** [comment]
@Forestdev @peitalin it's an known issue, but we don't have enough time to solve this issue.

But we can keep discussing here.

**Comment by benjycui** [comment]
If we can import breaking changes, we can solve this issue. Such as, move styles in reset to components' styles:

Move:

```css
* {
  box-sizing: border-box;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0); //  remove tap highlight color for mobile safari
}
```

To:

```css
.ant-btn,
.ant-btn * {
  box-sizing: border-box;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0); //  remove tap highlight color for mobile safari
}
```

And for backward compatibility, we can provide a standalone reset stylesheet.

```jsx
import 'antd/styles/reset.less'
```
