### ISSUE TITLE
在flex布局中使用Image组件的时候，预览的遮罩层不能正常显示

### ISSUE THREAD

**Issue by Digoler** [ant-design/ant-design#43902]
### Reproduction link

[https://github.com/ant-design/ant-design/tree/master/components/image](https://github.com/ant-design/ant-design/tree/master/components/image)

### Steps to reproduce

```JavaScript
<div className="item">
              <div className="order">{index}</div>
              <div className="time">2023年7月30日23：25</div>
              <div className="image">
                <Image
                  width={100}
                  height={100}
                  src={item.image.src}
                  key={index}
                />
              </div>
              <div className="action">操作</div>
 </div>
```
```css
.item {
  display: flex;
  justify-content: space-around;
  align-items: center;
}
.item div {
  width: 25%;
  height: 50px;
  font-size: 20px;
  font-weight: bold;
  line-height: 50px;
  text-align: center;
  background-color: #aaa;
}
```

### What is expected?

希望遮罩层能够正常显示

### What is actually happening?

遮罩层大小变成了.item div中的25%，而不是和图片大小一样

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | React18 |
| System | window11 |
| Browser | chrome 117.0.5911.2（正式版本）dev （64 位） |

---
使用flex布局实现四列布局，其中第三列为图片预览列
