### ISSUE TITLE
当下拉列表里面有9条或10条数据的时候，Select 组件的滚动条不会出现

### ISSUE THREAD

**Issue by jymsy** [ant-design/ant-design#45935]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dai-sou-suo-kuang-antd-5-11-1-forked-5tw59w?file=/demo.tsx)

### Steps to reproduce

点击select组件，显示下拉列表，不出现滚动条，但是鼠标滚轮可以滚动

### What is expected?

dropdown出现滚动条

### What is actually happening?

dropdown没有滚动条

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | 18 |
| System | windows10 |
| Browser | chrome 119.0.6045.159 |

---
看代码应该是virtual-list问题，inVirtual是false，导致不展示滚动条组件

**Comment by jymsy** [comment]
![动画](https://github.com/react-component/virtual-list/assets/2777671/dfde82cd-c6cc-41bb-9284-b4c89a159ee4)

**Comment by cdx111** [comment]
应该是mac电脑的问题吧

**Comment by jymsy** [comment]
@cdx111 我是Windows，你那没问题？

**Comment by vict-shevchenko** [comment]
I do not think this is a bug, you can show scroll via adding next line of CSS

```css
  .ant-select-dropdown:not(.ant-select-dropdown-hidden) {
    .rc-virtual-list-scrollbar { /* Always show scroll bar in select dropdown menu */
      right: 2px !important; /* look more like native mac os scroll bar */
    }

    .rc-virtual-list-scrollbar-show {
      display: block !important; /* important to overwrite inline style display: none */
    }
  }
  ```
