### ISSUE TITLE
inline 类型的 form Item  的最后一项 是否需要清除 margin-right

### ISSUE THREAD

**Issue by Plutoron** [ant-design/ant-design#46943]
### What problem does this feature solve?

现在默认inline 类型的 表单项都有 margin-right, 布局的时候，最后一项会会多一部分margin，右侧布局的话会导致多余间距

### What does the proposed API look like?

添加 inline 类型 style添加last-child判断

**Comment by MadCcc** [comment]
给个复现例子看看？

**Comment by Wxh16144** [comment]
> 给个复现例子看看？

![image](https://github.com/ant-design/ant-design/assets/25949206/8c533256-fc4a-40f0-9fef-12ae4affa7bd)

感觉确实可以优化一下 🤔，来个 PR

**Comment by Wxh16144** [comment]
之前 Tags 做过一些剥离工作，由于会 break change，所以回滚了。

https://github.com/ant-design/ant-design/pull/47504#issuecomment-1980464898

Form `inline` 如果要做清理，也需要慎重一些。

这么看来却是会有一定风险啊🤔

**Comment by Wxh16144** [comment]
避免和  https://github.com/ant-design/ant-design/pull/47504#issuecomment-1980464898 一样产生 break change ，所以这个问题先不修复。 可以自行用 css 进行覆盖。

将下列 css 样式贴在全局进行覆盖～

```css

/* https://github.com/ant-design/ant-design/issues/46943 */
form[class*="form-inline"] div[class*="form-item"]:last-of-type {
  margin-inline-end: 0;
}

```
