### ISSUE TITLE
Small Table 使用 expandable 有多个子元素样式异常

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#47189]
### Reproduction link

[https://stackblitz.com/edit/react-rvtz1f?file=demo.tsx](https://stackblitz.com/edit/react-rvtz1f?file=demo.tsx)

### Steps to reproduce

点击 click 按钮

### What is expected?

子表格位置不变

### What is actually happening?

子表格位置变了

https://github.com/ant-design/ant-design/assets/7971419/87d979ca-86bf-424d-bf75-2a7066a14de6

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | latest |
| System | mac |
| Browser | edge |

**Comment by crazyair** [comment]
经过讨论，目前 Table 下的子 Table 的 `margin` 样式 `large` 与 `small` `middle` 效果不一致，这个怎么做都是 `breakchange`
另外 `expandedRowRender` 是否需要 `margin` 不太能用 `ant-table` 来判断，需要增加一个 `isNeedMargin` 来控制展开元素是否需要 `marign`

**Comment by crazyair** [comment]
或者默认展开元素全部有 padding，就像 Modal 的 padding一样，用户不需要可以设置 bodyStyle={{ padding:0 }}

![image](https://github.com/ant-design/ant-design/assets/7971419/32725684-c414-4480-b6ee-a1ce7b045d45)

**Comment by afc163** [comment]
默认不太行，用户很可能不希望有这个 margin。

**Comment by MadCcc** [comment]
large 下也加一个 margin 好了？

**Comment by crazyair** [comment]
> large 下也加一个 margin 好了？

large 跟 middle small 写法不一样，large 有 `>`

**Comment by crazyair** [comment]
demo 我修改了，large 不是没有 margin 而是必须第一层就是 ant-table-wrapper

**Comment by Brucia323** [comment]
我希望 `margin-inline-start` 也是 `-16px`
```css
:where(.css-dev-only-do-not-override-i1mju1).ant-table-wrapper .ant-table-tbody >tr >th >.ant-table-wrapper:only-child .ant-table, :where(.css-dev-only-do-not-override-i1mju1).ant-table-wrapper .ant-table-tbody >tr >td >.ant-table-wrapper:only-child .ant-table, :where(.css-dev-only-do-not-override-i1mju1).ant-table-wrapper .ant-table-tbody >tr >th >.ant-table-expanded-row-fixed>.ant-table-wrapper:only-child .ant-table, :where(.css-dev-only-do-not-override-i1mju1).ant-table-wrapper .ant-table-tbody >tr >td >.ant-table-expanded-row-fixed>.ant-table-wrapper:only-child .ant-table {
    margin-block: -16px;
    margin-inline: 32px -16px;
}
```
