### ISSUE TITLE
Checkbox label ellipsis not working

### ISSUE THREAD

**Issue by bertilvdk** [ant-design/ant-design#47296]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/basic-antd-5-13-3-forked-kx5gs2?file=%2Fdemo.tsx%3A33%2C6)

### Steps to reproduce

Reduce the width of the output screen and see that no ellipsis is shown

### What is expected?

Ellipsis is shown

### What is actually happening?

No ellipsis is shown

| Environment | Info |
| --- | --- |
| antd | 5.13.3 |
| React | 18.2.0 |
| System | macOs |
| Browser | Google Chrome |

**Comment by MadCcc** [comment]
Couldn't open your codesandbox

**Comment by bertilvdk** [comment]
Link to codesandbox was updated, should be accessible now.

**Comment by RBilly** [comment]
It could probably be handled better from antd, but there is a simple to make it work.
Create a class like this:
```css
.truncate .ant-checkbox + span {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  width: 100px; // max-width can also be used, and it can be set on parent container as well
}
```
`.truncate` is the name of the class you will apply on the `Checkbox` component
`.ant-checkbox + span` will target the internal span that contains the label of your `Checkbox`

You just need to do
```js
<Checkbox className="truncate">My very long label that I need to truncate</Checkbox>
```
