### ISSUE TITLE
Icon and Button icon not vertically aligned with different font family.

### ISSUE THREAD

**Issue by alexcracea** [ant-design/ant-design#47422]
### Reproduction link

[https://codepen.io/nyph1337/pen/bGZmprO](https://codepen.io/nyph1337/pen/bGZmprO)

### Steps to reproduce

- Use antd 5.14.0 and override config token with new font, for example - "Mukta"

```
<ConfigProvider theme={{
  token: {
    fontFamily: '"Mukta", sans-serif',
  },
}}>
```

- Use an `<Icon>` or `<Button>` with icon component anywhere on the page with icons from antd library

### What is expected?

Icons are vertically aligned / centered within the button or within their text line

### What is actually happening?

Icons are vertically shifting to the top of the button / line whenever a different font is applied
![image](https://github.com/ant-design/ant-design/assets/8779031/59efb1bf-6390-4a1e-a6a3-8c634009b613)
![image](https://github.com/ant-design/ant-design/assets/8779031/56124d98-ecb6-4656-bc2a-75409ad12d20)

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | 18.2.0 |
| System | MacOS Sonoma 14.2.1 |
| Browser | Chrome Version 121.0.6167.160 (Official Build) (x86_64) |

---
After investigating it myself i see the issue is caused by different fonts having different letter baseline placement which ant-design doesn't take into consideration because of `inline-block`  `vertical-align`   `line-height`   `padding` which is not a reliable solution for vertically centering. Sources on the web recommend using a different line-height but that is also not a reliable solution because changing the `contentLineHeight` token to fix this issue will cause the padding to change as well. 

As a workaround: I override the CSS by myself to force a flex vertical alignment with this code snipped applied:

```css
/* Artificially add selector specificity to fix button icon placement issue due to font family differences */

a.ant-btn,
button.ant-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
}
``` 

I recommend relying on proper modern solutions like flex's `align-items` instead of current alignment solution, it feels wrong to apply this workaround like this because it adds selector specificity confusion
