### ISSUE TITLE
密码强度提示条无效

### ISSUE THREAD

**Issue by mydearxym** [ant-design/ant-design#482]
密码强度提示只有文字，没有ui条，应该是相关 css代码 没有编译进去。
在项目中手动添加如下 css 后正常：
```css
.ant-pwd-strength-item {
  float: left;
  margin-right:1px;
  margin-top: 12px;
  width:19px;
  height:8px;
  line-height:8px;
  list-style:none;
  background-color: #f3f3f3;
  transition:all 0.3s cubic-bezier(0.645, 0.045, 0.355, 1);
  -webkit-transition:all 0.3s cubic-bezier(0.645, 0.045, 0.355, 1);
  -moz-transition:all 0.3s cubic-bezier(0.645, 0.045, 0.355, 1);

}

.ant-pwd-strength-low .ant-pwd-strength-item-1, .ant-pwd-strength-medium .ant-pwd-strength-item-1, .ant-pwd-strength-high .ant-pwd-strength-item-1 {
  background-color: #FAC450;
}

.ant-pwd-strength-medium .ant-pwd-strength-item-2, .ant-pwd-strength-high .ant-pwd-strength-item-2 {
  background-color: rgba(135, 208, 104, .6);
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#9987D068,endColorstr=#9987D068);
}

.ant-pwd-strength-high .ant-pwd-strength-item-3 {
  background-color: #87D068;
}

.ant-pwd-strength-item-1 {
  border-top-left-radius: 6px;
  border-bottom-left-radius: 6px;
}

.ant-pwd-strength-item-2 {
  width: 20px;
}

.ant-pwd-strength-item-3 {
  border-top-right-radius: 6px;
  border-bottom-right-radius: 6px;
  margin-right: 8px;
}


```
