### ISSUE TITLE
menu subMenu css

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-design#4906]
1.  subMenu css 缺少 overflow: hidden, 下拉框最后一个选中后的样式是尖角的。。 

2. subMenu 样式多余，右边出现多余线条。。单用 item 时出现的
```css
.ant-menu-vertical {
   border-right: 1px solid #e9e9e9;
} 
.ant-menu-vertical .ant-menu-item{
  border-right: 1px solid #e9e9e9;
}
```
