### ISSUE TITLE
Button width changed when switching loading state

### ISSUE THREAD

**Issue by CallMeXYZ** [ant-design/ant-design#4913]
~

**Comment by benjycui** [comment]
Yep, for IE9/10 doesn't support [transition](http://caniuse.com/#search=transition).

**Comment by benjycui** [comment]
It will be better to write your issue/comment in English, so more people can understand you. And this means that more people can help you or benefit from your issue/comment.

**Comment by benjycui** [comment]
`antd` uses `transition` and `animation` in many cases, so it is expensive and unnecessary to refactor to use JavaScript animation.

**Comment by CallMeXYZ** [comment]
my case comes under Chrome not IE~

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

And steps to re-produce it, a GIF will be better.

**Comment by CallMeXYZ** [comment]
http://codepen.io/CallMeXYZ/pen/JEqjYj?editors=0010

**Comment by benjycui** [comment]
Yep, the animation is weirdo when we use both of `icon` and `loading`.

**Comment by afc163** [comment]
@CallMeXYZ Thx for the codepen, that was helpful!

**Comment by CallMeXYZ** [comment]
how can we fix this in the current version?

**Comment by afc163** [comment]
Override style in your css file like 8dc73f4 does.

**Comment by CallMeXYZ** [comment]
just write some dead  override css like below, would it be no side effect?
```css
.ant-btn.ant-btn-loading:not(.ant-btn-circle):not(.ant-btn-circle-outline) .anticon{
     transition: inherit;
 }
.anticon{
    transition: all 0.3s cubic-bezier(0.645, 0.045, 0.355, 1)
}
```

**Comment by afc163** [comment]
```css
.ant-btn .anticon {
  transition: all 0.3s cubic-bezier(0.645, 0.045, 0.355, 1)
}
.ant-btn.ant-btn-loading:not(.ant-btn-circle):not(.ant-btn-circle-outline) .anticon{
  transition: none;
}
```
