### ISSUE TITLE
4.x的官网文档drawer的样式不符合4.x的css里定义的样式

### ISSUE THREAD

**Issue by ldwonday** [ant-design/ant-design#49288]
### Reproduction link

[https://4x.ant.design/components/drawer-cn/](https://4x.ant.design/components/drawer-cn/)

### Steps to reproduce

drawer第一个例子，点击open，打开开发者模式，查看antd-drawer的css定义，发现只有
```css
.ant-drawer {
    position: fixed;
    inset: 0;
    z-index: 1000;
    pointer-events: none
}
```
点击下方“codesandbox中打开”，点击open查看ant-drawer样式，发现样式如下：
```css
.ant-drawer {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 1000;
    pointer-events: none;
}
```
两个css有区别

### What is expected?

期望文档中drawer的样式和4.x版本中的css定义的一致

### What is actually happening?

不一致，看起来是5.x版本的样式

| Environment | Info |
| --- | --- |
| antd | 4.24.16 |
| React | 18 |
| System | mac |
| Browser | chrome124 |
