### ISSUE TITLE
Controlling the width for drawer component in bottom placement

### ISSUE THREAD

**Issue by mushrafmim** [ant-design/ant-design#50119]
### What problem does this feature solve?

Currently,  the Drawer component in bottom placement takes the entire width of the screen. For larger screens this causes a significant portion of the screen is hidden. What I wish is a width controlling feature for drawer component in bottom placement such that the developer has control over the hidden portion of the screen and by this the developer can keep the width of the form as his wish according to the content he has.

### What does the proposed API look like?

I need to make custom changes to implement this feature. In this manner I achieved this. What I achieved is like this:

![Screen Shot](https://res.cloudinary.com/dgz1ipdtu/image/upload/v1722218856/Screenshot_2024-07-29_at_07.36.21_pifz9c.png)

```css
.ant-drawer-content-wrapper {
  box-shadow: none !important;
}

.ant-drawer-content {
  max-width: 500px;
  position: fixed;
  right: 2rem;
  box-shadow: 0 -6px 16px 0 rgba(0, 0, 0, 0.08),0 -3px 6px -4px rgba(0, 0, 0, 0.12),0 -9px 28px 8px rgba(0, 0, 0, 0.05);
}

@media screen and (max-width: 768px) {
  .ant-drawer-content {
    right: 0;
  }
}
```
