### ISSUE TITLE
fix codecov action for all rc components and @ant-design libraries

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#50387]
参考 https://github.com/react-component/select/pull/1056 的改动。

<img width="714" alt="图片" src="https://github.com/user-attachments/assets/f71a1873-201e-4d4c-9f35-7b1418b7c49b">

- [x] https://github.com/react-component/select https://github.com/react-component/select/pull/1056
- [x] https://github.com/react-component/footer https://github.com/react-component/footer/pull/58/
- [x] https://github.com/react-component/portal https://github.com/react-component/portal/pull/19
- [x] https://github.com/react-component/tour https://github.com/react-component/tour/pull/63
- [x] https://github.com/react-component/async-validator https://github.com/react-component/async-validator/pull/16
- [x] https://github.com/react-component/align https://github.com/react-component/align/pull/300
- [x] https://github.com/react-component/dom-align https://github.com/react-component/dom-align/pull/45
- [x] https://github.com/react-component/color-picker https://github.com/react-component/color-picker/pull/266
- [x] https://github.com/react-component/mutate-observer https://github.com/react-component/mutate-observer/pull/11
- [x] https://github.com/react-component/cascader https://github.com/react-component/cascader/pull/524
- [x] https://github.com/react-component/checkbox https://github.com/react-component/checkbox/pull/290
- [x] https://github.com/react-component/context https://github.com/react-component/context/pull/49
- [x] https://github.com/react-component/collapse https://github.com/react-component/collapse/pull/347
- [x] https://github.com/react-component/dialog https://github.com/react-component/dialog/pull/453
- [x] https://github.com/react-component/drawer https://github.com/react-component/drawer/pull/475
- [x] https://github.com/react-component/dropdown https://github.com/react-component/dropdown/pull/236
- [x] https://github.com/react-component/field-form https://github.com/react-component/field-form/pull/715
- [x] https://github.com/react-component/image https://github.com/react-component/image/pull/367
- [x] https://github.com/react-component/input https://github.com/react-component/input/pull/76
- [x] https://github.com/react-component/input-number https://github.com/react-component/input-number/pull/666
- [x] https://github.com/react-component/mentions https://github.com/react-component/mentions/pull/272
- [x] https://github.com/react-component/menu https://github.com/react-component/menu/pull/735
- [x] https://github.com/react-component/motion https://github.com/react-component/motion/pull/53
- [x] https://github.com/react-component/notification https://github.com/react-component/notification/pull/358
- [x] https://github.com/react-component/pagination https://github.com/react-component/pagination/pull/605
- [x] https://github.com/react-component/picker https://github.com/react-component/picker/pull/861
- [x] https://github.com/react-component/progress https://github.com/react-component/progress/pull/296
- [x] https://github.com/react-component/rate https://github.com/react-component/rate/pull/191
- [x] https://github.com/react-component/resize-observer https://github.com/react-component/resize-observer/pull/209
- [x] https://github.com/react-component/segmented https://github.com/react-component/segmented/pull/251
- [x] https://github.com/react-component/slider https://github.com/react-component/slider/pull/1031
- [x] https://github.com/react-component/steps https://github.com/react-component/steps/pull/367
- [x] https://github.com/react-component/switch https://github.com/react-component/switch/pull/155
- [x] https://github.com/react-component/table https://github.com/react-component/table/pull/1169
- [x] https://github.com/react-component/tabs https://github.com/react-component/tabs/pull/734
- [x] https://github.com/react-component/textarea https://github.com/react-component/textarea/pull/64
- [x] https://github.com/react-component/tooltip https://github.com/react-component/tooltip/pull/479
- [x] https://github.com/react-component/tree https://github.com/react-component/tree/pull/860
- [x] https://github.com/react-component/tree-select https://github.com/react-component/tree-select/pull/554
- [x] https://github.com/react-component/upload https://github.com/react-component/upload/pull/568
- [x] https://github.com/react-component/util https://github.com/react-component/util/pull/576
- [x] https://github.com/react-component/virtual-list https://github.com/react-component/virtual-list/pull/283
- [x] https://github.com/react-component/trigger https://github.com/react-component/trigger/pull/476
- [x] https://github.com/ant-design/ant-design-colors https://github.com/ant-design/ant-design-colors/pull/93
- [x] https://github.com/ant-design/fast-color https://github.com/ant-design/fast-color/pull/56
- [x] https://github.com/ant-design/cssinjs https://github.com/ant-design/cssinjs/pull/191
- [x] https://github.com/ant-design/cssinjs-utils https://github.com/ant-design/cssinjs-utils/pull/16
- [x] https://github.com/ant-design/ant-design-mobile https://github.com/ant-design/ant-design-mobile/pull/6726
- [x] https://github.com/ant-design/react-slick https://github.com/ant-design/react-slick/pull/114

---

可以复制以下内容并替代 main.yml：

```
name: CI

on: ['push', 'pull_request']

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: cache package-lock.json
        uses: actions/cache@v4
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: create package-lock.json
        run: npm i --package-lock-only --ignore-scripts

      - name: hack for singe file
        run: |
          if [ ! -d "package-temp-dir" ]; then
            mkdir package-temp-dir
          fi
          cp package-lock.json package-temp-dir

      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: restore cache from package-lock.json
        uses: actions/cache@v4
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: lint
        run: npm run lint

    needs: setup

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: restore cache from package-lock.json
        uses: actions/cache@v4
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: compile
        run: npm run compile

    needs: setup

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: restore cache from package-lock.json
        uses: actions/cache@v4
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: coverage
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

    needs: setup
```
