### ISSUE TITLE
modal freezes the whole page

### ISSUE THREAD

**Issue by tylerlong** [ant-design/ant-design#51205]
### Reproduction link

[https://github.com/tylerlong/antd-modal-freeze-whole-page-bug-produce](https://github.com/tylerlong/antd-modal-freeze-whole-page-bug-produce)

### Steps to reproduce

Click the button once to open the modal.
Close the modal
Click the button again
You will find that the whole page is frozon and you cannot click anything any more.

### What is expected?

The button should remain clickable and the whole page is not frozen

### What is actually happening?

Button is no clickable any more and the whole page freezes

| Environment | Info |
| --- | --- |
| antd | 5.21.3 |
| React | 18.3.1 |
| System | MacOS 14.4.1 |
| Browser | Chrome 129.0.6668.90  |

---
The following CSS caused it:

```css
body > div {
  position: fixed;
  top: 0;
  left: 0;
  height: 100vh;
  width: 100vw;
}
```

But there is no reason to disallow users to write such CSS.

**Comment by kiner-tang** [comment]
@tylerlong It seems to be Caused by this line style in your example
https://github.com/tylerlong/antd-modal-freeze-whole-page-bug-produce/blob/main/src/index.css
The official example does not have this section of css:
https://stackblitz.com/edit/p8dm1s?file=demo.tsx
<img width="1179" alt="image" src="https://github.com/user-attachments/assets/7d925cf3-d8cf-4932-8b4a-da0404e27cd9">

**Comment by tylerlong** [comment]
Yes, pretty sure it is caused by:

```css
body > div {
  position: fixed;
  top: 0;
  left: 0;
  height: 100vh;
  width: 100vw;
}
```

It turns on that after the first time the modal is shown, it will insert a div under the <body/>, which will be affected by this css rule.
