### ISSUE TITLE
表单输入组件新增 variant 类型 underline

### ISSUE THREAD

**Issue by ilxqx** [ant-design/ant-design#51379]
### What problem does this feature solve?

整体改变一下表单输入类型的组件的风格，我自己通过魔改样式模拟了一下效果：
<img width="1877" alt="image" src="https://github.com/user-attachments/assets/5e845f02-954f-4040-8ab1-a556a6dadb11">

基本上需要增加的一个样式是：
```css
.ant-input-underline {
    border-top: none;
    border-left: none;
    border-right: none; /* 当然这里直接 border: none 也行，但是我感觉好像有点不太优雅 */
    border-bottom: 1px solid var(--ant-color-border);
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
}
/* 当然还有 input，select 等类似输入框的组件的underline样式定义 */
```

### What does the proposed API look like?

目前 variants 仅支持 ["outlined", "borderless", "filled"]，可以再增加一个 underline 的选项让整个表单的输入控件呈现下划线式的风格
