### ISSUE TITLE
AutoComplete 表单项输入内容后高度错误问题

### ISSUE THREAD

**Issue by caijf** [ant-design/ant-design#51669]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/auto-complete-height-problem-9gls4c)

### Steps to reproduce

AutoComplete 在表单中输入或选择值后，高度变化。

无值时，高度为 `32px`：

<img width="540" alt="image" src="https://github.com/user-attachments/assets/1c66d931-a564-416d-92e8-0666ea9fb1cb">

---

有值时，高度为 `37px`：

<img width="542" alt="image" src="https://github.com/user-attachments/assets/68b4ecfc-5484-49f0-8e41-fe76d0827b75">

### What is expected?

AutoComplete 在表单中输入或选择值后，高度不变。

### What is actually happening?

AutoComplete 输入或选择值后，高度会从 `32px` 变成 `37px`。

| Environment | Info |
| --- | --- |
| antd | 5.22.1 |
| React | 18.2.0 |
| System | - |
| Browser | - |

---

```css
// 设置该样式可以临时解决
.ant-form .ant-form-item .ant-form-item-control {
    line-height: 0;
}
```
