### ISSUE TITLE
React使用Tooltip组件时，使用:global改变Tooltip内容区域的宽度时，贴边偏移会失效

### ISSUE THREAD

**Issue by ZhaoXR429** [ant-design/ant-design#52186]
### What problem does this feature solve?

```scss
.tooltip {
  :global(.ant-tooltip-inner) {
    width: 500px;
    padding: 12px 16px;
    background: #fff;
    box-shadow: 0 2px 8px 0 rgba(0, 0, 0, 0.1);
    border-radius: 8px;
    font-size: 14px;
    color: #333;
    line-height: 24px;
  }

  :global(.ant-tooltip-arrow::before) {
    background-color: #fff;
  }
}
```

```tsx
import styles from './index.module.scss'
import { Tooltip } from 'antd'

export const Test = () => {
    return <div>
        <Tooltip title="一段测试文本" overlayClassName={styles.tooltip}>
            Hover me!
        </Tooltip>
    </div>
}
```

当使用 :global 强行覆盖 Tooltip 内部宽度时，贴边偏移会失效。

### What does the proposed API look like?

使用:global覆盖.ant-tooltip-inner的宽度或者为Tooltip组件设置overlayInnerStyle指定宽度时，Tooltip的贴边偏移仍然可以生效。
