### ISSUE TITLE
Auto new line in From label

### ISSUE THREAD

**Issue by TangMonk** [ant-design/ant-design#5285]
In following picture, If the Label is too long, it will be cover by Input:

![image](https://cloud.githubusercontent.com/assets/3498786/23858608/e9826f2a-083b-11e7-9558-02d4b28f2a03.png)

But in Bootstrap, it won't, picture below:

![image](https://cloud.githubusercontent.com/assets/3498786/23858658/23d11f1e-083c-11e7-8bcf-23afabe966fd.png)

How to auto newline if the label is too long?

**Comment by kossel** [comment]
what I do is, I created a class call 'wrap-label' in my less and add it to all the "long labels" which I don't want to wrap.

```
.wrap-label {
.ant-form-item-label {
  white-space: normal;
}
}
```

**Comment by hansnow** [comment]
I add the following styles into `index.less`,
``` less
:global {
  .two-rows-label .ant-form-item-label {
    padding: 4px 0 !important;
    label {
      white-space: normal;
      margin-right: 12px;
      display: inline-block;
      text-align: center;
      line-height: 12px;
      width: 50px;
      &:after {
        content: none !important;
      }
      &.ant-form-item-required:before {
        position: absolute;
        left: -7px;
      }
    }
  }
}
```
and add the classname for `Form.Item` like this: `<Form.Item className={'two-rows-label'}>...</Form.Item>`

finally, we got the effect like this
![image](https://cloud.githubusercontent.com/assets/4365899/24068847/20cded56-0bd4-11e7-84fa-0dd889eed1c9.png)
