### ISSUE TITLE
Support a valueRender prop for Select

### ISSUE THREAD

**Issue by anzuj** [ant-design/ant-design#53603]
### What problem does this feature solve?

More control over the way selected values are shown in multi-selects. There are use cases where we do not want to display tags, for example when we just want to show comma separated values, truncated with an ellipsis. Analog to [MUI Select's](https://mui.com/material-ui/api/select/) renderValue

### What does the proposed API look like?

Support a `valueRender` prop allows replacing the content inside .ant-select-selection-overflow div, giving control to how you want to display the array of selected values.
```html
<Select
    className="my-select"
    mode="multiple"
    options={[{
    label: 'Administration category A',
    value: 1,
  }, {
    label: 'Administration category B',
    value: 2,
  }, {
    label: 'Administration category C',
    value: 3,
  }]}
    defaultValue={[1,2]}
    valueRender={values => `${values.map(value => value.label).join(', ')}`}
```
This would yield the below HTML
```html
<div class="my-select ant-select ant-select-multiple">
    <div class="ant-select-selector">
        <div class="ant-select-selection-wrap">
            <div class="ant-select-selection-overflow">
                  Administration category A, Administration category B
            </div>
        </div>
    </div>
</div>
```
Which we can style to achieve the overflow ellipsis and a simplified text value display
```css
.my-select.ant-select-multiple .ant-select-selector .ant-select-selection-wrap .ant-select-selection-overflow {
    white-space: nowrap;
    text-overflow: ellipsis;
}
```

**Comment by afc163** [comment]
`label` is all you need.

**Comment by MadCcc** [comment]
https://ant.design/components/select#select-demo-option-render
Did you mean this?

**Comment by anzuj** [comment]
@Wxh16144 Thank you for thinking along but I think using `getRawInputElement` to overwrite the underlying `Input` adds unnecessary complexity, extra state management and loses a bulk of the `Select` out-of-the-box functionality. In practice I would have to carefully reassign all validation props, mimic the dropdown toggle, implement the clear icon + functionality etc.
> There is an internal method that can directly modify the selector trigger, allowing for customized display content.

@afc163 Can you clarify your comment please? How can the `label` achieve a multiple Select value being displayed as "Administration A, Administr..." without the tags?

**Comment by anzuj** [comment]
For the time being this is a "hacky" workaround I've come up with: 

```html
<Select
    className="my-select"
    mode="multiple"
    options={[{
       label: 'Administration category A',
       value: 1,
     }, {
       label: 'Administration category B',
       value: 2,
    }, {
      label: 'Administration category C',
      value: 3,
    }]}
    maxTagCount={0}
    maxTagPlaceholder={(omittedValues)=> {
       const valueString = omittedValues.map(omittedValue => omittedValue.label).join(', ')
       return <Tooltip title={valueString}>{valueString}</Tooltip>
    }}

   />
```

Coupled with scss to overwrite Ant Design's attempt to leave space for tags + search
```scss
.my-select.ant-select-multiple {
    height: 32px;
    max-height:32px;
    .ant-select-selector {
        &:after{
            margin: 0;
            line-height:21px;
        }
        
        .ant-select-selection-wrap {
            align-self:center;
            &:after{
                margin-block:0;
                margin: 0;
                line-height:21px;
            }
            .ant-select-selection-overflow {
                white-space: nowrap;
                text-overflow: ellipsis;
            }
    
            .ant-select-selection-overflow-item-suffix {
              position: absolute;
              right: 0;
              margin-block: 0;
            }
    
            .ant-select-selection-item {
                background: none;
            }
        }
    }
}
```

I realise Ant Design is a design system, but flexibility in allowing users to divert from the default tag rendering would be very welcome and. In many real-world scenarios even necessary. Below is an example from the dashboard I'm working on:

![Image](https://github.com/user-attachments/assets/8cc42442-afe5-4ff6-9b00-089c40feec74)

Since the first selected value was just 2 characters too long for the `Select` to fully show as a tag, we see no value information anymore whatsoever. To show the shorter labels when possible also requires `maxTagCount="responsive" ` which as we know has a performance cost. My use case would be solved with the `valueRender ` prop without having to hack scss and I dare to guess I'm not alone as most other UI systems (MUI, Vuetify etc) all support this functionality with no fuss.
