### ISSUE TITLE
fixed header table have style problem when data is not enough

### ISSUE THREAD

**Issue by daskyrk** [ant-design/ant-design#5639]
### Version
2.8.3

### Environment
mac 10.12.3, Chrome 57.0.2987.110

### Reproduction link
[http://codepen.io/daskyrk/pen/ZeZMEv](http://codepen.io/daskyrk/pen/ZeZMEv)

### Steps to reproduce
use the demo code, reduce the table data less than 4, when the height is not enough for scroll
```javascript
for (let i = 0; i < 20; i  ) { // reduce data to less than 4 and the scroll bar will not disappear
  data.push({
    key: i,
    name: `Edward King ${i}`,
    age: 32,
    address: `London, Park Lane no. ${i}`,
  });
}
```
so i add the scroll style to fix it, and it works:
```css
.ant-table-header {
  overflow-y: auto !important;
}

.ant-table-body {
  overflow-y: auto !important;
}
```

### What is expected?
when table data is not enough, the scroll bar should disappear

### What is actually happening?
when table data is not enough, the scroll bar not disappear, which seems to be a little weird
