### ISSUE TITLE
表单样式问题

### ISSUE THREAD

**Issue by likezero** [ant-design/ant-design#636]
index.less 里面有这样的样式，范围影响也太大了吧。内联表单div样式全乱了！
``` css
.ant-form-inline div {
  display: inline-block;
}
````
