### ISSUE TITLE
对 td.ant-table-selection-column 设置 CSS 无效

### ISSUE THREAD

**Issue by TheWaWaR** [ant-design/ant-design#649]
``` css
th.ant-table-selection-column,
td.ant-table-selection-column {
    width: 28px;
    padding: 0;
}
```

设了上面的 CSS 后，`th.ant-table-selection-column` 宽还是 `60px` ，猜想这个宽度是 antd 计算出来然后设置的，这样不方便定制样式吧？
