### ISSUE TITLE
Missing style for Anchor Link

### ISSUE THREAD

**Issue by froston** [ant-design/ant-design#7712]
### Version
2.12.2

### Environment
Chrome 60

### Reproduction link
[https://ant.design/components/anchor](https://ant.design/components/anchor)

### Steps to reproduce
Missing syle for class `.ant-anchor-link `

### What is expected?
```css
.ant-anchor-link {
  padding: 8px 0 8px 18px;
  line-height: 1;
}
```
### What is actually happening?
Breaks the layout of links.
