### ISSUE TITLE
table: when header is fixed, header scrollbar should not be displayed

### ISSUE THREAD

**Issue by abenhamdine** [ant-design/ant-design#8414]
### Version
3.0.0RC4

### Environment
Windows 10, Chrome 63

### Reproduction link
[http://beta.ant.design/components/table/#components-table-demo-fixed-header](http://beta.ant.design/components/table/#components-table-demo-fixed-header)

### Steps to reproduce
Just see header in example http://beta.ant.design/components/table/#components-table-demo-fixed-header

### What is expected?
If the header is fixed, no scrollbar should be displayed for the header

### What is actually happening?
The vertical scrollbar is displayed, while useless because disabled

---
Possible fix: 
```css
.ant-table-fixed-header .ant-table-scroll .ant-table-header {
    overflow: hidden; /* instead of overflow:scroll */
}
```
