### ISSUE TITLE
谷歌浏览器升级到63版本之后，Table组件出现抽搐动画。。

### ISSUE THREAD

**Issue by zoufegnrui921017** [ant-design/ant-design#8509]
antd版本2.12.0
谷歌浏览器版本63.0.3239.84
在此版本状态下，antd的table组件在进行渲染的时候会出现抖动，初步猜测判断为padding或者margin的变化，并且有一个包裹住的div会在渲染途中出现，在渲染完成后消失。

![image](https://user-images.githubusercontent.com/21168791/33749740-747bed48-dc0a-11e7-8706-39f7b441c3e6.png)

![image](https://user-images.githubusercontent.com/21168791/33749745-80e6b34c-dc0a-11e7-9679-c1463624e2bc.png)

在谷歌62版本和火狐。Safari浏览器都没有此现象

**Comment by megoodroid** [comment]
same problem after i upgrade chrome to version 63

**Comment by megoodroid** [comment]
this problem is not exist when i upgrade antd to version 2.13.11, my preview antd version is 2.7.2

**Comment by zoufegnrui921017** [comment]
@megoodroid yeah,I was also guessing that this was a solution，but in our project ,we can't upgrade antd version without  discuss and the points meeting.

**Comment by frankywen** [comment]
@zoufegnrui921017

**Comment by frankywen** [comment]
@zoufegnrui921017 
I have the same problem. Did you fix it

**Comment by ckinmind** [comment]
我们同样遇到这个问题，chrome版本在63以上，antd版本在2.13以下的会有抖动的问题，升到2.13.2以上就没这个问题了

**Comment by lcoder** [comment]
我找到问题了：
```css
.ant-spin-blur {
    overflow: hidden;
    opacity: 0.7;
    -webkit-filter: blur(.01px);
    filter: blur(0.5px); 
    filter: progid\:DXImageTransform\.Microsoft\.Blur(PixelRadius\=1, MakeShadow\=false);
    -webkit-transform: translateZ(0);
}
```
关键是filter属性，我发现有filter和没filter，table会抖动一下。大伙可以试试。我的版本是`2.10.0`，另外，不知道咋解决。

**Comment by lcoder** [comment]
解决啦，解决啦，解决啦，`2.10.0`版本之下的，可以添加如下代码：
```css
body {
    .ant-spin-container {
        transition: opacity 0.3s cubic-bezier(0.645, 0.045, 0.355, 1) ;
    }
}
```
主要是filter属性，应用了过渡动画，导致的抖动问题。我把过渡的all，修改成了opacity，因为`.ant-spin-container`主要动画是opacity，忽略filter的过渡。bug完美解决。
