### ISSUE TITLE
常用布局 demo 代码 typo

### ISSUE THREAD

**Issue by raptium** [ant-design/ant-design#870]
http://ant.design/docs/spec/layout#layout-demo-top

多个布局的 Demo CSS 代码里有个 `:` 敲成了 `;`

```css
.ant-layout-aside .ant-layout-footer {
  height; 64px;
  line-height: 64px;
  text-align: center;
  font-size: 12px;
  color: #999;
  background: #fff;
  border-top: 1px solid #e9e9e9;
  width: 100%;
}
```
