### ISSUE TITLE
How to always show clear btn after datepicker have value

### ISSUE THREAD

**Issue by zeing** [ant-design/ant-design#9233]
### What problem does this feature solve?
Now : in Datepicker  input if mouse cursor hover on input which have data will show clear button 

I want  clear btn always show  after input(datepicker) have data

### What does the proposed API look like?
```
<RangePicker
    alwaysClearbtn = { true}
    />
  </div>
```

**Comment by yesmeck** [comment]
```css
.ant-calendar-picker-clear {
    opacity: 1;
}
```
