### ISSUE TITLE
Carousel don't show only one item

### ISSUE THREAD

**Issue by geraldchen890806** [ant-design/ant-design#9433]
### Version
3.2.2

### Environment
chrome

### Reproduction link
[https://codepen.io/geraldchen89/pen/gvQXQO](https://codepen.io/geraldchen89/pen/gvQXQO)

### Steps to reproduce
```
ReactDOM.render(
  <Carousel >
    <div><h3>1</h3></div>
  </Carousel>
, mountNode);

//now fixed by  effect={events.length === 1 ? 'fade' : 'scrollx'}
```

### What is expected?
show item

### What is actually happening?
no item show

**Comment by zhangchao828** [comment]
+1

**Comment by valleykid** [comment]
The thanslateX value is wrong, I'll fix it just soon. You can use the hack as below:
```css
.ant-carousel .slick-track .slick-slide:only-child {
  margin-left: 28.5% !important;
}
```
