### ISSUE TITLE
表单项的间距大，导致页面利用率较低问题请教

### ISSUE THREAD

**Issue by ganxunzou** [ant-design/ant-design#9713]
### What problem does this feature solve?
ant-design 一个强大的前端UI框架。但是我们的系统是企业内部应用，一个页面表单项较多，一个大约有50-80项之间。ant-design的表单间隙较大，原来我们一个页面能正屏能显示的，现在用ant-design后界面必须滚动，而且可视区域明显内的表单在20项左右。这样导致页面查看起来不方便。
![](https://pic1.zhimg.com/50/v2-e5b6fe1e48425099bd2cb5dd2f9ee66a_hd.jpg)
从功能看这个可视区域是为了显示错误信息，很多时候我们表单并不需要验证报错，就会浪费这个区域。
（PS：提供的时候不能添加图片，因此我在知乎上提了相关问题：https://www.zhihu.com/question/268970244）

### What does the proposed API look like?
以下个人几点优化建议：

- 1. 给Form增加size属性：large，default，small。用于控制表单输入项上下间距的大小。
- 2. 给Form增加一个errorLayout属性：hide，auto，show。
  - hide：输入项之间的上下间距始终固定间距。验证报错后比显示错误信息，输入项外框变红，输入项获取焦点后toolTip显示报错信息。用户更改信息后ToolTip消失。
  -   auto：输入项之间的上下间距根据验证报错信息自动扩张。未验证前输入项上下间距根据size属性控制，验证报错后，增加验证报错信息高度 间距高度显示。用户输入过程中隐藏报错信息，并还原上下间距（界面会跳动，这个没有想到更好的方案了，为了保持"用户交互后，隐藏报错信息"这个交互风格）
  -  show：和现在保持一直。但是多了size的控制。

（PS：很抱歉个人英文不好，这个一大段的描述，如果用英文估计会完全失去它原本要表达的意思。）

**Comment by dengfuping** [comment]
@ganxunzou The implement of `Form` follows the design principles and I don't think that there is need to supply the choice as you said. After all, it will result of page trembling. However, supplying a choice to display warning information behind the `FormItem` and make the `margin-bottom 0px` between two FormItems could be more useful to solve your problem.

**Comment by ganxunzou** [comment]
很抱歉截图给你产生的误导，我们的表单布局不是单列的，是多列模式。例如下图：
![image](https://user-images.githubusercontent.com/5092728/37564483-d72bd5b4-2ad1-11e8-9d6c-0741109ce7b6.png)
如果把错误信息放到FormItem后面的话，这个表单会更乱了。

**Comment by dengfuping** [comment]
@ganxunzou If you just want to make margin smaller, set the style of `FormItem` to `margin-bottom: 0px` directly will be easier as the demo shows https://codesandbox.io/s/jvl0k7yk0v.

**Comment by mrukas** [comment]
https://www.youtube.com/watch?v=RDrfE9I8_hs

**Comment by RoselinOldham** [comment]
https://www.youtube.com/watch?v=RDrfE9I8_hs

**Comment by Nokecy** [comment]
Rewritten FormItem @ganxunzou

**Comment by Lanboo** [comment]
``` css
:global {
  // 表单间隔 Start
  .ant-form-item {
    margin-bottom: 16px !important;
  }
  .ant-form-item-with-help {
    margin-bottom: 0 !important;
  }
  .ant-form-item-explain,
  .ant-form-item-extra {
    min-height: 16px !important;
    line-height: 1 !important;
  }
  // 表单间隔 End
}
```
