### ISSUE TITLE
Menu inline to the right of a content shows border to the right and not to the left. Or disable border at all.

### ISSUE THREAD

**Issue by ghost** [ant-design/ant-design#9866]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
React 16.2, Chrome 65, Win 10, NodeJS 8

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m7norlqpp9)

### Steps to reproduce
In Menu component (https://github.com/ant-design/ant-design/blob/master/components/menu/index.tsx) I see this:

```typescript
export type MenuMode = 'vertical' | 'vertical-left' | 'vertical-right' | 'horizontal' | 'inline';
```

So I go here: https://github.com/ant-design/ant-design/blob/master/components/menu/style/index.less and after view these two files I understand that there is no possible `inline-right` style. Is this a precise will?

Can we use something like this?

````less
&-inline,
&-vertical,
&-vertical-left {
  border-right: @border-width-base @border-style-base @border-color-split;
}
&-inline-right, // THIS ONE
&-vertical-right {
  border-left: @border-width-base @border-style-base @border-color-split;
}
```

And a way to disable border at all?

### What is expected?
Menu inline to the right of a Content or a generic div. Or maybe disable border at all.

### What is actually happening?
Border just to the right also when the Menu is on the right.


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->
