### ISSUE TITLE
RangePicker: allow the range separator to be overridden

### ISSUE THREAD

**Issue by szdc** [ant-design/ant-design#9891]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There is currently no way of overriding the range picker separator to set a custom value, e.g. 2018-01-01 to 2018-01-31, where " to " is an example of a custom value.  This would allow us to use wording that better reflects how we are using the RangePicker.

### What does the proposed API look like?
The `RangePicker` component accepts a new prop called `separator` which has a default value of `" ~ "` to match the current functionality.

**Comment by ddcat1115** [comment]
I think this is a useful but not not frequently used feature, or would you like to give us a PR?

**Comment by szdc** [comment]
I'd be happy to give you a PR

**Comment by austinpickett** [comment]
Would love to see this go to production. I'm hoping to change the tilde to something as simple as a hyphen without having to resort to using two separate DatePicker components.

**Comment by scottclayton** [comment]
@szdc @austinpickett 
If you're looking for a workaround for now, I found that doing it in CSS can kind of work:

```less
  .ant-calendar-range-picker-separator {
    position: relative;
    color: transparent;
    top: -18px;
  }
  .ant-calendar-range-picker-separator:after {
    content: "to";
  }
```

You may have to adjust the `top` and perhaps add a `left` property to adjust in there too, depending on your implementation.

**Comment by scottclayton** [comment]
Another alternative workaround using a bit of CSS, but might solve other potential formatting problems if you have access to the start-date and end-date:

- give your `<RangePicker />` a `className="range-picker-format-override"`
- have the following CSS:
```css
.range-picker-format-override {
  .ant-calendar-range-picker-separator {
    display: none;
  }
  
  .ant-calendar-range-picker-input:nth-of-type(1) {
    width: 100%;
  }
  .ant-calendar-range-picker-input:nth-of-type(2) {
    display: none;
  }
}
```
- give a prop to your `<RangePicker />` like:
```
format={`[${moment(startDate).format('MMM Do, YYYY')} to ${moment(endDate).format('MMM Do, YYYY')}]`}
```
