### ISSUE TITLE
[Tree] hope to can hide the icon on leaf

### ISSUE THREAD

**Issue by muzea** [ant-design/ant-design#9959]
### What problem does this feature solve?
hide the icon on leaf

### What does the proposed API look like?
add a props like `hideLeftIcon`

### Now
![image](https://user-images.githubusercontent.com/7843281/38464505-6a6e247e-3b41-11e8-9227-d01db66c0e14.png)

### Hope it will be
![image](https://user-images.githubusercontent.com/7843281/38464515-8d2b424e-3b41-11e8-9dbc-d9bfa14bd3bc.png)

We added some styles to hide it

```css
.ant-tree-show-line .ant-tree-switcher.ant-tree-switcher-noop:after{
  content: ' ' !important;
  width: 1px !important;
  border-left: 1px solid #d9d9d9 !important;
  height: 100% !important;
  position: absolute !important;
  left: 12px !important;
}
.ant-tree-show-line .ant-tree-switcher.ant-tree-switcher-noop:before{
  content: ' ';
  width: 16px;
  border-bottom: 1px solid #d9d9d9;
  height: 38%;
  position: absolute;
  left: 12px;
}

.ant-tree-show-line > li:last-child >  .ant-tree-switcher.ant-tree-switcher-noop:before{
  display: block;
  content: ' ' !important;
  width: 16px !important;
  border-left: 1px solid #d9d9d9 !important;
  border-bottom: 1px solid #d9d9d9 !important;
  height: 38% !important;
  position: absolute !important;
  left: 12px !important;
}


.ant-tree-show-line .ant-tree-child-tree  > li:last-child >  .ant-tree-switcher.ant-tree-switcher-noop:before{
  display: block;
  content: ' ' !important;
  width: 16px !important;
  border-left: 1px solid #d9d9d9 !important;
  border-bottom: 1px solid #d9d9d9 !important;
  height: 38% !important;
  position: absolute !important;
  left: 12px !important;
}

.ant-tree-show-line > li:last-child >  .ant-tree-switcher.ant-tree-switcher-noop:after{
  display: none !important;
}

.ant-tree-show-line .ant-tree-child-tree  > li:last-child >  .ant-tree-switcher.ant-tree-switcher-noop:after{
  display: none !important;
}
```
But here is too many `important`, so we hope to provide an option to hide icon
